-- +goose Up
-- BQ dashboard location taxonomy: seed shed rows under the existing CBE/CPT park-scope locations.
-- CBE/CPT stay as parks because old-tag scopes already depend on those location rows.
WITH bq_sheds(farm_code, shed_name) AS (
  VALUES
    ('CBE', 'Castro 1'),
    ('CBE', 'Castro 2'),
    ('CBE', 'Castro 3'),
    ('CBE', 'Gandhi 1'),
    ('CBE', 'Gandhi 1 - Part 1'),
    ('CBE', 'Gandhi 1 - Part 2'),
    ('CBE', 'Gandhi 2'),
    ('CBE', 'Gandhi 3'),
    ('CBE', 'Godel 1 - Part 1'),
    ('CBE', 'Godel 1 - Part 10'),
    ('CBE', 'Godel 1 - Part 2'),
    ('CBE', 'Godel 1 - Part 3'),
    ('CBE', 'Godel 1 - Part 4'),
    ('CBE', 'Godel 1 - Part 5'),
    ('CBE', 'Godel 1 - Part 6'),
    ('CBE', 'Godel 1 - Part 7'),
    ('CBE', 'Godel 1 - Part 8'),
    ('CBE', 'Godel 1 - Part 9'),
    ('CBE', 'Godel 2 - Part 1'),
    ('CBE', 'Godel 2 - Part 10'),
    ('CBE', 'Godel 2 - Part 2'),
    ('CBE', 'Godel 2 - Part 3'),
    ('CBE', 'Godel 2 - Part 4'),
    ('CBE', 'Godel 2 - Part 5'),
    ('CBE', 'Godel 2 - Part 6'),
    ('CBE', 'Godel 2 - Part 7'),
    ('CBE', 'Godel 2 - Part 8'),
    ('CBE', 'Godel 2 - Part 9'),
    ('CBE', 'Ho Chi Minh 1'),
    ('CBE', 'Ho Chi Minh 2'),
    ('CBE', 'Mandela 1 - Part 1'),
    ('CBE', 'Mandela 1 - Part 2'),
    ('CBE', 'Mandela 1 - Part 3'),
    ('CBE', 'Mandela 1 - Part 4'),
    ('CBE', 'Mandela 1 - Part 5'),
    ('CBE', 'Mandela 1 - Part 6'),
    ('CBE', 'Mandela 1 - Part 7'),
    ('CBE', 'Mandela 2 - Part 1'),
    ('CBE', 'Mandela 2 - Part 2'),
    ('CBE', 'Mandela 2 - Part 3'),
    ('CBE', 'Mandela 2 - Part 4'),
    ('CBE', 'Mandela 2 - Part 5'),
    ('CBE', 'Mandela 2 - Part 6'),
    ('CBE', 'Mandela 2 - Part 7'),
    ('CBE', 'Mandela 2 - Part 8'),
    ('CBE', 'Q1'),
    ('CBE', 'Q2'),
    ('CBE', 'Q3'),
    ('CBE', 'Sumathi 1 - Part 1'),
    ('CBE', 'Sumathi 1 - Part 10'),
    ('CBE', 'Sumathi 1 - Part 2'),
    ('CBE', 'Sumathi 1 - Part 3'),
    ('CBE', 'Sumathi 1 - Part 4'),
    ('CBE', 'Sumathi 1 - Part 5'),
    ('CBE', 'Sumathi 1 - Part 6'),
    ('CBE', 'Sumathi 1 - Part 7'),
    ('CBE', 'Sumathi 1 - Part 8'),
    ('CBE', 'Sumathi 1 - Part 9'),
    ('CBE', 'Sumathi 2 - Part 1'),
    ('CBE', 'Sumathi 2 - Part 10'),
    ('CBE', 'Sumathi 2 - Part 2'),
    ('CBE', 'Sumathi 2 - Part 3'),
    ('CBE', 'Sumathi 2 - Part 4'),
    ('CBE', 'Sumathi 2 - Part 5'),
    ('CBE', 'Sumathi 2 - Part 6'),
    ('CBE', 'Sumathi 2 - Part 7'),
    ('CBE', 'Sumathi 2 - Part 8'),
    ('CBE', 'Sumathi 2 - Part 9'),
    ('CBE', 'Yashoda 1'),
    ('CBE', 'Yashoda 10'),
    ('CBE', 'Yashoda 2'),
    ('CBE', 'Yashoda 3'),
    ('CBE', 'Yashoda 4'),
    ('CBE', 'Yashoda 5'),
    ('CBE', 'Yashoda 6'),
    ('CBE', 'Yashoda 7'),
    ('CBE', 'Yashoda 8'),
    ('CBE', 'Yashoda 9'),
    ('CPT', 'Castro 1'),
    ('CPT', 'Castro 2'),
    ('CPT', 'Gandhi 1'),
    ('CPT', 'Gandhi 2'),
    ('CPT', 'Gandhi 3'),
    ('CPT', 'Godel 1 - Part 1'),
    ('CPT', 'Godel 1 - Part 10'),
    ('CPT', 'Godel 1 - Part 2'),
    ('CPT', 'Godel 1 - Part 3'),
    ('CPT', 'Godel 1 - Part 4'),
    ('CPT', 'Godel 1 - Part 5'),
    ('CPT', 'Godel 1 - Part 6'),
    ('CPT', 'Godel 1 - Part 7'),
    ('CPT', 'Godel 1 - Part 8'),
    ('CPT', 'Godel 1 - Part 9'),
    ('CPT', 'Godel 2 - Part 1'),
    ('CPT', 'Godel 2 - Part 10'),
    ('CPT', 'Godel 2 - Part 2'),
    ('CPT', 'Godel 2 - Part 3'),
    ('CPT', 'Godel 2 - Part 4'),
    ('CPT', 'Godel 2 - Part 5'),
    ('CPT', 'Godel 2 - Part 6'),
    ('CPT', 'Godel 2 - Part 7'),
    ('CPT', 'Godel 2 - Part 8'),
    ('CPT', 'Godel 2 - Part 9'),
    ('CPT', 'Ho Chi Minh 1'),
    ('CPT', 'Ho Chi Minh 2'),
    ('CPT', 'Mandela 1 - Part 1'),
    ('CPT', 'Mandela 1 - Part 10'),
    ('CPT', 'Mandela 1 - Part 2'),
    ('CPT', 'Mandela 1 - Part 3'),
    ('CPT', 'Mandela 1 - Part 4'),
    ('CPT', 'Mandela 1 - Part 5'),
    ('CPT', 'Mandela 1 - Part 6'),
    ('CPT', 'Mandela 1 - Part 7'),
    ('CPT', 'Mandela 1 - Part 8'),
    ('CPT', 'Mandela 1 - Part 9'),
    ('CPT', 'Mandela 2 - Part 1'),
    ('CPT', 'Mandela 2 - Part 10'),
    ('CPT', 'Mandela 2 - Part 2'),
    ('CPT', 'Mandela 2 - Part 3'),
    ('CPT', 'Mandela 2 - Part 4'),
    ('CPT', 'Mandela 2 - Part 5'),
    ('CPT', 'Mandela 2 - Part 6'),
    ('CPT', 'Mandela 2 - Part 7'),
    ('CPT', 'Mandela 2 - Part 8'),
    ('CPT', 'Mandela 2 - Part 9'),
    ('CPT', 'Old Yashoda 1'),
    ('CPT', 'Old Yashoda 2'),
    ('CPT', 'Old Yashoda 3'),
    ('CPT', 'Old Yashoda 4'),
    ('CPT', 'Old Yashoda 5'),
    ('CPT', 'Sumathi 1 - Part 1'),
    ('CPT', 'Sumathi 1 - Part 10'),
    ('CPT', 'Sumathi 1 - Part 2'),
    ('CPT', 'Sumathi 1 - Part 3'),
    ('CPT', 'Sumathi 1 - Part 4'),
    ('CPT', 'Sumathi 1 - Part 5'),
    ('CPT', 'Sumathi 1 - Part 6'),
    ('CPT', 'Sumathi 1 - Part 7'),
    ('CPT', 'Sumathi 1 - Part 8'),
    ('CPT', 'Sumathi 1 - Part 9'),
    ('CPT', 'Sumathi 2 - Part 1'),
    ('CPT', 'Sumathi 2 - Part 10'),
    ('CPT', 'Sumathi 2 - Part 2'),
    ('CPT', 'Sumathi 2 - Part 3'),
    ('CPT', 'Sumathi 2 - Part 4'),
    ('CPT', 'Sumathi 2 - Part 5'),
    ('CPT', 'Sumathi 2 - Part 6'),
    ('CPT', 'Sumathi 2 - Part 7'),
    ('CPT', 'Sumathi 2 - Part 8'),
    ('CPT', 'Sumathi 2 - Part 9'),
    ('CPT', 'Yashoda 1'),
    ('CPT', 'Yashoda 2'),
    ('CPT', 'Yashoda 3'),
    ('CPT', 'Yashoda 4')
), normalized_sheds AS (
  SELECT DISTINCT
    farm_code,
    shed_name,
    upper(farm_code || '_SHED_' || regexp_replace(regexp_replace(trim(shed_name), '[^A-Za-z0-9]+', '_', 'g'), '(^_|_$)', '', 'g')) AS location_code
  FROM bq_sheds
), parent_parks AS (
  SELECT tenant_id, location_code, location_id
  FROM locations
  WHERE tenant_id = '00000000-0000-4000-8000-000000000001'::uuid
    AND location_type = 'park'
    AND location_code IN ('CBE', 'CPT')
)
INSERT INTO locations (
  tenant_id,
  location_type,
  location_code,
  name,
  parent_location_id,
  country,
  timezone,
  status,
  created_at
)
SELECT
  '00000000-0000-4000-8000-000000000001'::uuid,
  'shed',
  n.location_code,
  n.shed_name,
  p.location_id,
  'IN',
  'Asia/Kolkata',
  'active',
  now()
FROM normalized_sheds n
JOIN parent_parks p ON p.location_code = n.farm_code
ON CONFLICT (tenant_id, location_code) DO UPDATE SET
  name = EXCLUDED.name,
  parent_location_id = EXCLUDED.parent_location_id,
  status = 'active';

WITH bq_sheds(farm_code, shed_name) AS (
  VALUES
    ('CBE', 'Castro 1'),
    ('CBE', 'Castro 2'),
    ('CBE', 'Castro 3'),
    ('CBE', 'Gandhi 1'),
    ('CBE', 'Gandhi 1 - Part 1'),
    ('CBE', 'Gandhi 1 - Part 2'),
    ('CBE', 'Gandhi 2'),
    ('CBE', 'Gandhi 3'),
    ('CBE', 'Godel 1 - Part 1'),
    ('CBE', 'Godel 1 - Part 10'),
    ('CBE', 'Godel 1 - Part 2'),
    ('CBE', 'Godel 1 - Part 3'),
    ('CBE', 'Godel 1 - Part 4'),
    ('CBE', 'Godel 1 - Part 5'),
    ('CBE', 'Godel 1 - Part 6'),
    ('CBE', 'Godel 1 - Part 7'),
    ('CBE', 'Godel 1 - Part 8'),
    ('CBE', 'Godel 1 - Part 9'),
    ('CBE', 'Godel 2 - Part 1'),
    ('CBE', 'Godel 2 - Part 10'),
    ('CBE', 'Godel 2 - Part 2'),
    ('CBE', 'Godel 2 - Part 3'),
    ('CBE', 'Godel 2 - Part 4'),
    ('CBE', 'Godel 2 - Part 5'),
    ('CBE', 'Godel 2 - Part 6'),
    ('CBE', 'Godel 2 - Part 7'),
    ('CBE', 'Godel 2 - Part 8'),
    ('CBE', 'Godel 2 - Part 9'),
    ('CBE', 'Ho Chi Minh 1'),
    ('CBE', 'Ho Chi Minh 2'),
    ('CBE', 'Mandela 1 - Part 1'),
    ('CBE', 'Mandela 1 - Part 2'),
    ('CBE', 'Mandela 1 - Part 3'),
    ('CBE', 'Mandela 1 - Part 4'),
    ('CBE', 'Mandela 1 - Part 5'),
    ('CBE', 'Mandela 1 - Part 6'),
    ('CBE', 'Mandela 1 - Part 7'),
    ('CBE', 'Mandela 2 - Part 1'),
    ('CBE', 'Mandela 2 - Part 2'),
    ('CBE', 'Mandela 2 - Part 3'),
    ('CBE', 'Mandela 2 - Part 4'),
    ('CBE', 'Mandela 2 - Part 5'),
    ('CBE', 'Mandela 2 - Part 6'),
    ('CBE', 'Mandela 2 - Part 7'),
    ('CBE', 'Mandela 2 - Part 8'),
    ('CBE', 'Q1'),
    ('CBE', 'Q2'),
    ('CBE', 'Q3'),
    ('CBE', 'Sumathi 1 - Part 1'),
    ('CBE', 'Sumathi 1 - Part 10'),
    ('CBE', 'Sumathi 1 - Part 2'),
    ('CBE', 'Sumathi 1 - Part 3'),
    ('CBE', 'Sumathi 1 - Part 4'),
    ('CBE', 'Sumathi 1 - Part 5'),
    ('CBE', 'Sumathi 1 - Part 6'),
    ('CBE', 'Sumathi 1 - Part 7'),
    ('CBE', 'Sumathi 1 - Part 8'),
    ('CBE', 'Sumathi 1 - Part 9'),
    ('CBE', 'Sumathi 2 - Part 1'),
    ('CBE', 'Sumathi 2 - Part 10'),
    ('CBE', 'Sumathi 2 - Part 2'),
    ('CBE', 'Sumathi 2 - Part 3'),
    ('CBE', 'Sumathi 2 - Part 4'),
    ('CBE', 'Sumathi 2 - Part 5'),
    ('CBE', 'Sumathi 2 - Part 6'),
    ('CBE', 'Sumathi 2 - Part 7'),
    ('CBE', 'Sumathi 2 - Part 8'),
    ('CBE', 'Sumathi 2 - Part 9'),
    ('CBE', 'Yashoda 1'),
    ('CBE', 'Yashoda 10'),
    ('CBE', 'Yashoda 2'),
    ('CBE', 'Yashoda 3'),
    ('CBE', 'Yashoda 4'),
    ('CBE', 'Yashoda 5'),
    ('CBE', 'Yashoda 6'),
    ('CBE', 'Yashoda 7'),
    ('CBE', 'Yashoda 8'),
    ('CBE', 'Yashoda 9'),
    ('CPT', 'Castro 1'),
    ('CPT', 'Castro 2'),
    ('CPT', 'Gandhi 1'),
    ('CPT', 'Gandhi 2'),
    ('CPT', 'Gandhi 3'),
    ('CPT', 'Godel 1 - Part 1'),
    ('CPT', 'Godel 1 - Part 10'),
    ('CPT', 'Godel 1 - Part 2'),
    ('CPT', 'Godel 1 - Part 3'),
    ('CPT', 'Godel 1 - Part 4'),
    ('CPT', 'Godel 1 - Part 5'),
    ('CPT', 'Godel 1 - Part 6'),
    ('CPT', 'Godel 1 - Part 7'),
    ('CPT', 'Godel 1 - Part 8'),
    ('CPT', 'Godel 1 - Part 9'),
    ('CPT', 'Godel 2 - Part 1'),
    ('CPT', 'Godel 2 - Part 10'),
    ('CPT', 'Godel 2 - Part 2'),
    ('CPT', 'Godel 2 - Part 3'),
    ('CPT', 'Godel 2 - Part 4'),
    ('CPT', 'Godel 2 - Part 5'),
    ('CPT', 'Godel 2 - Part 6'),
    ('CPT', 'Godel 2 - Part 7'),
    ('CPT', 'Godel 2 - Part 8'),
    ('CPT', 'Godel 2 - Part 9'),
    ('CPT', 'Ho Chi Minh 1'),
    ('CPT', 'Ho Chi Minh 2'),
    ('CPT', 'Mandela 1 - Part 1'),
    ('CPT', 'Mandela 1 - Part 10'),
    ('CPT', 'Mandela 1 - Part 2'),
    ('CPT', 'Mandela 1 - Part 3'),
    ('CPT', 'Mandela 1 - Part 4'),
    ('CPT', 'Mandela 1 - Part 5'),
    ('CPT', 'Mandela 1 - Part 6'),
    ('CPT', 'Mandela 1 - Part 7'),
    ('CPT', 'Mandela 1 - Part 8'),
    ('CPT', 'Mandela 1 - Part 9'),
    ('CPT', 'Mandela 2 - Part 1'),
    ('CPT', 'Mandela 2 - Part 10'),
    ('CPT', 'Mandela 2 - Part 2'),
    ('CPT', 'Mandela 2 - Part 3'),
    ('CPT', 'Mandela 2 - Part 4'),
    ('CPT', 'Mandela 2 - Part 5'),
    ('CPT', 'Mandela 2 - Part 6'),
    ('CPT', 'Mandela 2 - Part 7'),
    ('CPT', 'Mandela 2 - Part 8'),
    ('CPT', 'Mandela 2 - Part 9'),
    ('CPT', 'Old Yashoda 1'),
    ('CPT', 'Old Yashoda 2'),
    ('CPT', 'Old Yashoda 3'),
    ('CPT', 'Old Yashoda 4'),
    ('CPT', 'Old Yashoda 5'),
    ('CPT', 'Sumathi 1 - Part 1'),
    ('CPT', 'Sumathi 1 - Part 10'),
    ('CPT', 'Sumathi 1 - Part 2'),
    ('CPT', 'Sumathi 1 - Part 3'),
    ('CPT', 'Sumathi 1 - Part 4'),
    ('CPT', 'Sumathi 1 - Part 5'),
    ('CPT', 'Sumathi 1 - Part 6'),
    ('CPT', 'Sumathi 1 - Part 7'),
    ('CPT', 'Sumathi 1 - Part 8'),
    ('CPT', 'Sumathi 1 - Part 9'),
    ('CPT', 'Sumathi 2 - Part 1'),
    ('CPT', 'Sumathi 2 - Part 10'),
    ('CPT', 'Sumathi 2 - Part 2'),
    ('CPT', 'Sumathi 2 - Part 3'),
    ('CPT', 'Sumathi 2 - Part 4'),
    ('CPT', 'Sumathi 2 - Part 5'),
    ('CPT', 'Sumathi 2 - Part 6'),
    ('CPT', 'Sumathi 2 - Part 7'),
    ('CPT', 'Sumathi 2 - Part 8'),
    ('CPT', 'Sumathi 2 - Part 9'),
    ('CPT', 'Yashoda 1'),
    ('CPT', 'Yashoda 2'),
    ('CPT', 'Yashoda 3'),
    ('CPT', 'Yashoda 4')
), normalized_sheds AS (
  SELECT DISTINCT
    farm_code,
    shed_name,
    upper(farm_code || '_SHED_' || regexp_replace(regexp_replace(trim(shed_name), '[^A-Za-z0-9]+', '_', 'g'), '(^_|_$)', '', 'g')) AS location_code
  FROM bq_sheds
)
INSERT INTO location_aliases (tenant_id, alias_code, canonical_location_id, source_context, notes, created_at)
SELECT
  '00000000-0000-4000-8000-000000000001'::uuid,
  n.farm_code || ':' || n.shed_name,
  l.location_id,
  'legacy_bq_dashboard_shed',
  'Legacy BigQuery dashboard shed label; current-data source of truth for Phase 1 location reconciliation.',
  now()
FROM normalized_sheds n
JOIN locations l
  ON l.tenant_id = '00000000-0000-4000-8000-000000000001'::uuid
 AND l.location_code = n.location_code
ON CONFLICT (tenant_id, alias_code, source_context) DO UPDATE SET
  canonical_location_id = EXCLUDED.canonical_location_id,
  notes = EXCLUDED.notes;

-- +goose Down
WITH bq_sheds(farm_code, shed_name) AS (
  VALUES
    ('CBE', 'Castro 1'),
    ('CBE', 'Castro 2'),
    ('CBE', 'Castro 3'),
    ('CBE', 'Gandhi 1'),
    ('CBE', 'Gandhi 1 - Part 1'),
    ('CBE', 'Gandhi 1 - Part 2'),
    ('CBE', 'Gandhi 2'),
    ('CBE', 'Gandhi 3'),
    ('CBE', 'Godel 1 - Part 1'),
    ('CBE', 'Godel 1 - Part 10'),
    ('CBE', 'Godel 1 - Part 2'),
    ('CBE', 'Godel 1 - Part 3'),
    ('CBE', 'Godel 1 - Part 4'),
    ('CBE', 'Godel 1 - Part 5'),
    ('CBE', 'Godel 1 - Part 6'),
    ('CBE', 'Godel 1 - Part 7'),
    ('CBE', 'Godel 1 - Part 8'),
    ('CBE', 'Godel 1 - Part 9'),
    ('CBE', 'Godel 2 - Part 1'),
    ('CBE', 'Godel 2 - Part 10'),
    ('CBE', 'Godel 2 - Part 2'),
    ('CBE', 'Godel 2 - Part 3'),
    ('CBE', 'Godel 2 - Part 4'),
    ('CBE', 'Godel 2 - Part 5'),
    ('CBE', 'Godel 2 - Part 6'),
    ('CBE', 'Godel 2 - Part 7'),
    ('CBE', 'Godel 2 - Part 8'),
    ('CBE', 'Godel 2 - Part 9'),
    ('CBE', 'Ho Chi Minh 1'),
    ('CBE', 'Ho Chi Minh 2'),
    ('CBE', 'Mandela 1 - Part 1'),
    ('CBE', 'Mandela 1 - Part 2'),
    ('CBE', 'Mandela 1 - Part 3'),
    ('CBE', 'Mandela 1 - Part 4'),
    ('CBE', 'Mandela 1 - Part 5'),
    ('CBE', 'Mandela 1 - Part 6'),
    ('CBE', 'Mandela 1 - Part 7'),
    ('CBE', 'Mandela 2 - Part 1'),
    ('CBE', 'Mandela 2 - Part 2'),
    ('CBE', 'Mandela 2 - Part 3'),
    ('CBE', 'Mandela 2 - Part 4'),
    ('CBE', 'Mandela 2 - Part 5'),
    ('CBE', 'Mandela 2 - Part 6'),
    ('CBE', 'Mandela 2 - Part 7'),
    ('CBE', 'Mandela 2 - Part 8'),
    ('CBE', 'Q1'),
    ('CBE', 'Q2'),
    ('CBE', 'Q3'),
    ('CBE', 'Sumathi 1 - Part 1'),
    ('CBE', 'Sumathi 1 - Part 10'),
    ('CBE', 'Sumathi 1 - Part 2'),
    ('CBE', 'Sumathi 1 - Part 3'),
    ('CBE', 'Sumathi 1 - Part 4'),
    ('CBE', 'Sumathi 1 - Part 5'),
    ('CBE', 'Sumathi 1 - Part 6'),
    ('CBE', 'Sumathi 1 - Part 7'),
    ('CBE', 'Sumathi 1 - Part 8'),
    ('CBE', 'Sumathi 1 - Part 9'),
    ('CBE', 'Sumathi 2 - Part 1'),
    ('CBE', 'Sumathi 2 - Part 10'),
    ('CBE', 'Sumathi 2 - Part 2'),
    ('CBE', 'Sumathi 2 - Part 3'),
    ('CBE', 'Sumathi 2 - Part 4'),
    ('CBE', 'Sumathi 2 - Part 5'),
    ('CBE', 'Sumathi 2 - Part 6'),
    ('CBE', 'Sumathi 2 - Part 7'),
    ('CBE', 'Sumathi 2 - Part 8'),
    ('CBE', 'Sumathi 2 - Part 9'),
    ('CBE', 'Yashoda 1'),
    ('CBE', 'Yashoda 10'),
    ('CBE', 'Yashoda 2'),
    ('CBE', 'Yashoda 3'),
    ('CBE', 'Yashoda 4'),
    ('CBE', 'Yashoda 5'),
    ('CBE', 'Yashoda 6'),
    ('CBE', 'Yashoda 7'),
    ('CBE', 'Yashoda 8'),
    ('CBE', 'Yashoda 9'),
    ('CPT', 'Castro 1'),
    ('CPT', 'Castro 2'),
    ('CPT', 'Gandhi 1'),
    ('CPT', 'Gandhi 2'),
    ('CPT', 'Gandhi 3'),
    ('CPT', 'Godel 1 - Part 1'),
    ('CPT', 'Godel 1 - Part 10'),
    ('CPT', 'Godel 1 - Part 2'),
    ('CPT', 'Godel 1 - Part 3'),
    ('CPT', 'Godel 1 - Part 4'),
    ('CPT', 'Godel 1 - Part 5'),
    ('CPT', 'Godel 1 - Part 6'),
    ('CPT', 'Godel 1 - Part 7'),
    ('CPT', 'Godel 1 - Part 8'),
    ('CPT', 'Godel 1 - Part 9'),
    ('CPT', 'Godel 2 - Part 1'),
    ('CPT', 'Godel 2 - Part 10'),
    ('CPT', 'Godel 2 - Part 2'),
    ('CPT', 'Godel 2 - Part 3'),
    ('CPT', 'Godel 2 - Part 4'),
    ('CPT', 'Godel 2 - Part 5'),
    ('CPT', 'Godel 2 - Part 6'),
    ('CPT', 'Godel 2 - Part 7'),
    ('CPT', 'Godel 2 - Part 8'),
    ('CPT', 'Godel 2 - Part 9'),
    ('CPT', 'Ho Chi Minh 1'),
    ('CPT', 'Ho Chi Minh 2'),
    ('CPT', 'Mandela 1 - Part 1'),
    ('CPT', 'Mandela 1 - Part 10'),
    ('CPT', 'Mandela 1 - Part 2'),
    ('CPT', 'Mandela 1 - Part 3'),
    ('CPT', 'Mandela 1 - Part 4'),
    ('CPT', 'Mandela 1 - Part 5'),
    ('CPT', 'Mandela 1 - Part 6'),
    ('CPT', 'Mandela 1 - Part 7'),
    ('CPT', 'Mandela 1 - Part 8'),
    ('CPT', 'Mandela 1 - Part 9'),
    ('CPT', 'Mandela 2 - Part 1'),
    ('CPT', 'Mandela 2 - Part 10'),
    ('CPT', 'Mandela 2 - Part 2'),
    ('CPT', 'Mandela 2 - Part 3'),
    ('CPT', 'Mandela 2 - Part 4'),
    ('CPT', 'Mandela 2 - Part 5'),
    ('CPT', 'Mandela 2 - Part 6'),
    ('CPT', 'Mandela 2 - Part 7'),
    ('CPT', 'Mandela 2 - Part 8'),
    ('CPT', 'Mandela 2 - Part 9'),
    ('CPT', 'Old Yashoda 1'),
    ('CPT', 'Old Yashoda 2'),
    ('CPT', 'Old Yashoda 3'),
    ('CPT', 'Old Yashoda 4'),
    ('CPT', 'Old Yashoda 5'),
    ('CPT', 'Sumathi 1 - Part 1'),
    ('CPT', 'Sumathi 1 - Part 10'),
    ('CPT', 'Sumathi 1 - Part 2'),
    ('CPT', 'Sumathi 1 - Part 3'),
    ('CPT', 'Sumathi 1 - Part 4'),
    ('CPT', 'Sumathi 1 - Part 5'),
    ('CPT', 'Sumathi 1 - Part 6'),
    ('CPT', 'Sumathi 1 - Part 7'),
    ('CPT', 'Sumathi 1 - Part 8'),
    ('CPT', 'Sumathi 1 - Part 9'),
    ('CPT', 'Sumathi 2 - Part 1'),
    ('CPT', 'Sumathi 2 - Part 10'),
    ('CPT', 'Sumathi 2 - Part 2'),
    ('CPT', 'Sumathi 2 - Part 3'),
    ('CPT', 'Sumathi 2 - Part 4'),
    ('CPT', 'Sumathi 2 - Part 5'),
    ('CPT', 'Sumathi 2 - Part 6'),
    ('CPT', 'Sumathi 2 - Part 7'),
    ('CPT', 'Sumathi 2 - Part 8'),
    ('CPT', 'Sumathi 2 - Part 9'),
    ('CPT', 'Yashoda 1'),
    ('CPT', 'Yashoda 2'),
    ('CPT', 'Yashoda 3'),
    ('CPT', 'Yashoda 4')
), normalized_sheds AS (
  SELECT DISTINCT
    farm_code,
    shed_name,
    upper(farm_code || '_SHED_' || regexp_replace(regexp_replace(trim(shed_name), '[^A-Za-z0-9]+', '_', 'g'), '(^_|_$)', '', 'g')) AS location_code
  FROM bq_sheds
)
DELETE FROM location_aliases la
USING normalized_sheds n
WHERE la.tenant_id = '00000000-0000-4000-8000-000000000001'::uuid
  AND la.source_context = 'legacy_bq_dashboard_shed'
  AND la.alias_code = n.farm_code || ':' || n.shed_name;

WITH bq_sheds(farm_code, shed_name) AS (
  VALUES
    ('CBE', 'Castro 1'),
    ('CBE', 'Castro 2'),
    ('CBE', 'Castro 3'),
    ('CBE', 'Gandhi 1'),
    ('CBE', 'Gandhi 1 - Part 1'),
    ('CBE', 'Gandhi 1 - Part 2'),
    ('CBE', 'Gandhi 2'),
    ('CBE', 'Gandhi 3'),
    ('CBE', 'Godel 1 - Part 1'),
    ('CBE', 'Godel 1 - Part 10'),
    ('CBE', 'Godel 1 - Part 2'),
    ('CBE', 'Godel 1 - Part 3'),
    ('CBE', 'Godel 1 - Part 4'),
    ('CBE', 'Godel 1 - Part 5'),
    ('CBE', 'Godel 1 - Part 6'),
    ('CBE', 'Godel 1 - Part 7'),
    ('CBE', 'Godel 1 - Part 8'),
    ('CBE', 'Godel 1 - Part 9'),
    ('CBE', 'Godel 2 - Part 1'),
    ('CBE', 'Godel 2 - Part 10'),
    ('CBE', 'Godel 2 - Part 2'),
    ('CBE', 'Godel 2 - Part 3'),
    ('CBE', 'Godel 2 - Part 4'),
    ('CBE', 'Godel 2 - Part 5'),
    ('CBE', 'Godel 2 - Part 6'),
    ('CBE', 'Godel 2 - Part 7'),
    ('CBE', 'Godel 2 - Part 8'),
    ('CBE', 'Godel 2 - Part 9'),
    ('CBE', 'Ho Chi Minh 1'),
    ('CBE', 'Ho Chi Minh 2'),
    ('CBE', 'Mandela 1 - Part 1'),
    ('CBE', 'Mandela 1 - Part 2'),
    ('CBE', 'Mandela 1 - Part 3'),
    ('CBE', 'Mandela 1 - Part 4'),
    ('CBE', 'Mandela 1 - Part 5'),
    ('CBE', 'Mandela 1 - Part 6'),
    ('CBE', 'Mandela 1 - Part 7'),
    ('CBE', 'Mandela 2 - Part 1'),
    ('CBE', 'Mandela 2 - Part 2'),
    ('CBE', 'Mandela 2 - Part 3'),
    ('CBE', 'Mandela 2 - Part 4'),
    ('CBE', 'Mandela 2 - Part 5'),
    ('CBE', 'Mandela 2 - Part 6'),
    ('CBE', 'Mandela 2 - Part 7'),
    ('CBE', 'Mandela 2 - Part 8'),
    ('CBE', 'Q1'),
    ('CBE', 'Q2'),
    ('CBE', 'Q3'),
    ('CBE', 'Sumathi 1 - Part 1'),
    ('CBE', 'Sumathi 1 - Part 10'),
    ('CBE', 'Sumathi 1 - Part 2'),
    ('CBE', 'Sumathi 1 - Part 3'),
    ('CBE', 'Sumathi 1 - Part 4'),
    ('CBE', 'Sumathi 1 - Part 5'),
    ('CBE', 'Sumathi 1 - Part 6'),
    ('CBE', 'Sumathi 1 - Part 7'),
    ('CBE', 'Sumathi 1 - Part 8'),
    ('CBE', 'Sumathi 1 - Part 9'),
    ('CBE', 'Sumathi 2 - Part 1'),
    ('CBE', 'Sumathi 2 - Part 10'),
    ('CBE', 'Sumathi 2 - Part 2'),
    ('CBE', 'Sumathi 2 - Part 3'),
    ('CBE', 'Sumathi 2 - Part 4'),
    ('CBE', 'Sumathi 2 - Part 5'),
    ('CBE', 'Sumathi 2 - Part 6'),
    ('CBE', 'Sumathi 2 - Part 7'),
    ('CBE', 'Sumathi 2 - Part 8'),
    ('CBE', 'Sumathi 2 - Part 9'),
    ('CBE', 'Yashoda 1'),
    ('CBE', 'Yashoda 10'),
    ('CBE', 'Yashoda 2'),
    ('CBE', 'Yashoda 3'),
    ('CBE', 'Yashoda 4'),
    ('CBE', 'Yashoda 5'),
    ('CBE', 'Yashoda 6'),
    ('CBE', 'Yashoda 7'),
    ('CBE', 'Yashoda 8'),
    ('CBE', 'Yashoda 9'),
    ('CPT', 'Castro 1'),
    ('CPT', 'Castro 2'),
    ('CPT', 'Gandhi 1'),
    ('CPT', 'Gandhi 2'),
    ('CPT', 'Gandhi 3'),
    ('CPT', 'Godel 1 - Part 1'),
    ('CPT', 'Godel 1 - Part 10'),
    ('CPT', 'Godel 1 - Part 2'),
    ('CPT', 'Godel 1 - Part 3'),
    ('CPT', 'Godel 1 - Part 4'),
    ('CPT', 'Godel 1 - Part 5'),
    ('CPT', 'Godel 1 - Part 6'),
    ('CPT', 'Godel 1 - Part 7'),
    ('CPT', 'Godel 1 - Part 8'),
    ('CPT', 'Godel 1 - Part 9'),
    ('CPT', 'Godel 2 - Part 1'),
    ('CPT', 'Godel 2 - Part 10'),
    ('CPT', 'Godel 2 - Part 2'),
    ('CPT', 'Godel 2 - Part 3'),
    ('CPT', 'Godel 2 - Part 4'),
    ('CPT', 'Godel 2 - Part 5'),
    ('CPT', 'Godel 2 - Part 6'),
    ('CPT', 'Godel 2 - Part 7'),
    ('CPT', 'Godel 2 - Part 8'),
    ('CPT', 'Godel 2 - Part 9'),
    ('CPT', 'Ho Chi Minh 1'),
    ('CPT', 'Ho Chi Minh 2'),
    ('CPT', 'Mandela 1 - Part 1'),
    ('CPT', 'Mandela 1 - Part 10'),
    ('CPT', 'Mandela 1 - Part 2'),
    ('CPT', 'Mandela 1 - Part 3'),
    ('CPT', 'Mandela 1 - Part 4'),
    ('CPT', 'Mandela 1 - Part 5'),
    ('CPT', 'Mandela 1 - Part 6'),
    ('CPT', 'Mandela 1 - Part 7'),
    ('CPT', 'Mandela 1 - Part 8'),
    ('CPT', 'Mandela 1 - Part 9'),
    ('CPT', 'Mandela 2 - Part 1'),
    ('CPT', 'Mandela 2 - Part 10'),
    ('CPT', 'Mandela 2 - Part 2'),
    ('CPT', 'Mandela 2 - Part 3'),
    ('CPT', 'Mandela 2 - Part 4'),
    ('CPT', 'Mandela 2 - Part 5'),
    ('CPT', 'Mandela 2 - Part 6'),
    ('CPT', 'Mandela 2 - Part 7'),
    ('CPT', 'Mandela 2 - Part 8'),
    ('CPT', 'Mandela 2 - Part 9'),
    ('CPT', 'Old Yashoda 1'),
    ('CPT', 'Old Yashoda 2'),
    ('CPT', 'Old Yashoda 3'),
    ('CPT', 'Old Yashoda 4'),
    ('CPT', 'Old Yashoda 5'),
    ('CPT', 'Sumathi 1 - Part 1'),
    ('CPT', 'Sumathi 1 - Part 10'),
    ('CPT', 'Sumathi 1 - Part 2'),
    ('CPT', 'Sumathi 1 - Part 3'),
    ('CPT', 'Sumathi 1 - Part 4'),
    ('CPT', 'Sumathi 1 - Part 5'),
    ('CPT', 'Sumathi 1 - Part 6'),
    ('CPT', 'Sumathi 1 - Part 7'),
    ('CPT', 'Sumathi 1 - Part 8'),
    ('CPT', 'Sumathi 1 - Part 9'),
    ('CPT', 'Sumathi 2 - Part 1'),
    ('CPT', 'Sumathi 2 - Part 10'),
    ('CPT', 'Sumathi 2 - Part 2'),
    ('CPT', 'Sumathi 2 - Part 3'),
    ('CPT', 'Sumathi 2 - Part 4'),
    ('CPT', 'Sumathi 2 - Part 5'),
    ('CPT', 'Sumathi 2 - Part 6'),
    ('CPT', 'Sumathi 2 - Part 7'),
    ('CPT', 'Sumathi 2 - Part 8'),
    ('CPT', 'Sumathi 2 - Part 9'),
    ('CPT', 'Yashoda 1'),
    ('CPT', 'Yashoda 2'),
    ('CPT', 'Yashoda 3'),
    ('CPT', 'Yashoda 4')
), normalized_sheds AS (
  SELECT DISTINCT
    upper(farm_code || '_SHED_' || regexp_replace(regexp_replace(trim(shed_name), '[^A-Za-z0-9]+', '_', 'g'), '(^_|_$)', '', 'g')) AS location_code
  FROM bq_sheds
)
DELETE FROM locations l
USING normalized_sheds n
WHERE l.tenant_id = '00000000-0000-4000-8000-000000000001'::uuid
  AND l.location_type = 'shed'
  AND l.location_code = n.location_code
  AND NOT EXISTS (
    SELECT 1
    FROM goats g
    WHERE g.tenant_id = l.tenant_id
      AND (
        g.park_id = l.location_id
        OR g.shed_id = l.location_id
        OR g.current_location_id = l.location_id
      )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM goat_identity_counters c
    WHERE c.tenant_id = l.tenant_id
      AND (
        c.farm_id = l.location_id
        OR c.park_id = l.location_id
        OR c.shed_id = l.location_id
        OR c.cohort_id = l.location_id
      )
  );
