-- +goose Up
-- VACC-REV-11 P1: Migration 000195 was originally a NON-RESUMABLE, UNSAFE migration
-- combining ADD+VALIDATE+DROP+RENAME without bounded lock_timeout. It has been superseded
-- by three separate, lock-safe, resumable migrations:
-- - 000199: ADD CONSTRAINT with bounded lock_timeout and idempotent guards
-- - 000200: VALIDATE CONSTRAINT (idempotent scan under concurrent access)
-- - 000201: SWAP (DROP old, RENAME new) with idempotent guards
--
-- This file is now a no-op to preserve checksum history. The identity_goat decision type
-- is added to identity_decisions.decision_type CHECK via migrations 000199-000201 instead.
-- No action required in this file; all work moved to the three-phase split migrations.

-- +goose Down
-- No-op, same as Up.
