import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { scopeHref, type Scope } from "@/lib/scope";
import { copy, type AdminUiPageContract } from "@/lib/admin-ui-contract";

// Header actions must be real. A vaccination drive is generated by published
// protocol config and SOP execution, not hand-created from this page.
export function VaccinationHeaderActions({ scope, pageContract }: { scope: Scope; pageContract: AdminUiPageContract }) {
  return (
    <Link href={scopeHref("/config", scope, {}, { category: "vaccination" })} className="btn p">
      {copy(pageContract, "action.open_protocol_rules")}
      <ArrowUpRight className="ic" style={{ width: 14 }} aria-hidden="true" />
    </Link>
  );
}
