package postgres

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/vgoats/goatos/backend/internal/feeddirection/domain"
	"github.com/vgoats/goatos/backend/internal/feeddirection/ports"
	"github.com/vgoats/goatos/backend/internal/platform/biztime"
	"github.com/vgoats/goatos/backend/internal/platform/pgtest"
)

// Proofs against the REAL schema (migration 000003).
//
// The generation rules themselves are proved without a database in ../../domain -- they are a pure
// function and should not need Docker. What only a database can prove is the boundary between Go
// and SQL, and there are three things there that would silently produce a WRONG FEED SHEET rather
// than an error:
//
//	KEY PARITY        -- the generator joins live free-text values to authored labels IN MEMORY,
//	                     using NormalizeConfigKey. The stored *_key columns are GENERATED by the
//	                     database's feed_config_norm(). If the two ever disagree by one character,
//	                     a perfectly well-authored shed silently BLOCKS. Nothing but a real database
//	                     can compare them.
//	EFFECTIVE DATING  -- the snapshot must load the rates in force ON THE TARGET DAY, not the
//	                     currently-open row. A fake would happily return whatever it was stocked
//	                     with and "prove" a back-dated regeneration that never happened.
//	ABSENCE           -- a cell with no row must be ABSENT from the map, never a zero. The query has
//	                     no COALESCE and no LEFT JOIN, and this is where that is verified.

const (
	// A dedicated uuid prefix (fd...) rather than the conventional 3001/4001 fixture ids. Those
	// collide with locations the baseline migration already seeds, which silently mixes 8 foreign
	// sheds into this park and makes the shed-page assertions meaningless.
	fdTenant = "fd000000-0000-4000-8000-000000000001"
	fdPark   = "fd000000-0000-4000-8000-000000003001"
	fdShedA  = "fd000000-0000-4000-8000-000000004001"
	fdShedB  = "fd000000-0000-4000-8000-000000004002"
	// A retired shed, to prove the shed page lists active sheds only.
	fdShedRetired = "fd000000-0000-4000-8000-000000004003"
	// A second park, to prove park scoping.
	fdOtherPark = "fd000000-0000-4000-8000-000000003002"
)

func setupFeedDirectionDB(t *testing.T, ctx context.Context) (*Repository, *pgxpool.Pool) {
	t.Helper()
	pgtest.SkipIfNoDocker(t)
	pool := pgtest.StartPostgres(t, ctx)
	seedFeedDirectionScope(t, ctx, pool)
	return NewRepository(pool, 10*time.Second), pool
}

func seedFeedDirectionScope(t *testing.T, ctx context.Context, pool *pgxpool.Pool) {
	t.Helper()
	exec := func(sql string, args ...any) {
		t.Helper()
		if _, err := pool.Exec(ctx, sql, args...); err != nil {
			t.Fatalf("seed: %v\nsql: %s", err, sql)
		}
	}

	exec(`INSERT INTO tenants (tenant_id, name, status) VALUES ($1::uuid, 'Mesha Test', 'active')
ON CONFLICT (tenant_id) DO NOTHING`, fdTenant)

	exec(`INSERT INTO locations (location_id, tenant_id, location_type, location_code, name, status)
VALUES ($2::uuid, $1::uuid, 'park', 'CPT', 'CPT', 'active'),
       ($3::uuid, $1::uuid, 'park', 'CBE', 'CBE', 'active')
ON CONFLICT (location_id) DO NOTHING`, fdTenant, fdPark, fdOtherPark)

	exec(`INSERT INTO locations (location_id, tenant_id, location_type, location_code, name, status, parent_location_id, display_order)
VALUES ($3::uuid, $1::uuid, 'shed', 'S-A', 'Shed A', 'active',   $2::uuid, 1),
       ($4::uuid, $1::uuid, 'shed', 'S-B', 'Shed B', 'active',   $2::uuid, 2),
       ($5::uuid, $1::uuid, 'shed', 'S-R', 'Shed R', 'inactive', $2::uuid, 3)
ON CONFLICT (location_id) DO NOTHING`, fdTenant, fdPark, fdShedA, fdShedB, fdShedRetired)

	// The real tag vocabulary, including the cosmetic variants that make key parity load-bearing.
	exec(`INSERT INTO feed_shed_tags (tenant_id, shed_tag_label, applies_to, display_order, status)
VALUES ($1::uuid, 'Non-Pregnant', 'adult', 1, 'active'),
       ($1::uuid, 'Mother',       'adult', 2, 'active'),
       ($1::uuid, 'ICU-Kid',      'kid',   3, 'active'),
       ($1::uuid, 'F2-Male',      'kid',   4, 'active'),
       ($1::uuid, 'K0',           'kid',   5, 'active'),
       ($1::uuid, 'Retired Tag',  'adult', 6, 'retired')`, fdTenant)

	// The real Beetal + Sirohi merge.
	exec(`INSERT INTO feed_ration_groups (tenant_id, breed_label, ration_group_label)
VALUES ($1::uuid, 'Beetal',          'Beetal/Sirohi'),
       ($1::uuid, 'Sirohi',          'Beetal/Sirohi'),
       ($1::uuid, 'Anantapur Sheep', 'Anantapur Sheep')`, fdTenant)

	exec(`INSERT INTO feed_item_catalog (tenant_id, feed_item_label, display_order, status)
VALUES ($1::uuid, 'Concentrate', 1, 'active'),
       ($1::uuid, 'Hybrid',      2, 'active'),
       ($1::uuid, 'Retired Item',         3, 'retired')`, fdTenant)

	exec(`INSERT INTO feed_session_templates (tenant_id, park_id, session_no, session_label, split_fraction, display_order, status)
VALUES ($1::uuid, $2::uuid, 1, 'Morning', 0.5, 1, 'active'),
       ($1::uuid, $2::uuid, 2, 'Evening', 0.5, 2, 'active'),
       ($1::uuid, $2::uuid, 3, 'Retired', 0.5, 3, 'retired')`, fdTenant, fdPark)

	// The workbook's `Template` tab: what each session actually consists of, in packing order.
	// Session 1 declares two slots, session 2 declares one, and one slot is retired -- enough shape
	// to prove ordering, per-session scoping, and status filtering in one fixture.
	exec(`INSERT INTO feed_session_template_items (tenant_id, park_id, session_no, slot_no, feed_item_label, status)
VALUES ($1::uuid, $2::uuid, 1, 1, 'Hybrid',       'active'),
       ($1::uuid, $2::uuid, 1, 2, 'Concentrate',  'active'),
       ($1::uuid, $2::uuid, 1, 3, 'Retired Item', 'retired'),
       ($1::uuid, $2::uuid, 2, 1, 'Concentrate',  'active')`, fdTenant, fdPark)
}

// ---------------------------------------------------------------------------
// Key parity: the Go normalizer vs the database's feed_config_norm
// ---------------------------------------------------------------------------

// The single most valuable proof in this file.
//
// The generator resolves rations by joining live free-text values to authored labels IN MEMORY,
// so the Go NormalizeConfigKey must be byte-identical to the SQL feed_config_norm() that generated
// the stored keys. A one-character divergence does not raise an error anywhere: it makes a lookup
// miss, which makes a shed BLOCK, which is a shed that does not get fed over a hyphen.
func TestGoNormalizerMatchesDatabaseFeedConfigNormExactly(t *testing.T) {
	ctx := context.Background()
	_, pool := setupFeedDirectionDB(t, ctx)

	labels := []string{
		// The live cosmetic variants from the source sheet.
		"ICU-Kid", "ICU- kid", "ICU-  KID", "F2-Male", "F2- Male",
		"Non-Pregnant", "Milking Warmup", "Quarantine kids", "Mother", "K0",
		// The merged ration group, whose slash must survive normalization.
		"Beetal/Sirohi", "Anantapur Sheep",
		// The feed catalog.
		"Concentrate", "Baking Soda", "Dry Masoor Bhusa",
		// Adversarial separator/padding shapes.
		"  padded  ", "A___B---C   D", "-leading-", "trailing-", "a-_ b",
	}

	for _, label := range labels {
		var sqlKey string
		if err := pool.QueryRow(ctx, `SELECT feed_config_norm($1)`, label).Scan(&sqlKey); err != nil {
			t.Fatalf("feed_config_norm(%q): %v", label, err)
		}
		if goKey := domain.NormalizeConfigKey(label); goKey != sqlKey {
			t.Fatalf("normalizer divergence for %q: Go=%q SQL=%q -- an in-memory join would miss and block a well-authored shed",
				label, goKey, sqlKey)
		}
	}
}

// The stored *_key columns are GENERATED by the database. The snapshot builds its map keys from
// them via RateKey, and the generator looks up with raw live labels. This proves the round trip.
func TestStoredGeneratedKeysResolveThroughTheGoLookupKey(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	if _, err := pool.Exec(ctx, `
INSERT INTO feed_ration_rates (tenant_id, park_id, ration_group_label, shed_tag_label, feed_item_label, grams_per_head, valid_from)
VALUES ($1::uuid, $2::uuid, 'Kid', 'ICU-Kid', 'Concentrate', 50.000, DATE '2026-01-01')`,
		fdTenant, fdPark); err != nil {
		t.Fatalf("seed rate: %v", err)
	}

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2026, 7, 19))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}

	// Looked up with the RAW LIVE spelling variant, not the authored one. This is exactly what the
	// generator does after resolving the tag.
	rate, ok := snapshot.RatesByKey[domain.RateKey("Kid", "ICU- kid", "Concentrate")]
	if !ok {
		t.Fatal("stored rate did not resolve through a raw live label variant")
	}
	if rate.GramsPerHead != "50.000" {
		t.Fatalf("grams_per_head = %q, want \"50.000\" (exact decimal string, never a float)", rate.GramsPerHead)
	}
}

// ---------------------------------------------------------------------------
// Absence is not zero
// ---------------------------------------------------------------------------

// The query has no COALESCE and no LEFT JOIN, and this is the proof: an unauthored cell is simply
// not in the map. The generator turns that absence into a BLOCKED quantity, which is what stops a
// shed from silently being fed nothing.
func TestUnauthoredCellIsAbsentFromTheSnapshotRatherThanZero(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	// Concentrate is authored (as an explicit ZERO); Hybrid is not authored at all.
	if _, err := pool.Exec(ctx, `
INSERT INTO feed_ration_rates (tenant_id, park_id, ration_group_label, shed_tag_label, feed_item_label, grams_per_head, valid_from)
VALUES ($1::uuid, $2::uuid, 'Kid', 'K0', 'Concentrate', 0.000, DATE '2026-01-01')`,
		fdTenant, fdPark); err != nil {
		t.Fatalf("seed rate: %v", err)
	}

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2026, 7, 19))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}

	authoredZero, ok := snapshot.RatesByKey[domain.RateKey("Kid", "K0", "Concentrate")]
	if !ok {
		t.Fatal("an authored zero is a real rate and must be PRESENT in the snapshot")
	}
	if authoredZero.GramsPerHead != "0.000" {
		t.Fatalf("authored zero = %q, want \"0.000\"", authoredZero.GramsPerHead)
	}

	if _, ok := snapshot.RatesByKey[domain.RateKey("Kid", "K0", "Hybrid")]; ok {
		t.Fatal("an unauthored cell appeared in the snapshot; absence is the ONLY encoding of 'not configured'")
	}
}

// ---------------------------------------------------------------------------
// Effective dating
// ---------------------------------------------------------------------------

// The snapshot must load what was in force ON THE TARGET DAY. Loading the currently-open row
// instead would reprint history with today's numbers.
func TestSnapshotLoadsTheRateInForceOnTheTargetDayNotTheOpenRow(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	// A superseded window (closed on 2026-07-01) and its successor (still open).
	if _, err := pool.Exec(ctx, `
INSERT INTO feed_ration_rates (tenant_id, park_id, ration_group_label, shed_tag_label, feed_item_label, grams_per_head, valid_from, valid_to)
VALUES ($1::uuid, $2::uuid, 'Beetal/Sirohi', 'Non-Pregnant', 'Concentrate', 150.000, DATE '2026-01-01', DATE '2026-07-01'),
       ($1::uuid, $2::uuid, 'Beetal/Sirohi', 'Non-Pregnant', 'Concentrate', 200.000, DATE '2026-07-01', NULL)`,
		fdTenant, fdPark); err != nil {
		t.Fatalf("seed rates: %v", err)
	}

	key := domain.RateKey("Beetal/Sirohi", "Non-Pregnant", "Concentrate")

	cases := []struct {
		name string
		day  time.Time
		want string
	}{
		{name: "today takes the open row", day: businessDay(2026, 7, 19), want: "200.000"},
		// The window is [valid_from, valid_to): the successor's first day is the day it takes effect.
		{name: "the changeover day takes the successor", day: businessDay(2026, 7, 1), want: "200.000"},
		{name: "the day before takes the superseded row", day: businessDay(2026, 6, 30), want: "150.000"},
		{name: "a back-dated day reprints the historical rate", day: businessDay(2026, 3, 15), want: "150.000"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, tc.day)
			if err != nil {
				t.Fatalf("LoadConfigSnapshot: %v", err)
			}
			rate, ok := snapshot.RatesByKey[key]
			if !ok {
				t.Fatalf("no rate in force on %s", biztime.BusinessDate(tc.day))
			}
			if rate.GramsPerHead != tc.want {
				t.Fatalf("grams_per_head on %s = %q, want %q",
					biztime.BusinessDate(tc.day), rate.GramsPerHead, tc.want)
			}
		})
	}

	// Before the first window opens there is NO rate -- and that must read as absent (blocking),
	// not as a zero.
	early, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2025, 12, 31))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}
	if _, ok := early.RatesByKey[key]; ok {
		t.Fatal("a rate resolved before its first window opened")
	}
}

// ---------------------------------------------------------------------------
// Scoping
// ---------------------------------------------------------------------------

// Rates are park-scoped because CBE and CPT genuinely differ. A cross-park leak would feed one park
// the other's ration.
func TestRatesAreParkScoped(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	if _, err := pool.Exec(ctx, `
INSERT INTO feed_ration_rates (tenant_id, park_id, ration_group_label, shed_tag_label, feed_item_label, grams_per_head, valid_from)
VALUES ($1::uuid, $2::uuid, 'Beetal/Sirohi', 'Non-Pregnant', 'Concentrate', 999.000, DATE '2026-01-01')`,
		fdTenant, fdOtherPark); err != nil {
		t.Fatalf("seed rate: %v", err)
	}

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2026, 7, 19))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}
	if _, ok := snapshot.RatesByKey[domain.RateKey("Beetal/Sirohi", "Non-Pregnant", "Concentrate")]; ok {
		t.Fatal("another park's rate leaked into this park's snapshot")
	}
}

// Retired vocabulary is excluded. An animal still carrying a retired tag must BLOCK rather than
// resolve through a rule the farm withdrew.
func TestRetiredVocabularyIsExcludedFromTheSnapshot(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2026, 7, 19))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}
	if _, ok := snapshot.ShedTagsByKey["retired_tag"]; ok {
		t.Fatal("a retired shed tag is still in the vocabulary")
	}
	for _, item := range snapshot.FeedItems {
		if item.Label == "Retired Item" {
			t.Fatal("a retired feed item is still in the catalog")
		}
	}
	for _, session := range snapshot.Sessions {
		if session.Label == "Retired" {
			t.Fatal("a retired session template is still in the split")
		}
	}
	// The active vocabulary IS present, and applies_to -- the field the whole kid/adult branch turns
	// on -- survives the round trip.
	if tag, ok := snapshot.ShedTagsByKey["mother"]; !ok || tag.AppliesTo != domain.AppliesToAdult {
		t.Fatalf("Mother tag = %+v, want an adult tag", tag)
	}
	if tag, ok := snapshot.ShedTagsByKey["icu_kid"]; !ok || tag.AppliesTo != domain.AppliesToKid {
		t.Fatalf("ICU-Kid tag = %+v, want a kid tag", tag)
	}
	// The catalog arrives in authored display order, which becomes the column order everywhere.
	if len(snapshot.FeedItems) != 2 || snapshot.FeedItems[0].Label != "Concentrate" {
		t.Fatalf("feed items = %+v, want the active catalog in display order", snapshot.FeedItems)
	}
	// Sessions in display order.
	if len(snapshot.Sessions) != 2 || snapshot.Sessions[0].SessionNo != 1 {
		t.Fatalf("sessions = %+v, want the two active sessions in order", snapshot.Sessions)
	}
}

func TestShedFactorsAndExperimentsLoadForTheParkOnly(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	if _, err := pool.Exec(ctx, `
INSERT INTO feed_shed_factors (tenant_id, park_id, shed_id, feed_item_label, multiplier, valid_from)
VALUES ($1::uuid, $2::uuid, $3::uuid, 'Concentrate', 1.5000, DATE '2026-01-01')`,
		fdTenant, fdPark, fdShedA); err != nil {
		t.Fatalf("seed factor: %v", err)
	}
	if _, err := pool.Exec(ctx, `
INSERT INTO feed_experiment_config (tenant_id, park_id, shed_id, feed_item_label, absolute_kg, head_count, experiment_category, status)
VALUES ($1::uuid, $2::uuid, $3::uuid, 'Concentrate', 12.000, 40, 'Trial A', 'active'),
       ($1::uuid, $2::uuid, $3::uuid, 'Hybrid',      30.000, 40, 'Trial A', 'retired')`,
		fdTenant, fdPark, fdShedB); err != nil {
		t.Fatalf("seed experiment: %v", err)
	}

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, businessDay(2026, 7, 19))
	if err != nil {
		t.Fatalf("LoadConfigSnapshot: %v", err)
	}

	if got, ok := snapshot.ShedFactorsByKey[domain.ShedFactorKey(fdShedA, "Concentrate")]; !ok || got != "1.5000" {
		t.Fatalf("shed factor = %q (present=%v), want \"1.5000\"", got, ok)
	}
	// A shed with no factor row is simply absent; the generator reads that as 1.0, which is safe in
	// a way a missing RATE is not.
	if _, ok := snapshot.ShedFactorsByKey[domain.ShedFactorKey(fdShedB, "Concentrate")]; ok {
		t.Fatal("a shed factor materialized for a shed that has none")
	}

	cells := snapshot.ExperimentByLocation[domain.ExperimentLocationKey(fdShedB, "")]
	if len(cells) != 1 {
		t.Fatalf("experiment cells = %d, want 1 (the retired row is excluded)", len(cells))
	}
	if cells[0].AbsoluteKg != "12.000" {
		t.Fatalf("absolute_kg = %q, want \"12.000\"", cells[0].AbsoluteKg)
	}
	if cells[0].Category != "Trial A" {
		t.Fatalf("category = %q, want \"Trial A\"", cells[0].Category)
	}
	// head_count is not even read: it is informational and must never reach a multiplier.
	if len(snapshot.ExperimentByLocation[domain.ExperimentLocationKey(fdShedA, "")]) != 0 {
		t.Fatal("a non-experiment shed acquired experiment cells")
	}
}

// ---------------------------------------------------------------------------
// Shed scope
// ---------------------------------------------------------------------------

func TestListShedScopeReturnsEveryActiveShedInOrder(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	scope, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: fdTenant, ParkID: fdPark})
	if err != nil {
		t.Fatalf("ListShedScope: %v", err)
	}
	if len(scope.Items) != 2 {
		t.Fatalf("sheds = %d, want 2 active (the inactive shed is excluded)", len(scope.Items))
	}
	// Stable ordering is what makes the service's in-memory page slice a real page rather than an
	// arbitrary subset that could repeat or skip a shed between requests.
	if scope.Items[0].Label != "Shed A" || scope.Items[1].Label != "Shed B" {
		t.Fatalf("sheds = %+v, want display order", scope.Items)
	}
}

func TestListShedScopeNarrowsToOneShed(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	scope, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: fdTenant, ParkID: fdPark, ShedID: fdShedB})
	if err != nil {
		t.Fatalf("ListShedScope: %v", err)
	}
	if len(scope.Items) != 1 || scope.Items[0].ShedID != fdShedB {
		t.Fatalf("filtered scope = %+v, want only shed B", scope.Items)
	}
}

// The scope read is what the whole-scope summary covers, so a park that outgrows the tripwire must
// FAIL rather than return a prefix. A truncated scope is a total that is quietly too small, which
// an operator packs against with no error anywhere -- the exact defect class the summary rewrite
// removed.
func TestListShedScopeFailsClosedRatherThanTruncating(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	// Push the park just past the tripwire.
	if _, err := pool.Exec(ctx, `
INSERT INTO locations (tenant_id, location_id, parent_location_id, location_type, name, location_code, status, display_order)
SELECT $1::uuid,
       ('fd000000-0000-4000-8000-' || lpad((900000 + g)::text, 12, '0'))::uuid,
       $2::uuid, 'shed', 'Bulk Shed ' || g, 'BULK' || g, 'active', 100 + g
FROM generate_series(1, $3::int) g`, fdTenant, fdPark, MaxShedScopeRows+1); err != nil {
		t.Fatalf("seed bulk sheds: %v", err)
	}

	_, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: fdTenant, ParkID: fdPark})
	if !errors.Is(err, ports.ErrScopeTooLarge) {
		t.Fatalf("err = %v, want ErrScopeTooLarge -- an oversized scope must never return a silent partial", err)
	}
}

// P2-CAP regression: loadRates had no LIMIT/+1 tripwire at all before this fix -- unlike
// ListShedScope in the same package (proved above), an oversized ration grid would be read in
// full with no bound, rather than failing closed. Seed past MaxRationRateRows and prove the whole
// config-snapshot load fails with ErrScopeTooLarge instead of silently loading a partial (or,
// pre-fix, unboundedly large) grid.
func TestLoadRatesFailsClosedRatherThanUnboundedRead(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	if _, err := pool.Exec(ctx, `
INSERT INTO feed_ration_rates (tenant_id, park_id, ration_group_label, shed_tag_label, feed_item_label, grams_per_head, valid_from, source_system)
SELECT $1::uuid, $2::uuid, 'Bulk Group ' || g, 'Bulk Tag', 'Bulk Item', 100, '2026-01-01'::date, 'test'
FROM generate_series(1, $3::int) g`, fdTenant, fdPark, MaxRationRateRows+1); err != nil {
		t.Fatalf("seed bulk ration rates: %v", err)
	}

	_, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC))
	if !errors.Is(err, ports.ErrScopeTooLarge) {
		t.Fatalf("err = %v, want ErrScopeTooLarge -- an oversized ration grid must never be read unboundedly", err)
	}
}

// P2-CAP regression, session-slot twin of the ration-rate test above: loadSessionItems also had no
// tripwire.
func TestLoadSessionItemsFailsClosedRatherThanUnboundedRead(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	// slot_no offset past the fixture's existing session-1 slots (1-3) so this bulk insert does not
	// collide with feed_session_template_items_open_slot_uidx.
	if _, err := pool.Exec(ctx, `
INSERT INTO feed_session_template_items (tenant_id, park_id, session_no, slot_no, feed_item_label, status, valid_from)
SELECT $1::uuid, $2::uuid, 1, 1000 + g, 'Bulk Slot Item ' || g, 'active', '2026-01-01'::date
FROM generate_series(1, $3::int) g`, fdTenant, fdPark, MaxSessionItemRows+1); err != nil {
		t.Fatalf("seed bulk session items: %v", err)
	}

	_, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC))
	if !errors.Is(err, ports.ErrScopeTooLarge) {
		t.Fatalf("err = %v, want ErrScopeTooLarge -- an oversized session slot set must never be read unboundedly", err)
	}
}

// A mistyped park must fail CLOSED. An empty page looks exactly like "nothing to feed today", and
// that is the one answer a feed surface must never give by accident.
func TestUnknownParkFailsClosedRatherThanReturningAnEmptyPage(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	missing := "fd000000-0000-4000-8000-0000000039ff"
	if _, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: fdTenant, ParkID: missing}); !errors.Is(err, ports.ErrParkNotFound) {
		t.Fatalf("err = %v, want ErrParkNotFound", err)
	}
	if _, err := repo.LoadConfigSnapshot(ctx, fdTenant, missing, businessDay(2026, 7, 19)); !errors.Is(err, ports.ErrParkNotFound) {
		t.Fatalf("err = %v, want ErrParkNotFound", err)
	}
	// A SHED id passed as a park id is rejected on type, not accepted because it happens to be a
	// valid location.
	if _, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: fdTenant, ParkID: fdShedA}); !errors.Is(err, ports.ErrParkNotFound) {
		t.Fatalf("err = %v, want ErrParkNotFound for a shed id used as a park", err)
	}
}

func TestShedScopeIsTenantScoped(t *testing.T) {
	ctx := context.Background()
	repo, pool := setupFeedDirectionDB(t, ctx)

	other := "fd000000-0000-4000-8000-0000000000ff"
	if _, err := pool.Exec(ctx, `INSERT INTO tenants (tenant_id, name, status) VALUES ($1::uuid, 'Other', 'active')
ON CONFLICT (tenant_id) DO NOTHING`, other); err != nil {
		t.Fatalf("seed other tenant: %v", err)
	}
	if _, err := repo.ListShedScope(ctx, ports.ShedScopeQuery{TenantID: other, ParkID: fdPark}); !errors.Is(err, ports.ErrParkNotFound) {
		t.Fatalf("err = %v, want ErrParkNotFound -- another tenant's park must not resolve", err)
	}
}

func businessDay(year int, month time.Month, day int) time.Time {
	return time.Date(year, month, day, 0, 0, 0, 0, biztime.DefaultLocation())
}

// ---------------------------------------------------------------------------
// The session recipe (migration 000005)
// ---------------------------------------------------------------------------

// The slots are what stop the generator walking the whole feed_item_catalog. Four properties of
// that read are only observable against a real database, and each of them silently produces a WRONG
// FEED SHEET rather than an error:
//
//	SLOT ORDER      -- slot_no is packing order, not catalog order. Session 1 declares Hybrid before
//	                   Concentrate here precisely because the catalog's display_order is the reverse;
//	                   a query that forgot ORDER BY slot_no would still "pass" against a fixture
//	                   whose two orders agreed.
//	PER-SESSION     -- session 1's slots must not leak into session 2's row.
//	STATUS FILTER   -- a retired slot is no longer part of the recipe.
//	KEY PARITY      -- feed_item_key is GENERATED by feed_config_norm(), and it is the string the
//	                   generator matches against the rate grid's own generated key. If the two ever
//	                   diverge, a declared slot silently blocks.
func TestSessionSlotsLoadInPackingOrderScopedToTheirOwnSession(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdPark, biztime.BusinessDayStart(time.Now()))
	if err != nil {
		t.Fatalf("load snapshot: %v", err)
	}
	if len(snapshot.Sessions) != 2 {
		t.Fatalf("sessions = %d, want 2 active", len(snapshot.Sessions))
	}

	// Session 1: both active slots, in slot_no order -- which is the REVERSE of catalog order.
	got := []string{}
	for _, item := range snapshot.Sessions[0].Items {
		got = append(got, item.Label)
	}
	if len(got) != 2 || got[0] != "Hybrid" || got[1] != "Concentrate" {
		t.Fatalf("session 1 slots = %v, want [Hybrid Concentrate] in slot_no order; the retired slot must be excluded", got)
	}

	// Session 2 declares only one slot. Session 1's second slot must not leak into it.
	if len(snapshot.Sessions[1].Items) != 1 || snapshot.Sessions[1].Items[0].Label != "Concentrate" {
		t.Fatalf("session 2 slots = %+v, want only Concentrate", snapshot.Sessions[1].Items)
	}

	// The GENERATED key must be the one the generator joins on, so a declared slot finds its rate.
	for _, item := range snapshot.Sessions[0].Items {
		if item.Key != domain.NormalizeConfigKey(item.Label) {
			t.Fatalf("slot %q stored key %q != Go NormalizeConfigKey %q; a declared slot would silently block",
				item.Label, item.Key, domain.NormalizeConfigKey(item.Label))
		}
	}

	// The union the generator resolves rates against: distinct, first-declared order.
	planned := []string{}
	for _, item := range snapshot.PlannedFeedItems() {
		planned = append(planned, item.Label)
	}
	if len(planned) != 2 || planned[0] != "Hybrid" || planned[1] != "Concentrate" {
		t.Fatalf("planned items = %v, want [Hybrid Concentrate] deduped across sessions", planned)
	}
}

// Slots are park-scoped like the rates they pair with. CBE's recipe must never be served to CPT --
// the two parks genuinely differ, and this is the same failure shape as TestRatesAreParkScoped.
func TestSessionSlotsAreParkScoped(t *testing.T) {
	ctx := context.Background()
	repo, _ := setupFeedDirectionDB(t, ctx)

	snapshot, err := repo.LoadConfigSnapshot(ctx, fdTenant, fdOtherPark, biztime.BusinessDayStart(time.Now()))
	if err != nil {
		t.Fatalf("load snapshot: %v", err)
	}
	// The other park has no session template at all, so it has no recipe either -- and crucially it
	// does NOT inherit CPT's.
	if len(snapshot.PlannedFeedItems()) != 0 {
		t.Fatalf("other park planned items = %+v, want none; a park must never inherit another park's recipe",
			snapshot.PlannedFeedItems())
	}
}
