SELECT current_database(),current_setting('transaction_read_only'),now();
SELECT 'feed_catalog' AS section,feed_item_key,feed_item_label,status,energy_kcal_per_kg,dry_matter_factor,wastage_factor FROM feed_item_catalog ORDER BY display_order;
SELECT 'ration_groups' AS section,breed_key,ration_group_key FROM feed_ration_groups ORDER BY breed_key,ration_group_key;
SELECT 'ration_rates' AS section,ration_group_key,shed_tag_key,feed_item_key,min(grams_per_head) AS min_g_head,max(grams_per_head) AS max_g_head,count(*) AS rows,min(valid_from) AS first_date,max(valid_from) AS latest_date,count(*) FILTER(WHERE valid_to IS NULL) AS open_ended FROM feed_ration_rates GROUP BY 2,3,4 ORDER BY 2,3,4;
SELECT 'feed_schedules' AS section,workflow,direction_time,correction_time,transport_time,valid_from,valid_to,count(*) FROM feed_schedule_config GROUP BY 2,3,4,5,6,7 ORDER BY 2,6;
SELECT 'feed_experiments' AS section,feed_item_key,experiment_category,quantity_basis,status,count(*),min(grams_per_head),max(grams_per_head),min(absolute_kg),max(absolute_kg) FROM feed_experiment_config GROUP BY 2,3,4,5 ORDER BY 2,3;
SELECT 'stage_catalog' AS section,stage_code,name,min_age_days,max_age_days,age_band,status FROM animal_stage_lookup ORDER BY sort_order;
SELECT 'breeds' AS section,species,canonical_name,status FROM breeds ORDER BY species,canonical_name;
SELECT 'health_versions' AS section,disease_key,age_band,version,duration_days,status FROM health_protocol_versions ORDER BY disease_key,age_band,version;
SELECT 'health_step_shapes' AS section,record_type,medicine_route,dosage_denominator,critical_action_type,count(*) FROM health_protocol_steps GROUP BY 2,3,4,5 ORDER BY 2,3;
SELECT 'protocol_dsl' AS section,d.code,v.version,v.status,v.rule_dsl,v.proof_policy FROM protocol_versions v JOIN protocol_definitions d USING(protocol_id) WHERE v.status IN ('published','draft');
SELECT 'vaccine_capacity' AS section,max_per_day,capacity_scope,max_buffer_days,overflow_policy,max_shots_per_animal_per_drive FROM vaccination_capacity_config;
SELECT 'vaccine_rules' AS section,v.version,v.status,r.dose_code,r.trigger_type,r.offset_days,r.due_window_days,r.min_gap_days,r.repeat,r.catch_up,r.proof_policy FROM protocol_rules r JOIN protocol_versions v USING(protocol_version_id) WHERE v.status='published' ORDER BY dose_code,sequence;
SELECT 'sales_benchmarks' AS section,market,category,breed,ex_farm_rate,transport_rate,landing_cost_per_kg,market_price_per_kg FROM sales_market_benchmarks ORDER BY market,category,breed;
SELECT 'vendor_catalog_shape' AS section,kind,register_side,is_active,count(*) FROM procurement_vendor_catalog GROUP BY 2,3,4 ORDER BY 2,3;
SELECT 'leave_policy' AS section,park_head_required,hr_required,row_version FROM workforce_leave_approval_config;
SELECT 'identifier_policies' AS section,policy_version,identifier_type,default_scope_type,scope_required,active_uniqueness,auto_link_allowed,primary_allowed,unknown_scope_action,missing_or_conflicting_scope_action,normalizer_version FROM identifier_policies;
SELECT 'status_catalog' AS section,status_code,axis,display_name,expected_duration_days,active FROM status_definitions ORDER BY axis,sort_order;
SELECT 'milk_sop' AS section,d.code,v.version,v.form_dsl,v.proof_policy FROM sop_versions v JOIN sop_definitions d USING(sop_id) WHERE d.code IN ('milk.feeding','milk.preparation') AND v.status='published';
SELECT 'cutoff' AS section,cutoff_time FROM feed_water_removal_config;
SELECT 'market_call' AS section,call_time FROM market_survey_config;
