// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202606 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202607 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202608 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202609 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLogDefault struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuthPendingEmailGrant struct {
	PendingGrantID             pgtype.UUID
	TenantID                   pgtype.UUID
	Email                      string
	NormalizedEmail            string
	Role                       string
	ScopeType                  string
	ScopeID                    pgtype.UUID
	Status                     string
	ValidFrom                  pgtype.Timestamptz
	ValidTo                    pgtype.Timestamptz
	Source                     string
	CreatedBy                  pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	LastClaimedUserID          pgtype.UUID
	LastClaimedExternalSubject pgtype.Text
	LastClaimedAt              pgtype.Timestamptz
	ClaimCount                 int64
	Metadata                   []byte
}

type Breed struct {
	BreedID       pgtype.UUID
	Species       string
	CanonicalName string
	Status        string
	ReviewNotes   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type BreedAlias struct {
	AliasID         pgtype.UUID
	BreedID         pgtype.UUID
	Alias           string
	NormalizedAlias string
	SourceSystem    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type Goat struct {
	GoatID             pgtype.UUID
	TenantID           pgtype.UUID
	DisplayID          string
	Species            string
	Breed              pgtype.Text
	BreedID            pgtype.UUID
	Sex                pgtype.Text
	ApproxDob          pgtype.Date
	AgeBand            pgtype.Text
	LifecycleStatus    string
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      string
	CustodianPartyID   pgtype.UUID
	CurrentLocationID  pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	MergedIntoGoatID   pgtype.UUID
	SourceConfidence   pgtype.Numeric
	RowVersion         int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
}

type GoatCustodyHistory struct {
	CustodyHistoryID pgtype.UUID
	TenantID         pgtype.UUID
	GoatID           pgtype.UUID
	CustodianPartyID pgtype.UUID
	FromLocationID   pgtype.UUID
	ToLocationID     pgtype.UUID
	ValidFrom        pgtype.Timestamptz
	ValidTo          pgtype.Timestamptz
	DecisionID       pgtype.UUID
	Reason           pgtype.Text
	CreatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
}

type GoatIdentifier struct {
	IdentifierID      pgtype.UUID
	TenantID          pgtype.UUID
	GoatID            pgtype.UUID
	IdentifierType    string
	IdentifierValue   string
	NormalizedValue   string
	ScopeKey          string
	IsPrimaryForGoat  bool
	Status            string
	ValidFrom         pgtype.Timestamptz
	ValidTo           pgtype.Timestamptz
	SourceSystem      pgtype.Text
	SourceRecordID    pgtype.Text
	NormalizerVersion string
	Confidence        pgtype.Numeric
	ApprovedBy        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type GoatIdentityCounter struct {
	CounterID          pgtype.UUID
	CounterGrain       string
	TenantID           pgtype.UUID
	CustodianPartyID   pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            pgtype.UUID
	Sex                pgtype.Text
	CountValue         int64
	AsOfRecordedAt     pgtype.Timestamptz
	SourceImportRunID  pgtype.UUID
	IsRebuilding       bool
	UpdatedAt          pgtype.Timestamptz
}

type GoatIdentityCounterMembership struct {
	CounterGrain       string
	TenantID           pgtype.UUID
	GoatID             pgtype.UUID
	CustodianPartyID   pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	LifecycleStatus    string
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            pgtype.UUID
	Sex                pgtype.Text
}

type GoatIdentityCounterProcessedEvent struct {
	TenantID        pgtype.UUID
	EventID         pgtype.UUID
	EventRecordedAt pgtype.Timestamptz
	EventType       string
	Outcome         string
	ProcessedAt     pgtype.Timestamptz
}

type GoatIdentityCounterProjectionState struct {
	TenantID                pgtype.UUID
	LastProcessedRecordedAt pgtype.Timestamptz
	LastProcessedEventID    pgtype.UUID
	RebuildRequired         bool
	RebuildReason           pgtype.Text
	UpdatedAt               pgtype.Timestamptz
}

type GoatIdentityEvent struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202606 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202607 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202608 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202609 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEventsDefault struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatLocationHistory struct {
	LocationHistoryID pgtype.UUID
	TenantID          pgtype.UUID
	GoatID            pgtype.UUID
	FromLocationID    pgtype.UUID
	ToLocationID      pgtype.UUID
	Reason            pgtype.Text
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	SourceRecordID    pgtype.Text
}

type GoatMergeLink struct {
	MergeLinkID    pgtype.UUID
	TenantID       pgtype.UUID
	SurvivorGoatID pgtype.UUID
	MergedGoatID   pgtype.UUID
	DecisionID     pgtype.UUID
	Reason         string
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
}

type GoatOwnership struct {
	OwnershipID  pgtype.UUID
	TenantID     pgtype.UUID
	GoatID       pgtype.UUID
	OwnerPartyID pgtype.UUID
	ShareBps     int32
	ValidFrom    pgtype.Timestamptz
	ValidTo      pgtype.Timestamptz
	Status       string
	DecisionID   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
}

type IdempotencyKey struct {
	IdempotencyKey string
	TenantID       pgtype.UUID
	Scope          string
	RequestHash    string
	Status         string
	ResultType     pgtype.Text
	ResultID       pgtype.UUID
	FirstSeenAt    pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type IdentifierPolicy struct {
	PolicyVersion                   string
	IdentifierType                  string
	DefaultScopeType                string
	ScopeRequired                   bool
	ActiveUniqueness                string
	AutoLinkAllowed                 bool
	PrimaryAllowed                  bool
	UnknownScopeAction              string
	MissingOrConflictingScopeAction string
	NormalizerVersion               string
	FormatValidatorVersion          pgtype.Text
	InvalidValueAction              string
	CreatedAt                       pgtype.Timestamptz
	ApprovedBy                      pgtype.UUID
}

type IdentifierPolicyVersion struct {
	PolicyVersion string
	Status        string
	CreatedAt     pgtype.Timestamptz
	ApprovedAt    pgtype.Timestamptz
	ApprovedBy    pgtype.UUID
}

type IdentityConflict struct {
	ConflictID      pgtype.UUID
	TenantID        pgtype.UUID
	ConflictType    string
	Severity        string
	State           string
	IdentifierType  pgtype.Text
	IdentifierValue pgtype.Text
	GoatIds         []pgtype.UUID
	SourceRecordIds []string
	Evidence        []byte
	CreatedAt       pgtype.Timestamptz
	ResolvedAt      pgtype.Timestamptz
	ResolvedBy      pgtype.UUID
	DecisionID      pgtype.UUID
	RowVersion      int32
}

type IdentityConflictGoat struct {
	ConflictID pgtype.UUID
	TenantID   pgtype.UUID
	GoatID     pgtype.UUID
	Role       string
	CreatedAt  pgtype.Timestamptz
}

type IdentityConflictSourceRecord struct {
	ConflictID     pgtype.UUID
	TenantID       pgtype.UUID
	SourceSystem   string
	SourceRecordID string
	CreatedAt      pgtype.Timestamptz
}

type IdentityCorrectionRequest struct {
	CorrectionRequestID pgtype.UUID
	TenantID            pgtype.UUID
	RequestType         string
	State               string
	GoatID              pgtype.UUID
	IdentifierType      pgtype.Text
	IdentifierValue     pgtype.Text
	FarmID              pgtype.UUID
	ParkID              pgtype.UUID
	ShedID              pgtype.UUID
	CohortID            pgtype.UUID
	Description         string
	Evidence            []byte
	RequestedBy         pgtype.UUID
	AssignedReviewerID  pgtype.UUID
	DecisionID          pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	RowVersion          int32
}

type IdentityDecision struct {
	DecisionID          pgtype.UUID
	TenantID            pgtype.UUID
	DecisionType        string
	DecisionResult      string
	DecisionState       string
	DecidedByType       string
	DecidedBy           pgtype.UUID
	PolicyVersion       string
	SourceRecordIds     []string
	SourceIdentifierIds []pgtype.UUID
	SourceGoatIds       []pgtype.UUID
	SourceEventIds      []pgtype.UUID
	SourceMediaIds      []pgtype.UUID
	ModelVersion        pgtype.Text
	Confidence          pgtype.Numeric
	ReviewerID          pgtype.UUID
	Evidence            []byte
	CreatedAt           pgtype.Timestamptz
	ApprovedAt          pgtype.Timestamptz
	DecidedAt           pgtype.Timestamptz
}

type IdentityDecisionEvent struct {
	DecisionID      pgtype.UUID
	TenantID        pgtype.UUID
	EventID         pgtype.UUID
	EventRecordedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type IdentityDecisionGoat struct {
	DecisionID pgtype.UUID
	TenantID   pgtype.UUID
	GoatID     pgtype.UUID
	Role       string
	CreatedAt  pgtype.Timestamptz
}

type IdentityDecisionIdentifier struct {
	DecisionIdentifierID pgtype.UUID
	DecisionID           pgtype.UUID
	TenantID             pgtype.UUID
	IdentifierID         pgtype.UUID
	IdentifierType       pgtype.Text
	IdentifierValue      pgtype.Text
	Action               string
	CreatedAt            pgtype.Timestamptz
}

type IdentityDecisionMedium struct {
	DecisionID pgtype.UUID
	TenantID   pgtype.UUID
	MediaID    pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type IdentityMatchCandidate struct {
	CandidateID     pgtype.UUID
	TenantID        pgtype.UUID
	LegacyRowID     pgtype.UUID
	ProposedGoatID  pgtype.UUID
	CandidateGoatID pgtype.UUID
	MatchScore      pgtype.Numeric
	MatchReasons    []byte
	State           string
	CreatedBy       string
	ReviewedBy      pgtype.UUID
	ReviewedAt      pgtype.Timestamptz
	DecisionID      pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	RowVersion      int32
}

type LegacyImportPolicy struct {
	PolicyVersion           string
	SourceSystem            string
	SourceDataset           string
	IdentifierPolicyVersion string
	SourceKeyRecipe         []byte
	SourceKeyRecipeVersion  string
	HashRecipe              []byte
	HashRecipeVersion       string
	FieldDiffPolicy         []byte
	AutoLinkPolicy          []byte
	NormalizerVersion       string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	ApprovedAt              pgtype.Timestamptz
	ApprovedBy              pgtype.UUID
}

type LegacyImportRow struct {
	LegacyRowID            pgtype.UUID
	TenantID               pgtype.UUID
	ImportRunID            pgtype.UUID
	RowNumber              int32
	SourceSystem           string
	SourceDataset          string
	SourceRecordID         pgtype.Text
	SourceRowKey           string
	SourceKeyRecipeVersion string
	SourceRowVersionHash   string
	HashRecipeVersion      string
	RawPayload             []byte
	NormalizedPayload      []byte
	ProcessingState        string
	MatchedGoatID          pgtype.UUID
	ErrorReason            pgtype.Text
	CreatedAt              pgtype.Timestamptz
	RowVersion             int32
}

type LegacyImportRun struct {
	ImportRunID      pgtype.UUID
	TenantID         pgtype.UUID
	SourceName       string
	SourceSystem     string
	SourceDataset    string
	SourceFileRef    pgtype.Text
	SourceFileHash   pgtype.Text
	PolicyVersion    string
	DryRun           bool
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	Status           string
	RowCount         int32
	CreatedGoatCount int32
	UpdatedGoatCount int32
	ConflictCount    int32
	ErrorCount       int32
	StartedBy        pgtype.UUID
}

type LegacyStatusMapping struct {
	MappingID          pgtype.UUID
	SourceSystem       string
	RawLabel           string
	NormalizedRawLabel string
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	SexOverride        pgtype.Text
	DisplayStatusCode  pgtype.Text
	Confidence         string
	ReviewRequired     bool
	Notes              pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type LegacySyncRun struct {
	SyncRunID          pgtype.UUID
	TenantID           pgtype.UUID
	RequestedBy        pgtype.UUID
	Mode               string
	Domain             string
	Status             string
	ColdStart          bool
	SourceWindowStart  pgtype.Timestamptz
	SourceWindowEnd    pgtype.Timestamptz
	EtaSeconds         pgtype.Int4
	RowsRead           int32
	RowsPlanned        int32
	RowsApplied        int32
	RowsSkipped        int32
	GoatsCreated       int32
	GoatsUpdated       int32
	ConflictsOpened    int32
	ConflictsRefreshed int32
	CountersRebuilt    bool
	CounterCheckStatus string
	FreshnessStatus    string
	BlockedReason      pgtype.Text
	CancelRequestedAt  pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	TraceID            pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type LegacySyncRunConflict struct {
	SyncRunConflictID  pgtype.UUID
	TenantID           pgtype.UUID
	SyncRunID          pgtype.UUID
	SourceID           string
	SourceRecordID     string
	SourceConflictKey  string
	ConflictID         pgtype.UUID
	GoatID             pgtype.UUID
	EvidenceReason     string
	Result             string
	OldGoatosValue     pgtype.Text
	NewLegacyValue     pgtype.Text
	PreviousDecisionID pgtype.UUID
	PreviousDecisionAt pgtype.Timestamptz
	AuditID            pgtype.UUID
	Evidence           []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type LegacySyncRunStep struct {
	SyncStepID  pgtype.UUID
	SyncRunID   pgtype.UUID
	SourceID    pgtype.Text
	StepName    string
	Status      string
	RowsRead    int32
	RowsPlanned int32
	RowsApplied int32
	RowsSkipped int32
	Details     []byte
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type LegacySyncSource struct {
	SourceID            string
	SourceName          string
	Domain              string
	SourceKind          string
	BqProject           pgtype.Text
	BqDataset           pgtype.Text
	BqTableOrConfig     pgtype.Text
	CadenceSeconds      int32
	GreenWithinSeconds  int32
	YellowWithinSeconds int32
	Criticality         string
	Enabled             bool
	KnownDegraded       bool
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type LegacySyncSourceStatus struct {
	TenantID             pgtype.UUID
	SourceID             string
	FreshnessStatus      string
	StatusReason         string
	SourceWatermarkAt    pgtype.Timestamptz
	ObservedAt           pgtype.Timestamptz
	LastSuccessSyncRunID pgtype.UUID
	LatestError          pgtype.Text
	RowsSeen             int32
	IsUnknownSource      bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type LegacySyncSourceWatermark struct {
	TenantID               pgtype.UUID
	SourceID               string
	LastSuccessWindowStart pgtype.Timestamptz
	LastSuccessWindowEnd   pgtype.Timestamptz
	LastSuccessAt          pgtype.Timestamptz
	LastSuccessSyncRunID   pgtype.UUID
	Checkpoint             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type Location struct {
	LocationID       pgtype.UUID
	TenantID         pgtype.UUID
	LocationType     string
	LocationCode     pgtype.Text
	Name             string
	ParentLocationID pgtype.UUID
	Country          string
	StateRegion      pgtype.Text
	District         pgtype.Text
	Pincode          pgtype.Text
	Lat              pgtype.Numeric
	Lng              pgtype.Numeric
	Timezone         string
	Status           string
	CreatedAt        pgtype.Timestamptz
}

type LocationAlias struct {
	AliasID             pgtype.UUID
	TenantID            pgtype.UUID
	AliasCode           string
	CanonicalLocationID pgtype.UUID
	SourceContext       string
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
}

type Org struct {
	PartyID   pgtype.UUID
	OrgType   string
	LegalName pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OutboxMessage struct {
	OutboxID       pgtype.UUID
	TenantID       pgtype.UUID
	EventID        pgtype.UUID
	EventType      string
	SchemaVersion  string
	AggregateType  string
	AggregateID    pgtype.UUID
	Topic          string
	Payload        []byte
	Headers        []byte
	IdempotencyKey string
	TraceID        pgtype.Text
	Status         string
	AttemptCount   int32
	NextAttemptAt  pgtype.Timestamptz
	LastError      pgtype.Text
	PublishedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Party struct {
	PartyID     pgtype.UUID
	PartyType   string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type StatusDefinition struct {
	StatusCode           string
	Axis                 string
	DisplayName          string
	ShortLabel           string
	Description          pgtype.Text
	LegacyLabel          pgtype.Text
	SortOrder            int32
	Active               bool
	ExpectedDurationDays pgtype.Int4
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Tenant struct {
	TenantID  pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserScopeGrant struct {
	GrantID   pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	ScopeType string
	ScopeID   pgtype.UUID
	Status    string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
