// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOpenConflictForIdentifier = `-- name: FindOpenConflictForIdentifier :one
SELECT conflict_id::text AS conflict_id
FROM identity_conflicts
WHERE tenant_id = $1
  AND identifier_type = $2
  AND identifier_value = $3
  AND evidence->>'scope_key' = $4::text
  AND state IN ('open', 'needs_field_check')
ORDER BY created_at DESC
LIMIT 1
`

type FindOpenConflictForIdentifierParams struct {
	TenantID        pgtype.UUID
	IdentifierType  pgtype.Text
	IdentifierValue pgtype.Text
	ScopeKey        string
}

func (q *Queries) FindOpenConflictForIdentifier(ctx context.Context, arg FindOpenConflictForIdentifierParams) (string, error) {
	row := q.db.QueryRow(ctx, findOpenConflictForIdentifier,
		arg.TenantID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.ScopeKey,
	)
	var conflict_id string
	err := row.Scan(&conflict_id)
	return conflict_id, err
}

const getGoatByDisplayID = `-- name: GetGoatByDisplayID :one
SELECT
  g.goat_id::text AS goat_id,
  g.display_id,
  animal_id_1.identifier_value AS animal_identifier_1,
  animal_id_2.identifier_value AS animal_identifier_2,
  g.breed,
  g.sex,
  g.age_band,
  g.lifecycle_status,
  g.reproductive_status,
  g.growth_cohort_tag,
  g.management_stage,
  g.health_status,
  COALESCE(loc.name, 'Unknown location') AS location_display,
  COALESCE(g.farm_id::text, '')::text AS farm_id,
  COALESCE(g.park_id::text, '')::text AS park_id,
  COALESCE(g.shed_id::text, '')::text AS shed_id,
  COALESCE(g.cohort_id::text, '')::text AS cohort_id,
  g.species,
  COALESCE(g.merged_into_goat_id::text, '')::text AS merged_into_goat_id,
  g.row_version
FROM goats g
LEFT JOIN locations loc ON loc.tenant_id = g.tenant_id AND loc.location_id = g.current_location_id
LEFT JOIN goat_identifiers animal_id_1 ON animal_id_1.tenant_id = g.tenant_id
  AND animal_id_1.goat_id = g.goat_id
  AND animal_id_1.identifier_type = 'animal_identifier_1'
  AND animal_id_1.status = 'active'
LEFT JOIN goat_identifiers animal_id_2 ON animal_id_2.tenant_id = g.tenant_id
  AND animal_id_2.goat_id = g.goat_id
  AND animal_id_2.identifier_type = 'animal_identifier_2'
  AND animal_id_2.status = 'active'
WHERE g.tenant_id = $1 AND g.display_id = $2
`

type GetGoatByDisplayIDParams struct {
	TenantID  pgtype.UUID
	DisplayID string
}

type GetGoatByDisplayIDRow struct {
	GoatID             string
	DisplayID          string
	AnimalIdentifier1  pgtype.Text
	AnimalIdentifier2  pgtype.Text
	Breed              pgtype.Text
	Sex                string
	AgeBand            pgtype.Text
	LifecycleStatus    string
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	LocationDisplay    string
	FarmID             string
	ParkID             string
	ShedID             string
	CohortID           string
	Species            string
	MergedIntoGoatID   string
	RowVersion         int32
}

func (q *Queries) GetGoatByDisplayID(ctx context.Context, arg GetGoatByDisplayIDParams) (GetGoatByDisplayIDRow, error) {
	row := q.db.QueryRow(ctx, getGoatByDisplayID, arg.TenantID, arg.DisplayID)
	var i GetGoatByDisplayIDRow
	err := row.Scan(
		&i.GoatID,
		&i.DisplayID,
		&i.AnimalIdentifier1,
		&i.AnimalIdentifier2,
		&i.Breed,
		&i.Sex,
		&i.AgeBand,
		&i.LifecycleStatus,
		&i.ReproductiveStatus,
		&i.GrowthCohortTag,
		&i.ManagementStage,
		&i.HealthStatus,
		&i.LocationDisplay,
		&i.FarmID,
		&i.ParkID,
		&i.ShedID,
		&i.CohortID,
		&i.Species,
		&i.MergedIntoGoatID,
		&i.RowVersion,
	)
	return i, err
}

const getGoatByID = `-- name: GetGoatByID :one
SELECT
  g.goat_id::text AS goat_id,
  g.display_id,
  animal_id_1.identifier_value AS animal_identifier_1,
  animal_id_2.identifier_value AS animal_identifier_2,
  g.breed,
  g.sex,
  g.age_band,
  g.lifecycle_status,
  g.reproductive_status,
  g.growth_cohort_tag,
  g.management_stage,
  g.health_status,
  COALESCE(loc.name, 'Unknown location') AS location_display,
  COALESCE(g.farm_id::text, '')::text AS farm_id,
  COALESCE(g.park_id::text, '')::text AS park_id,
  COALESCE(g.shed_id::text, '')::text AS shed_id,
  COALESCE(g.cohort_id::text, '')::text AS cohort_id,
  g.species,
  COALESCE(g.merged_into_goat_id::text, '')::text AS merged_into_goat_id,
  g.row_version
FROM goats g
LEFT JOIN locations loc ON loc.tenant_id = g.tenant_id AND loc.location_id = g.current_location_id
LEFT JOIN goat_identifiers animal_id_1 ON animal_id_1.tenant_id = g.tenant_id
  AND animal_id_1.goat_id = g.goat_id
  AND animal_id_1.identifier_type = 'animal_identifier_1'
  AND animal_id_1.status = 'active'
LEFT JOIN goat_identifiers animal_id_2 ON animal_id_2.tenant_id = g.tenant_id
  AND animal_id_2.goat_id = g.goat_id
  AND animal_id_2.identifier_type = 'animal_identifier_2'
  AND animal_id_2.status = 'active'
WHERE g.tenant_id = $1 AND g.goat_id = $2
`

type GetGoatByIDParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetGoatByIDRow struct {
	GoatID             string
	DisplayID          string
	AnimalIdentifier1  pgtype.Text
	AnimalIdentifier2  pgtype.Text
	Breed              pgtype.Text
	Sex                string
	AgeBand            pgtype.Text
	LifecycleStatus    string
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	LocationDisplay    string
	FarmID             string
	ParkID             string
	ShedID             string
	CohortID           string
	Species            string
	MergedIntoGoatID   string
	RowVersion         int32
}

func (q *Queries) GetGoatByID(ctx context.Context, arg GetGoatByIDParams) (GetGoatByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoatByID, arg.TenantID, arg.GoatID)
	var i GetGoatByIDRow
	err := row.Scan(
		&i.GoatID,
		&i.DisplayID,
		&i.AnimalIdentifier1,
		&i.AnimalIdentifier2,
		&i.Breed,
		&i.Sex,
		&i.AgeBand,
		&i.LifecycleStatus,
		&i.ReproductiveStatus,
		&i.GrowthCohortTag,
		&i.ManagementStage,
		&i.HealthStatus,
		&i.LocationDisplay,
		&i.FarmID,
		&i.ParkID,
		&i.ShedID,
		&i.CohortID,
		&i.Species,
		&i.MergedIntoGoatID,
		&i.RowVersion,
	)
	return i, err
}

const listGoatTimeline = `-- name: ListGoatTimeline :many
SELECT
  e.identity_event_id::text AS event_id,
  e.event_type,
  e.occurred_at,
  e.recorded_at,
  CASE WHEN e.actor_id IS NULL THEN 'system' ELSE 'human' END::text AS actor_type,
  COALESCE(e.payload->'evidence_refs', '[]'::jsonb)::text AS evidence_refs,
  COALESCE(e.decision_id::text, '')::text AS decision_id
FROM goat_identity_events e
WHERE e.tenant_id = $1
  AND e.goat_id = $2
  AND (
    $3::timestamptz IS NULL
    OR (e.occurred_at, e.identity_event_id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY e.occurred_at DESC, e.identity_event_id DESC
LIMIT $5
`

type ListGoatTimelineParams struct {
	TenantID         pgtype.UUID
	GoatID           pgtype.UUID
	CursorOccurredAt pgtype.Timestamptz
	CursorEventID    pgtype.UUID
	LimitCount       int32
}

type ListGoatTimelineRow struct {
	EventID      string
	EventType    string
	OccurredAt   pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
	ActorType    string
	EvidenceRefs string
	DecisionID   string
}

func (q *Queries) ListGoatTimeline(ctx context.Context, arg ListGoatTimelineParams) ([]ListGoatTimelineRow, error) {
	rows, err := q.db.Query(ctx, listGoatTimeline,
		arg.TenantID,
		arg.GoatID,
		arg.CursorOccurredAt,
		arg.CursorEventID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoatTimelineRow
	for rows.Next() {
		var i ListGoatTimelineRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorType,
			&i.EvidenceRefs,
			&i.DecisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentifiersForGoat = `-- name: ListIdentifiersForGoat :many
SELECT
  identifier_id::text AS identifier_id,
  identifier_type,
  identifier_value,
  scope_key,
  status,
  is_primary_for_goat,
  valid_from,
  valid_to,
  source_system,
  source_record_id,
  COALESCE(confidence::float8, 'NaN'::float8)::float8 AS confidence
FROM goat_identifiers
WHERE tenant_id = $1 AND goat_id = $2
ORDER BY is_primary_for_goat DESC, status ASC, valid_from DESC
`

type ListIdentifiersForGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type ListIdentifiersForGoatRow struct {
	IdentifierID     string
	IdentifierType   string
	IdentifierValue  string
	ScopeKey         string
	Status           string
	IsPrimaryForGoat bool
	ValidFrom        pgtype.Timestamptz
	ValidTo          pgtype.Timestamptz
	SourceSystem     pgtype.Text
	SourceRecordID   pgtype.Text
	Confidence       float64
}

func (q *Queries) ListIdentifiersForGoat(ctx context.Context, arg ListIdentifiersForGoatParams) ([]ListIdentifiersForGoatRow, error) {
	rows, err := q.db.Query(ctx, listIdentifiersForGoat, arg.TenantID, arg.GoatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentifiersForGoatRow
	for rows.Next() {
		var i ListIdentifiersForGoatRow
		if err := rows.Scan(
			&i.IdentifierID,
			&i.IdentifierType,
			&i.IdentifierValue,
			&i.ScopeKey,
			&i.Status,
			&i.IsPrimaryForGoat,
			&i.ValidFrom,
			&i.ValidTo,
			&i.SourceSystem,
			&i.SourceRecordID,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
