// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package feeddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFeedDirection = `-- name: AcceptFeedDirection :many
UPDATE feed_direction_completions
SET status = 'accepted', verified_by = $1, verified_at = now(),
    row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $2 AND completion_id = $3 AND status = 'recorded'
RETURNING obligation_id::text AS obligation_id,
          shed_id::text AS shed_id,
          COALESCE(batch_id::text, '')::text AS batch_id,
          COALESCE(feed_inventory_lot_id::text, '')::text AS feed_inventory_lot_id,
          COALESCE(quantity_fed::text, '')::text AS quantity_fed,
          COALESCE(quantity_unit, '')::text AS quantity_unit,
          fed_at
`

type AcceptFeedDirectionParams struct {
	VerifiedBy   pgtype.UUID
	TenantID     pgtype.UUID
	CompletionID pgtype.UUID
}

type AcceptFeedDirectionRow struct {
	ObligationID       string
	ShedID             string
	BatchID            string
	FeedInventoryLotID string
	QuantityFed        string
	QuantityUnit       string
	FedAt              pgtype.Timestamptz
}

// SM-5 verify (accept). Acts only on a still-recorded row, returning its verification context so the
// caller can complete the obligation + (later) consume feed stock. Idempotent: an already-accepted/
// rejected row matches nothing → no rows → caller no-ops.
func (q *Queries) AcceptFeedDirection(ctx context.Context, arg AcceptFeedDirectionParams) ([]AcceptFeedDirectionRow, error) {
	rows, err := q.db.Query(ctx, acceptFeedDirection, arg.VerifiedBy, arg.TenantID, arg.CompletionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcceptFeedDirectionRow
	for rows.Next() {
		var i AcceptFeedDirectionRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.ShedID,
			&i.BatchID,
			&i.FeedInventoryLotID,
			&i.QuantityFed,
			&i.QuantityUnit,
			&i.FedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedDirectionsByShed = `-- name: ListFeedDirectionsByShed :many
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id,
       COALESCE(batch_id::text, '')::text AS batch_id, fed_at, status,
       COALESCE(quantity_fed::text, '')::text AS quantity_fed, COALESCE(quantity_unit, '')::text AS quantity_unit,
       COALESCE(head_count, 0)::int AS head_count
FROM feed_direction_completions
WHERE tenant_id = $1 AND shed_id = $2
ORDER BY fed_at DESC, completion_id DESC
LIMIT $3
`

type ListFeedDirectionsByShedParams struct {
	TenantID pgtype.UUID
	ShedID   pgtype.UUID
	RowLimit int32
}

type ListFeedDirectionsByShedRow struct {
	CompletionID string
	ObligationID string
	BatchID      string
	FedAt        pgtype.Timestamptz
	Status       string
	QuantityFed  string
	QuantityUnit string
	HeadCount    int32
}

// Per-shed feed history (most recent first). Uses feed_direction_completions_shed_history_idx.
func (q *Queries) ListFeedDirectionsByShed(ctx context.Context, arg ListFeedDirectionsByShedParams) ([]ListFeedDirectionsByShedRow, error) {
	rows, err := q.db.Query(ctx, listFeedDirectionsByShed, arg.TenantID, arg.ShedID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedDirectionsByShedRow
	for rows.Next() {
		var i ListFeedDirectionsByShedRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.BatchID,
			&i.FedAt,
			&i.Status,
			&i.QuantityFed,
			&i.QuantityUnit,
			&i.HeadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedFeedDirections = `-- name: ListRecordedFeedDirections :many
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id,
       shed_id::text AS shed_id, COALESCE(batch_id::text, '')::text AS batch_id, fed_at,
       COALESCE(quantity_fed::text, '')::text AS quantity_fed, COALESCE(quantity_unit, '')::text AS quantity_unit,
       COALESCE(head_count, 0)::int AS head_count
FROM feed_direction_completions
WHERE tenant_id = $1 AND status = 'recorded'
  AND fed_at IS NOT NULL
ORDER BY fed_at ASC, completion_id ASC
LIMIT $2
`

type ListRecordedFeedDirectionsParams struct {
	TenantID pgtype.UUID
	RowLimit int32
}

type ListRecordedFeedDirectionsRow struct {
	CompletionID string
	ObligationID string
	ShedID       string
	BatchID      string
	FedAt        pgtype.Timestamptz
	QuantityFed  string
	QuantityUnit string
	HeadCount    int32
}

// Verification queue: directions awaiting review (status='recorded'), earliest fed first.
// Uses feed_direction_completions_review_idx (tenant_id, fed_at) WHERE status='recorded'.
func (q *Queries) ListRecordedFeedDirections(ctx context.Context, arg ListRecordedFeedDirectionsParams) ([]ListRecordedFeedDirectionsRow, error) {
	rows, err := q.db.Query(ctx, listRecordedFeedDirections, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordedFeedDirectionsRow
	for rows.Next() {
		var i ListRecordedFeedDirectionsRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.ShedID,
			&i.BatchID,
			&i.FedAt,
			&i.QuantityFed,
			&i.QuantityUnit,
			&i.HeadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFeedDirection = `-- name: RecordFeedDirection :one
INSERT INTO feed_direction_completions (
  tenant_id, obligation_id, batch_id, shed_id, ration_protocol_version_id, sop_submission_item_id,
  feed_inventory_lot_id, quantity_fed, quantity_unit, head_count, fed_at, status, recorded_by, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING completion_id::text AS completion_id
`

type RecordFeedDirectionParams struct {
	TenantID                pgtype.UUID
	ObligationID            pgtype.UUID
	BatchID                 pgtype.UUID
	ShedID                  pgtype.UUID
	RationProtocolVersionID pgtype.UUID
	SopSubmissionItemID     pgtype.UUID
	FeedInventoryLotID      pgtype.UUID
	QuantityFed             pgtype.Numeric
	QuantityUnit            pgtype.Text
	HeadCount               pgtype.Int4
	FedAt                   pgtype.Timestamptz
	Status                  string
	RecordedBy              pgtype.UUID
	IdempotencyKey          string
}

// Idempotent on (tenant_id, idempotency_key); returns no row on replay.
func (q *Queries) RecordFeedDirection(ctx context.Context, arg RecordFeedDirectionParams) (string, error) {
	row := q.db.QueryRow(ctx, recordFeedDirection,
		arg.TenantID,
		arg.ObligationID,
		arg.BatchID,
		arg.ShedID,
		arg.RationProtocolVersionID,
		arg.SopSubmissionItemID,
		arg.FeedInventoryLotID,
		arg.QuantityFed,
		arg.QuantityUnit,
		arg.HeadCount,
		arg.FedAt,
		arg.Status,
		arg.RecordedBy,
		arg.IdempotencyKey,
	)
	var completion_id string
	err := row.Scan(&completion_id)
	return completion_id, err
}

const rejectFeedDirection = `-- name: RejectFeedDirection :execrows
UPDATE feed_direction_completions
SET status = 'rejected', verified_by = $1, verified_at = now(),
    rejection_reason = $2, row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $3 AND completion_id = $4 AND status = 'recorded'
`

type RejectFeedDirectionParams struct {
	VerifiedBy      pgtype.UUID
	RejectionReason pgtype.Text
	TenantID        pgtype.UUID
	CompletionID    pgtype.UUID
}

// SM-5 verify (rework). Acts only on a still-recorded row. Idempotent: returns 0 rows on replay.
func (q *Queries) RejectFeedDirection(ctx context.Context, arg RejectFeedDirectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectFeedDirection,
		arg.VerifiedBy,
		arg.RejectionReason,
		arg.TenantID,
		arg.CompletionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
