"use server";

// Counts -> whole-pen stage change. Retags every live animal in one shed+partition at once.
//
// Both actions return the API result rather than redirecting, because this flow is a check-then-
// apply conversation inside a drawer: the operator picks a pen, sees what would change, and only
// then commits. A redirect after preview would throw that away.
//
// Everything visible here is backend-owned. These actions forward the operator's picks and carry an
// Idempotency-Key on the commit; they compose no copy, derive no counts, and never compute the
// operational-location label themselves.
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import {
  commitReclassifyShedStage,
  previewReclassifyShedStage,
  type ApiResult,
  type ReclassifyShedStagePreviewResponse,
  type ReclassifyShedStageRequest,
  type ReclassifyShedStageResponse,
} from "@/lib/api/server";

const BREAKDOWN_PATH = "/counts/breakdown";

export async function previewShedStageAction(
  body: ReclassifyShedStageRequest,
): Promise<ApiResult<ReclassifyShedStagePreviewResponse>> {
  return previewReclassifyShedStage(body);
}

// The idempotency key is generated by the CALLER (the drawer) and held across retries of the same
// intent, so a double-click or a retried network failure replays the first write instead of
// emitting a second round of stage-change events. Generating it here would defeat that -- every
// retry would arrive as a new key.
export async function commitShedStageAction(
  body: ReclassifyShedStageRequest,
  idempotencyKey: string,
): Promise<ApiResult<ReclassifyShedStageResponse>> {
  const result = await commitReclassifyShedStage(body, idempotencyKey || randomUUID());
  if (result.ok) {
    // The breakdown's stage columns and kid/adult split are now stale by construction.
    revalidatePath(BREAKDOWN_PATH);
  }
  return result;
}
