"use server";

// Counts -> whole-pen stage change. Retags every live animal in one shed+partition at once.
//
// Both actions return the API result rather than redirecting, because this flow is a check-then-
// apply conversation inside a drawer: the operator picks a pen, sees what would change, and only
// then commits. A redirect after preview would throw that away.
//
// Everything visible here is backend-owned. These actions forward the operator's picks and carry an
// Idempotency-Key on the commit; they compose no copy, derive no counts, and never compute the
// operational-location label themselves.
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import {
  commitReclassifyShedStage,
  previewReclassifyShedStage,
  type ApiResult,
  type ReclassifyShedStagePreviewResponse,
  type ReclassifyShedStageRequest,
  type ReclassifyShedStageResponse,
} from "@/lib/api/server";

const BREAKDOWN_PATH = "/counts/breakdown";
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function trimmedString(value: unknown, key: string, minLength: number, maxLength: number): string {
  if (typeof value !== "string") {
    throw new Error(`${key} is required`);
  }
  const trimmed = value.trim();
  if (trimmed.length < minLength || trimmed.length > maxLength) {
    throw new Error(`${key} is out of range`);
  }
  return trimmed;
}

function optionalTrimmedString(value: unknown, key: string, minLength: number, maxLength: number): string | undefined {
  if (value == null || value === "") return undefined;
  const trimmed = trimmedString(value, key, minLength, maxLength);
  return trimmed.length === 0 ? undefined : trimmed;
}

function validateReclassifyShedStageRequest(body: unknown): ReclassifyShedStageRequest {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    throw new Error("request body is required");
  }
  const candidate = body as Record<string, unknown>;
  const shedId = trimmedString(candidate.shed_id, "shed_id", 1, 80);
  if (!UUID_RE.test(shedId)) {
    throw new Error("shed_id must be a uuid");
  }
  const managementStage = trimmedString(candidate.management_stage, "management_stage", 1, 80);
  const reason = optionalTrimmedString(candidate.reason, "reason", 3, 500);
  return {
    shed_id: shedId,
    management_stage: managementStage,
    ...(reason ? { reason } : {}),
  };
}

export async function previewShedStageAction(
  body: ReclassifyShedStageRequest,
): Promise<ApiResult<ReclassifyShedStagePreviewResponse>> {
  return previewReclassifyShedStage(validateReclassifyShedStageRequest(body));
}

// The idempotency key is generated by the CALLER (the drawer) and held across retries of the same
// intent, so a double-click or a retried network failure replays the first write instead of
// emitting a second round of stage-change events. Generating it here would defeat that -- every
// retry would arrive as a new key.
export async function commitShedStageAction(
  body: ReclassifyShedStageRequest,
  idempotencyKey: string,
): Promise<ApiResult<ReclassifyShedStageResponse>> {
  const key = typeof idempotencyKey === "string" && idempotencyKey.trim() ? idempotencyKey.trim() : randomUUID();
  const result = await commitReclassifyShedStage(validateReclassifyShedStageRequest(body), key);
  if (result.ok) {
    // The breakdown's stage columns and kid/adult split are now stale by construction.
    revalidatePath(BREAKDOWN_PATH);
  }
  return result;
}
