// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package vaccinationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptVaccinationCompletion = `-- name: AcceptVaccinationCompletion :many
UPDATE vaccination_completions
SET status = 'accepted', verified_by = $1, verified_at = now(),
    withdrawal_until_date = COALESCE($2, withdrawal_until_date),
    row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $3 AND completion_id = $4 AND status = 'recorded'
RETURNING obligation_id::text AS obligation_id,
          goat_id::text AS goat_id,
          COALESCE(batch_id::text, '')::text AS batch_id,
          COALESCE(vaccine_inventory_lot_id::text, '')::text AS vaccine_inventory_lot_id,
          COALESCE(doses, 0)::int AS doses,
          administered_at
`

type AcceptVaccinationCompletionParams struct {
	VerifiedBy          pgtype.UUID
	WithdrawalUntilDate pgtype.Date
	TenantID            pgtype.UUID
	CompletionID        pgtype.UUID
}

type AcceptVaccinationCompletionRow struct {
	ObligationID          string
	GoatID                string
	BatchID               string
	VaccineInventoryLotID string
	Doses                 int32
	AdministeredAt        pgtype.Timestamptz
}

// SM-5 verify (accept). Acts only on a still-recorded row, returning its verification context so the
// caller can complete the obligation + consume stock. Idempotent: an already-accepted/rejected row
// matches nothing → no rows → caller no-ops.
func (q *Queries) AcceptVaccinationCompletion(ctx context.Context, arg AcceptVaccinationCompletionParams) ([]AcceptVaccinationCompletionRow, error) {
	rows, err := q.db.Query(ctx, acceptVaccinationCompletion,
		arg.VerifiedBy,
		arg.WithdrawalUntilDate,
		arg.TenantID,
		arg.CompletionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcceptVaccinationCompletionRow
	for rows.Next() {
		var i AcceptVaccinationCompletionRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.GoatID,
			&i.BatchID,
			&i.VaccineInventoryLotID,
			&i.Doses,
			&i.AdministeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVaccinationCompletion = `-- name: RecordVaccinationCompletion :one
INSERT INTO vaccination_completions (
  tenant_id, obligation_id, batch_id, goat_id, sop_submission_item_id, vaccine_inventory_lot_id,
  doses, dose_ml_given, route_site, adverse_reaction, adverse_reaction_problem_id, cold_chain_verified,
  administered_at, status, withdrawal_until_date, recorded_by, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING completion_id::text AS completion_id
`

type RecordVaccinationCompletionParams struct {
	TenantID                 pgtype.UUID
	ObligationID             pgtype.UUID
	BatchID                  pgtype.UUID
	GoatID                   pgtype.UUID
	SopSubmissionItemID      pgtype.UUID
	VaccineInventoryLotID    pgtype.UUID
	Doses                    pgtype.Int4
	DoseMlGiven              pgtype.Numeric
	RouteSite                pgtype.Text
	AdverseReaction          bool
	AdverseReactionProblemID pgtype.UUID
	ColdChainVerified        bool
	AdministeredAt           pgtype.Timestamptz
	Status                   string
	WithdrawalUntilDate      pgtype.Date
	RecordedBy               pgtype.UUID
	IdempotencyKey           string
}

// Idempotent on (tenant_id, idempotency_key); returns no row on replay.
func (q *Queries) RecordVaccinationCompletion(ctx context.Context, arg RecordVaccinationCompletionParams) (string, error) {
	row := q.db.QueryRow(ctx, recordVaccinationCompletion,
		arg.TenantID,
		arg.ObligationID,
		arg.BatchID,
		arg.GoatID,
		arg.SopSubmissionItemID,
		arg.VaccineInventoryLotID,
		arg.Doses,
		arg.DoseMlGiven,
		arg.RouteSite,
		arg.AdverseReaction,
		arg.AdverseReactionProblemID,
		arg.ColdChainVerified,
		arg.AdministeredAt,
		arg.Status,
		arg.WithdrawalUntilDate,
		arg.RecordedBy,
		arg.IdempotencyKey,
	)
	var completion_id string
	err := row.Scan(&completion_id)
	return completion_id, err
}

const rejectVaccinationCompletion = `-- name: RejectVaccinationCompletion :execrows
UPDATE vaccination_completions
SET status = 'rejected', verified_by = $1, verified_at = now(),
    rejection_reason = $2, row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $3 AND completion_id = $4 AND status = 'recorded'
`

type RejectVaccinationCompletionParams struct {
	VerifiedBy      pgtype.UUID
	RejectionReason pgtype.Text
	TenantID        pgtype.UUID
	CompletionID    pgtype.UUID
}

// SM-5 verify (rework). Acts only on a still-recorded row. Idempotent: returns 0 rows on replay.
func (q *Queries) RejectVaccinationCompletion(ctx context.Context, arg RejectVaccinationCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectVaccinationCompletion,
		arg.VerifiedBy,
		arg.RejectionReason,
		arg.TenantID,
		arg.CompletionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
