// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package vaccinationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastAcceptedCompletionForGoat = `-- name: GetLastAcceptedCompletionForGoat :one
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id, administered_at
FROM vaccination_completions
WHERE tenant_id = $1 AND goat_id = $2 AND status = 'accepted'
ORDER BY administered_at DESC
LIMIT 1
`

type GetLastAcceptedCompletionForGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetLastAcceptedCompletionForGoatRow struct {
	CompletionID   string
	ObligationID   string
	AdministeredAt pgtype.Timestamptz
}

// Next-due / SM-7 basis: most recent accepted administration for a goat.
func (q *Queries) GetLastAcceptedCompletionForGoat(ctx context.Context, arg GetLastAcceptedCompletionForGoatParams) (GetLastAcceptedCompletionForGoatRow, error) {
	row := q.db.QueryRow(ctx, getLastAcceptedCompletionForGoat, arg.TenantID, arg.GoatID)
	var i GetLastAcceptedCompletionForGoatRow
	err := row.Scan(&i.CompletionID, &i.ObligationID, &i.AdministeredAt)
	return i, err
}

const listVaccinationCompletionsByGoat = `-- name: ListVaccinationCompletionsByGoat :many
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id,
       COALESCE(batch_id::text, '')::text AS batch_id, administered_at, status,
       COALESCE(doses, 0)::int AS doses, COALESCE(route_site, '')::text AS route_site,
       adverse_reaction, withdrawal_until_date
FROM vaccination_completions
WHERE tenant_id = $1 AND goat_id = $2
ORDER BY administered_at DESC
LIMIT $3
`

type ListVaccinationCompletionsByGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
	RowLimit int32
}

type ListVaccinationCompletionsByGoatRow struct {
	CompletionID        string
	ObligationID        string
	BatchID             string
	AdministeredAt      pgtype.Timestamptz
	Status              string
	Doses               int32
	RouteSite           string
	AdverseReaction     bool
	WithdrawalUntilDate pgtype.Date
}

// Goat Passport history. Uses vaccination_completions_goat_history_idx (tenant_id, goat_id, administered_at DESC).
func (q *Queries) ListVaccinationCompletionsByGoat(ctx context.Context, arg ListVaccinationCompletionsByGoatParams) ([]ListVaccinationCompletionsByGoatRow, error) {
	rows, err := q.db.Query(ctx, listVaccinationCompletionsByGoat, arg.TenantID, arg.GoatID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaccinationCompletionsByGoatRow
	for rows.Next() {
		var i ListVaccinationCompletionsByGoatRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.BatchID,
			&i.AdministeredAt,
			&i.Status,
			&i.Doses,
			&i.RouteSite,
			&i.AdverseReaction,
			&i.WithdrawalUntilDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
