// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package vaccinationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatchupGoats = `-- name: CountCatchupGoats :one
WITH impact_params AS (
  SELECT $8::int AS warmup_no_vaccination_days,
         $9::timestamptz AS as_of
)
SELECT count(DISTINCT g.goat_id)::bigint AS total
FROM goats g
CROSS JOIN impact_params ip
JOIN vaccination_completions vc
  ON vc.tenant_id = g.tenant_id AND vc.goat_id = g.goat_id AND vc.status = 'accepted'
LEFT JOIN LATERAL (
  SELECT COALESCE(plg.warmup_started_at, plg.intake_accepted_at, g.entry_date::timestamptz) AS warming_entry_at
  FROM procurement_load_goats plg
  WHERE plg.tenant_id = g.tenant_id
    AND plg.goat_id = g.goat_id
  ORDER BY COALESCE(plg.warmup_started_at, plg.intake_accepted_at, plg.created_at) DESC NULLS LAST
  LIMIT 1
) proc ON true
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = COALESCE(g.current_location_id, g.shed_id)
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = g.shed_id
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
WHERE g.tenant_id = $1
  AND g.lifecycle_status = 'alive'
  AND COALESCE(g.health_status, '') NOT IN ('sick', 'under_treatment', 'recovering', 'quarantine', 'icu')
  AND COALESCE(loa.usable_for_vaccination, true)
  AND NOT COALESCE(loa.is_quarantine, false)
  AND NOT COALESCE(loa.is_icu, false)
  AND (
    ip.warmup_no_vaccination_days <= 0
    OR COALESCE(
      proc.warming_entry_at + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of,
      g.entry_date IS NULL OR g.entry_date::timestamptz + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of
    )
  )
  AND ($2::text = '' OR g.species = $2::text)
  AND ($3::text = '' OR COALESCE(asl.stage_code, g.management_stage, '') = $3::text)
  AND ($4::text = '' OR g.sex = $4::text)
  AND ($5::text = '' OR g.breed = $5::text)
  AND ($6::text = '' OR COALESCE(g.health_status, '') = $6::text)
  AND ($7::uuid IS NULL OR g.park_id = $7::uuid)
`

type CountCatchupGoatsParams struct {
	TenantID                pgtype.UUID
	Species                 string
	Stage                   string
	Sex                     string
	Breed                   string
	Health                  string
	ParkID                  pgtype.UUID
	WarmupNoVaccinationDays int32
	AsOf                    pgtype.Timestamptz
}

// Eligible goats that already have an accepted completion (next-due from last accepted, not DOB).
func (q *Queries) CountCatchupGoats(ctx context.Context, arg CountCatchupGoatsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatchupGoats,
		arg.TenantID,
		arg.Species,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
		arg.WarmupNoVaccinationDays,
		arg.AsOf,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countEligibleGoats = `-- name: CountEligibleGoats :one
WITH impact_params AS (
  SELECT $8::int AS warmup_no_vaccination_days,
         $9::timestamptz AS as_of
)
SELECT count(*)::bigint AS total
FROM goats g
CROSS JOIN impact_params ip
LEFT JOIN LATERAL (
  SELECT COALESCE(plg.warmup_started_at, plg.intake_accepted_at, g.entry_date::timestamptz) AS warming_entry_at
  FROM procurement_load_goats plg
  WHERE plg.tenant_id = g.tenant_id
    AND plg.goat_id = g.goat_id
  ORDER BY COALESCE(plg.warmup_started_at, plg.intake_accepted_at, plg.created_at) DESC NULLS LAST
  LIMIT 1
) proc ON true
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = COALESCE(g.current_location_id, g.shed_id)
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = g.shed_id
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
WHERE g.tenant_id = $1
  AND g.lifecycle_status = 'alive'
  AND COALESCE(g.health_status, '') NOT IN ('sick', 'under_treatment', 'recovering', 'quarantine', 'icu')
  AND COALESCE(loa.usable_for_vaccination, true)
  AND NOT COALESCE(loa.is_quarantine, false)
  AND NOT COALESCE(loa.is_icu, false)
  AND (
    ip.warmup_no_vaccination_days <= 0
    OR COALESCE(
      proc.warming_entry_at + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of,
      g.entry_date IS NULL OR g.entry_date::timestamptz + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of
    )
  )
  AND ($2::text = '' OR g.species = $2::text)
  AND ($3::text = '' OR COALESCE(asl.stage_code, g.management_stage, '') = $3::text)
  AND ($4::text = '' OR g.sex = $4::text)
  AND ($5::text = '' OR g.breed = $5::text)
  AND ($6::text = '' OR COALESCE(g.health_status, '') = $6::text)
  AND ($7::uuid IS NULL OR g.park_id = $7::uuid)
`

type CountEligibleGoatsParams struct {
	TenantID                pgtype.UUID
	Species                 string
	Stage                   string
	Sex                     string
	Breed                   string
	Health                  string
	ParkID                  pgtype.UUID
	WarmupNoVaccinationDays int32
	AsOf                    pgtype.Timestamptz
}

// Live impact: in-care goats matching a rule's eligibility dims within an optional park scope.
// Optional text dims use the (” OR col = @x) idiom; park scope via a nullable narg uuid.
func (q *Queries) CountEligibleGoats(ctx context.Context, arg CountEligibleGoatsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleGoats,
		arg.TenantID,
		arg.Species,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
		arg.WarmupNoVaccinationDays,
		arg.AsOf,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countEligibleShedScopes = `-- name: CountEligibleShedScopes :one
WITH impact_params AS (
  SELECT $8::int AS warmup_no_vaccination_days,
         $9::timestamptz AS as_of
)
SELECT count(DISTINCT g.shed_id)::bigint AS total
FROM goats g
CROSS JOIN impact_params ip
LEFT JOIN LATERAL (
  SELECT COALESCE(plg.warmup_started_at, plg.intake_accepted_at, g.entry_date::timestamptz) AS warming_entry_at
  FROM procurement_load_goats plg
  WHERE plg.tenant_id = g.tenant_id
    AND plg.goat_id = g.goat_id
  ORDER BY COALESCE(plg.warmup_started_at, plg.intake_accepted_at, plg.created_at) DESC NULLS LAST
  LIMIT 1
) proc ON true
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = COALESCE(g.current_location_id, g.shed_id)
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = g.shed_id
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
WHERE g.tenant_id = $1
  AND g.lifecycle_status = 'alive'
  AND COALESCE(g.health_status, '') NOT IN ('sick', 'under_treatment', 'recovering', 'quarantine', 'icu')
  AND COALESCE(loa.usable_for_vaccination, true)
  AND NOT COALESCE(loa.is_quarantine, false)
  AND NOT COALESCE(loa.is_icu, false)
  AND (
    ip.warmup_no_vaccination_days <= 0
    OR COALESCE(
      proc.warming_entry_at + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of,
      g.entry_date IS NULL OR g.entry_date::timestamptz + (ip.warmup_no_vaccination_days * INTERVAL '1 day') <= ip.as_of
    )
  )
  AND g.shed_id IS NOT NULL
  AND ($2::text = '' OR g.species = $2::text)
  AND ($3::text = '' OR COALESCE(asl.stage_code, g.management_stage, '') = $3::text)
  AND ($4::text = '' OR g.sex = $4::text)
  AND ($5::text = '' OR g.breed = $5::text)
  AND ($6::text = '' OR COALESCE(g.health_status, '') = $6::text)
  AND ($7::uuid IS NULL OR g.park_id = $7::uuid)
`

type CountEligibleShedScopesParams struct {
	TenantID                pgtype.UUID
	Species                 string
	Stage                   string
	Sex                     string
	Breed                   string
	Health                  string
	ParkID                  pgtype.UUID
	WarmupNoVaccinationDays int32
	AsOf                    pgtype.Timestamptz
}

// Estimated drive batches = distinct sheds holding eligible goats (one shed drive per shed).
func (q *Queries) CountEligibleShedScopes(ctx context.Context, arg CountEligibleShedScopesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleShedScopes,
		arg.TenantID,
		arg.Species,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
		arg.WarmupNoVaccinationDays,
		arg.AsOf,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRecordedCompletions = `-- name: CountRecordedCompletions :one
SELECT COUNT(*)::bigint
FROM vaccination_completions vc
LEFT JOIN goats g ON g.tenant_id = vc.tenant_id AND g.goat_id = vc.goat_id
WHERE vc.tenant_id = $1
  AND vc.status = 'recorded'
  AND ($2::uuid IS NULL OR g.park_id = $2::uuid)
`

type CountRecordedCompletionsParams struct {
	TenantID pgtype.UUID
	ParkID   pgtype.UUID
}

// Verification queue total for the current tenant/park filter. Exact total_count must stay honest even
// when the client is reading a later cursor page.
func (q *Queries) CountRecordedCompletions(ctx context.Context, arg CountRecordedCompletionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordedCompletions, arg.TenantID, arg.ParkID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAcceptableVaccinationCompletion = `-- name: GetAcceptableVaccinationCompletion :one
SELECT completion_id::text AS completion_id,
       status,
       obligation_id::text AS obligation_id,
       goat_id::text AS goat_id,
       COALESCE(batch_id::text, '')::text AS batch_id,
       COALESCE(vaccine_inventory_lot_id::text, '')::text AS vaccine_inventory_lot_id,
       COALESCE(doses, 0)::int AS doses,
       administered_at
FROM vaccination_completions
WHERE tenant_id = $1
  AND completion_id = $2
  AND status IN ('recorded', 'accepted')
`

type GetAcceptableVaccinationCompletionParams struct {
	TenantID     pgtype.UUID
	CompletionID pgtype.UUID
}

type GetAcceptableVaccinationCompletionRow struct {
	CompletionID          string
	Status                string
	ObligationID          string
	GoatID                string
	BatchID               string
	VaccineInventoryLotID string
	Doses                 int32
	AdministeredAt        pgtype.Timestamptz
}

// Recovery/resume read for SM-5: a retry after the completion row was already accepted must still
// be able to finish idempotent side effects such as obligation completion, stock consumption, and
// booster scheduling.
func (q *Queries) GetAcceptableVaccinationCompletion(ctx context.Context, arg GetAcceptableVaccinationCompletionParams) (GetAcceptableVaccinationCompletionRow, error) {
	row := q.db.QueryRow(ctx, getAcceptableVaccinationCompletion, arg.TenantID, arg.CompletionID)
	var i GetAcceptableVaccinationCompletionRow
	err := row.Scan(
		&i.CompletionID,
		&i.Status,
		&i.ObligationID,
		&i.GoatID,
		&i.BatchID,
		&i.VaccineInventoryLotID,
		&i.Doses,
		&i.AdministeredAt,
	)
	return i, err
}

const getAcceptableVaccinationCompletionByIdempotency = `-- name: GetAcceptableVaccinationCompletionByIdempotency :one
SELECT completion_id::text AS completion_id,
       status,
       obligation_id::text AS obligation_id,
       goat_id::text AS goat_id,
       COALESCE(batch_id::text, '')::text AS batch_id,
       COALESCE(vaccine_inventory_lot_id::text, '')::text AS vaccine_inventory_lot_id,
       COALESCE(doses, 0)::int AS doses,
       administered_at
FROM vaccination_completions
WHERE tenant_id = $1
  AND idempotency_key = $2
  AND status IN ('recorded', 'accepted', 'rejected')
`

type GetAcceptableVaccinationCompletionByIdempotencyParams struct {
	TenantID       pgtype.UUID
	IdempotencyKey string
}

type GetAcceptableVaccinationCompletionByIdempotencyRow struct {
	CompletionID          string
	Status                string
	ObligationID          string
	GoatID                string
	BatchID               string
	VaccineInventoryLotID string
	Doses                 int32
	AdministeredAt        pgtype.Timestamptz
}

// Direct Accept recovery: if the record step succeeded but a later side effect failed, the same
// idempotency key must resume the existing completion instead of no-oping.
func (q *Queries) GetAcceptableVaccinationCompletionByIdempotency(ctx context.Context, arg GetAcceptableVaccinationCompletionByIdempotencyParams) (GetAcceptableVaccinationCompletionByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getAcceptableVaccinationCompletionByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i GetAcceptableVaccinationCompletionByIdempotencyRow
	err := row.Scan(
		&i.CompletionID,
		&i.Status,
		&i.ObligationID,
		&i.GoatID,
		&i.BatchID,
		&i.VaccineInventoryLotID,
		&i.Doses,
		&i.AdministeredAt,
	)
	return i, err
}

const getGoatForGeneration = `-- name: GetGoatForGeneration :one
SELECT g.goat_id::text AS goat_id, g.dob, g.entry_date, g.breeding_date, g.last_delivery_date, g.lifecycle_status,
       COALESCE(g.health_status, '')::text AS health_status,
       COALESCE(g.reproductive_status, '')::text AS reproductive_status,
       COALESCE(g.species, 'goat')::text AS species,
       COALESCE(g.origin_type, '')::text AS origin_type,
       COALESCE(proc.procurement_purpose, '')::text AS procurement_purpose,
       proc.warming_entry_at,
       COALESCE(shed.location_id::text, '')::text AS shed_id,
       COALESCE(park.location_id::text, '')::text AS park_id,
       COALESCE(gsp.partition_label, '')::text AS partition_label,
       COALESCE(g.sex, '')::text AS sex,
       COALESCE(g.breed, '')::text AS breed,
       COALESCE(asl.stage_code, g.management_stage, '')::text AS management_stage,
       COALESCE(g.age_band, '')::text AS age_band,
       COALESCE(loa.is_quarantine, false)::boolean AS location_is_quarantine,
       COALESCE(loa.is_icu, false)::boolean AS location_is_icu
FROM goats g
LEFT JOIN LATERAL (
  SELECT plg.purpose AS procurement_purpose,
         COALESCE(plg.warmup_started_at, plg.intake_accepted_at, g.entry_date::timestamptz) AS warming_entry_at
  FROM procurement_load_goats plg
  WHERE plg.tenant_id = g.tenant_id
    AND plg.goat_id = g.goat_id
  ORDER BY COALESCE(plg.warmup_started_at, plg.intake_accepted_at, plg.created_at) DESC NULLS LAST
  LIMIT 1
) proc ON true
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = COALESCE(g.current_location_id, g.shed_id)
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = g.shed_id
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
LEFT JOIN locations shed
  ON shed.tenant_id = g.tenant_id
 AND shed.location_id = g.shed_id
 AND shed.location_type = 'shed'
LEFT JOIN locations park
  ON park.tenant_id = g.tenant_id
 AND park.location_id = g.park_id
 AND park.location_type = 'park'
LEFT JOIN goat_shed_partitions gsp
  ON gsp.tenant_id = g.tenant_id
 AND gsp.goat_id = g.goat_id
WHERE g.tenant_id = $1 AND g.goat_id = $2::uuid
`

type GetGoatForGenerationParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetGoatForGenerationRow struct {
	GoatID               string
	Dob                  pgtype.Date
	EntryDate            pgtype.Date
	BreedingDate         pgtype.Date
	LastDeliveryDate     pgtype.Date
	LifecycleStatus      string
	HealthStatus         string
	ReproductiveStatus   string
	Species              string
	OriginType           string
	ProcurementPurpose   string
	WarmingEntryAt       pgtype.Timestamptz
	ShedID               string
	ParkID               string
	PartitionLabel       string
	Sex                  string
	Breed                string
	ManagementStage      string
	AgeBand              string
	LocationIsQuarantine bool
	LocationIsIcu        bool
}

// Single-goat generation fields (incl sex/breed/stage for Go-side eligibility match on goat.created).
func (q *Queries) GetGoatForGeneration(ctx context.Context, arg GetGoatForGenerationParams) (GetGoatForGenerationRow, error) {
	row := q.db.QueryRow(ctx, getGoatForGeneration, arg.TenantID, arg.GoatID)
	var i GetGoatForGenerationRow
	err := row.Scan(
		&i.GoatID,
		&i.Dob,
		&i.EntryDate,
		&i.BreedingDate,
		&i.LastDeliveryDate,
		&i.LifecycleStatus,
		&i.HealthStatus,
		&i.ReproductiveStatus,
		&i.Species,
		&i.OriginType,
		&i.ProcurementPurpose,
		&i.WarmingEntryAt,
		&i.ShedID,
		&i.ParkID,
		&i.PartitionLabel,
		&i.Sex,
		&i.Breed,
		&i.ManagementStage,
		&i.AgeBand,
		&i.LocationIsQuarantine,
		&i.LocationIsIcu,
	)
	return i, err
}

const getLastAcceptedCompletionForGoat = `-- name: GetLastAcceptedCompletionForGoat :one
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id, administered_at
FROM vaccination_completions
WHERE tenant_id = $1 AND goat_id = $2 AND status = 'accepted'
ORDER BY administered_at DESC
LIMIT 1
`

type GetLastAcceptedCompletionForGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetLastAcceptedCompletionForGoatRow struct {
	CompletionID   string
	ObligationID   string
	AdministeredAt pgtype.Timestamptz
}

// Next-due / SM-7 basis: most recent accepted administration for a goat.
func (q *Queries) GetLastAcceptedCompletionForGoat(ctx context.Context, arg GetLastAcceptedCompletionForGoatParams) (GetLastAcceptedCompletionForGoatRow, error) {
	row := q.db.QueryRow(ctx, getLastAcceptedCompletionForGoat, arg.TenantID, arg.GoatID)
	var i GetLastAcceptedCompletionForGoatRow
	err := row.Scan(&i.CompletionID, &i.ObligationID, &i.AdministeredAt)
	return i, err
}

const getRecordedVaccinationCompletion = `-- name: GetRecordedVaccinationCompletion :one
SELECT obligation_id::text AS obligation_id,
       goat_id::text AS goat_id,
       COALESCE(batch_id::text, '')::text AS batch_id,
       COALESCE(vaccine_inventory_lot_id::text, '')::text AS vaccine_inventory_lot_id,
       COALESCE(doses, 0)::int AS doses,
       administered_at
FROM vaccination_completions
WHERE tenant_id = $1
  AND completion_id = $2
  AND status = 'recorded'
`

type GetRecordedVaccinationCompletionParams struct {
	TenantID     pgtype.UUID
	CompletionID pgtype.UUID
}

type GetRecordedVaccinationCompletionRow struct {
	ObligationID          string
	GoatID                string
	BatchID               string
	VaccineInventoryLotID string
	Doses                 int32
	AdministeredAt        pgtype.Timestamptz
}

// Verification preflight: read the stock/obligation context while the completion is still pending
// review, so stock consumption can happen before the row flips to accepted.
func (q *Queries) GetRecordedVaccinationCompletion(ctx context.Context, arg GetRecordedVaccinationCompletionParams) (GetRecordedVaccinationCompletionRow, error) {
	row := q.db.QueryRow(ctx, getRecordedVaccinationCompletion, arg.TenantID, arg.CompletionID)
	var i GetRecordedVaccinationCompletionRow
	err := row.Scan(
		&i.ObligationID,
		&i.GoatID,
		&i.BatchID,
		&i.VaccineInventoryLotID,
		&i.Doses,
		&i.AdministeredAt,
	)
	return i, err
}

const listEligibleGoatsForGeneration = `-- name: ListEligibleGoatsForGeneration :many
SELECT g.goat_id::text AS goat_id, g.dob, g.entry_date, g.breeding_date, g.last_delivery_date, g.lifecycle_status,
       COALESCE(g.health_status, '')::text AS health_status,
       COALESCE(g.reproductive_status, '')::text AS reproductive_status,
       COALESCE(g.species, 'goat')::text AS species,
       COALESCE(g.origin_type, '')::text AS origin_type,
       COALESCE(proc.procurement_purpose, '')::text AS procurement_purpose,
       proc.warming_entry_at,
       COALESCE(shed.location_id::text, '')::text AS shed_id,
       COALESCE(park.location_id::text, '')::text AS park_id,
       COALESCE(gsp.partition_label, '')::text AS partition_label,
       COALESCE(g.sex, '')::text AS sex,
       COALESCE(g.breed, '')::text AS breed,
       COALESCE(asl.stage_code, g.management_stage, '')::text AS management_stage,
       COALESCE(g.age_band, '')::text AS age_band,
       COALESCE(loa.is_quarantine, false)::boolean AS location_is_quarantine,
       COALESCE(loa.is_icu, false)::boolean AS location_is_icu
FROM goats g
LEFT JOIN LATERAL (
  SELECT plg.purpose AS procurement_purpose,
         COALESCE(plg.warmup_started_at, plg.intake_accepted_at, g.entry_date::timestamptz) AS warming_entry_at
  FROM procurement_load_goats plg
  WHERE plg.tenant_id = g.tenant_id
    AND plg.goat_id = g.goat_id
  ORDER BY COALESCE(plg.warmup_started_at, plg.intake_accepted_at, plg.created_at) DESC NULLS LAST
  LIMIT 1
) proc ON true
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = COALESCE(g.current_location_id, g.shed_id)
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = g.shed_id
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
LEFT JOIN locations shed
  ON shed.tenant_id = g.tenant_id
 AND shed.location_id = g.shed_id
 AND shed.location_type = 'shed'
LEFT JOIN locations park
  ON park.tenant_id = g.tenant_id
 AND park.location_id = g.park_id
 AND park.location_type = 'park'
LEFT JOIN goat_shed_partitions gsp
  ON gsp.tenant_id = g.tenant_id
 AND gsp.goat_id = g.goat_id
WHERE g.tenant_id = $1
  AND g.lifecycle_status IN ('alive', 'sick', 'under_treatment', 'quarantine', 'icu')
  AND ($2::text = '' OR COALESCE(asl.stage_code, g.management_stage, '') = $2::text)
  AND ($3::text = '' OR g.sex = $3::text)
  AND ($4::text = '' OR g.breed = $4::text)
  AND ($5::text = '' OR COALESCE(g.health_status, '') = $5::text)
  AND ($6::uuid IS NULL OR g.park_id = $6::uuid)
  AND g.goat_id > $7::uuid
ORDER BY g.goat_id
LIMIT $8
`

type ListEligibleGoatsForGenerationParams struct {
	TenantID    pgtype.UUID
	Stage       string
	Sex         string
	Breed       string
	Health      string
	ParkID      pgtype.UUID
	AfterGoatID pgtype.UUID
	RowLimit    int32
}

type ListEligibleGoatsForGenerationRow struct {
	GoatID               string
	Dob                  pgtype.Date
	EntryDate            pgtype.Date
	BreedingDate         pgtype.Date
	LastDeliveryDate     pgtype.Date
	LifecycleStatus      string
	HealthStatus         string
	ReproductiveStatus   string
	Species              string
	OriginType           string
	ProcurementPurpose   string
	WarmingEntryAt       pgtype.Timestamptz
	ShedID               string
	ParkID               string
	PartitionLabel       string
	Sex                  string
	Breed                string
	ManagementStage      string
	AgeBand              string
	LocationIsQuarantine bool
	LocationIsIcu        bool
}

// Chunked (keyset) listing of the in-care cohort for SM-1 generation. Cursor by goat_id over the
// (tenant_id, goat_id) unique index. Includes defer-state goats (icu/quarantine/sick) so the
// handler can write a canonical deferred obligation rather than silently skipping them.
func (q *Queries) ListEligibleGoatsForGeneration(ctx context.Context, arg ListEligibleGoatsForGenerationParams) ([]ListEligibleGoatsForGenerationRow, error) {
	rows, err := q.db.Query(ctx, listEligibleGoatsForGeneration,
		arg.TenantID,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
		arg.AfterGoatID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleGoatsForGenerationRow
	for rows.Next() {
		var i ListEligibleGoatsForGenerationRow
		if err := rows.Scan(
			&i.GoatID,
			&i.Dob,
			&i.EntryDate,
			&i.BreedingDate,
			&i.LastDeliveryDate,
			&i.LifecycleStatus,
			&i.HealthStatus,
			&i.ReproductiveStatus,
			&i.Species,
			&i.OriginType,
			&i.ProcurementPurpose,
			&i.WarmingEntryAt,
			&i.ShedID,
			&i.ParkID,
			&i.PartitionLabel,
			&i.Sex,
			&i.Breed,
			&i.ManagementStage,
			&i.AgeBand,
			&i.LocationIsQuarantine,
			&i.LocationIsIcu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedCompletions = `-- name: ListRecordedCompletions :many
SELECT vc.completion_id::text AS completion_id, vc.obligation_id::text AS obligation_id,
       vc.goat_id::text AS goat_id, COALESCE(vc.batch_id::text, '')::text AS batch_id,
       COALESCE(st.task_id::text, '')::text AS sop_task_id,
       COALESCE(st.row_version, 0)::int AS sop_task_row_version,
       vc.administered_at, COALESCE(vc.doses, 0)::int AS doses, COALESCE(vc.route_site, '')::text AS route_site
FROM vaccination_completions vc
LEFT JOIN goats g ON g.tenant_id = vc.tenant_id AND g.goat_id = vc.goat_id
LEFT JOIN sop_submission_items si
  ON si.tenant_id = vc.tenant_id AND si.item_id = vc.sop_submission_item_id
LEFT JOIN sop_submissions ss
  ON ss.tenant_id = si.tenant_id AND ss.submission_id = si.submission_id
LEFT JOIN sop_tasks st
  ON st.tenant_id = ss.tenant_id AND st.task_id = ss.task_id
WHERE vc.tenant_id = $1 AND vc.status = 'recorded'
  AND ($2::uuid IS NULL OR g.park_id = $2::uuid)
  AND (
    $3::timestamptz IS NULL
    OR (vc.administered_at, vc.completion_id) > ($3::timestamptz, $4::uuid)
  )
ORDER BY vc.administered_at ASC, vc.completion_id ASC
LIMIT $5
`

type ListRecordedCompletionsParams struct {
	TenantID             pgtype.UUID
	ParkID               pgtype.UUID
	CursorAdministeredAt pgtype.Timestamptz
	CursorCompletionID   pgtype.UUID
	RowLimitPlusOne      int32
}

type ListRecordedCompletionsRow struct {
	CompletionID      string
	ObligationID      string
	GoatID            string
	BatchID           string
	SopTaskID         string
	SopTaskRowVersion int32
	AdministeredAt    pgtype.Timestamptz
	Doses             int32
	RouteSite         string
}

// Verification queue: completions awaiting review (status='recorded'), earliest administered first.
// Uses vaccination_completions_review_idx (tenant_id, administered_at) WHERE status='recorded'. The
// optional park_id scope filters by the completed goat's park so the top-bar park scope reaches the queue.
func (q *Queries) ListRecordedCompletions(ctx context.Context, arg ListRecordedCompletionsParams) ([]ListRecordedCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listRecordedCompletions,
		arg.TenantID,
		arg.ParkID,
		arg.CursorAdministeredAt,
		arg.CursorCompletionID,
		arg.RowLimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordedCompletionsRow
	for rows.Next() {
		var i ListRecordedCompletionsRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.GoatID,
			&i.BatchID,
			&i.SopTaskID,
			&i.SopTaskRowVersion,
			&i.AdministeredAt,
			&i.Doses,
			&i.RouteSite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedCompletionsByTask = `-- name: ListRecordedCompletionsByTask :many
SELECT c.completion_id::text AS completion_id
FROM vaccination_completions c
JOIN sop_submission_items i ON i.tenant_id = c.tenant_id AND i.item_id = c.sop_submission_item_id
JOIN sop_submissions s ON s.tenant_id = i.tenant_id AND s.submission_id = i.submission_id
WHERE c.tenant_id = $1 AND s.task_id = $2 AND c.status = 'recorded'
  AND c.sop_submission_item_id IS NOT NULL
ORDER BY c.completion_id
`

type ListRecordedCompletionsByTaskParams struct {
	TenantID pgtype.UUID
	TaskID   pgtype.UUID
}

// SOP verify fan-out: the still-recorded vaccination completions captured under a SOP task's
// submissions, so a task-level verify/rework can be applied per completion. Drives from the task's
// submissions (sop_submissions_task_history_idx) -> items (sop_submission_items_submission_idx) ->
// completions (vaccination_completions_submission_item_idx).
func (q *Queries) ListRecordedCompletionsByTask(ctx context.Context, arg ListRecordedCompletionsByTaskParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRecordedCompletionsByTask, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var completion_id string
		if err := rows.Scan(&completion_id); err != nil {
			return nil, err
		}
		items = append(items, completion_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaccinationCompletionsByGoat = `-- name: ListVaccinationCompletionsByGoat :many
SELECT vc.completion_id::text AS completion_id, vc.obligation_id::text AS obligation_id,
       COALESCE(vc.batch_id::text, '')::text AS batch_id, vc.administered_at, vc.status,
       COALESCE(vc.doses, 0)::int AS doses, COALESCE(vc.route_site, '')::text AS route_site,
       COALESCE(pr.dose_code, '')::text AS dose_code,
       COALESCE(NULLIF(pr.eligibility_json -> 'vaccine' ->> 'display_name', ''), NULLIF(prd.vaccine_code, ''), NULLIF(pr.dose_code, ''), '')::text AS vaccine_label,
       vc.adverse_reaction, vc.withdrawal_until_date
FROM vaccination_completions vc
LEFT JOIN obligation_instances oi
  ON oi.tenant_id = vc.tenant_id
 AND oi.obligation_id = vc.obligation_id
LEFT JOIN protocol_rules pr
  ON pr.tenant_id = oi.tenant_id
 AND pr.rule_id = oi.rule_id
LEFT JOIN LATERAL (
  SELECT vaccine_code
  FROM protocol_rule_dimensions dim
  WHERE dim.tenant_id = pr.tenant_id
    AND dim.rule_id = pr.rule_id
  ORDER BY NULLIF(dim.vaccine_code, '') NULLS LAST, dim.protocol_rule_dimension_id
  LIMIT 1
) prd ON true
WHERE vc.tenant_id = $1 AND vc.goat_id = $2
ORDER BY vc.administered_at DESC
LIMIT $3
`

type ListVaccinationCompletionsByGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
	RowLimit int32
}

type ListVaccinationCompletionsByGoatRow struct {
	CompletionID        string
	ObligationID        string
	BatchID             string
	AdministeredAt      pgtype.Timestamptz
	Status              string
	Doses               int32
	RouteSite           string
	DoseCode            string
	VaccineLabel        string
	AdverseReaction     bool
	WithdrawalUntilDate pgtype.Date
}

// Goat Passport history. Uses vaccination_completions_goat_history_idx (tenant_id, goat_id, administered_at DESC).
func (q *Queries) ListVaccinationCompletionsByGoat(ctx context.Context, arg ListVaccinationCompletionsByGoatParams) ([]ListVaccinationCompletionsByGoatRow, error) {
	rows, err := q.db.Query(ctx, listVaccinationCompletionsByGoat, arg.TenantID, arg.GoatID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaccinationCompletionsByGoatRow
	for rows.Next() {
		var i ListVaccinationCompletionsByGoatRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.BatchID,
			&i.AdministeredAt,
			&i.Status,
			&i.Doses,
			&i.RouteSite,
			&i.DoseCode,
			&i.VaccineLabel,
			&i.AdverseReaction,
			&i.WithdrawalUntilDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAvailableStockForItem = `-- name: SumAvailableStockForItem :one
SELECT COALESCE(SUM(quantity_in_stock - quantity_reserved), 0)::numeric AS available,
       MIN(expiry_date)::date AS earliest_expiry
FROM inventory_stock
WHERE tenant_id = $1
  AND item_id = $2
  AND quantity_in_stock > quantity_reserved
  AND status = 'active'
  AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE)
  AND ($3::uuid IS NULL OR location_id = $3::uuid)
`

type SumAvailableStockForItemParams struct {
	TenantID   pgtype.UUID
	ItemID     pgtype.UUID
	LocationID pgtype.UUID
}

type SumAvailableStockForItemRow struct {
	Available      pgtype.Numeric
	EarliestExpiry pgtype.Date
}

// Available (unreserved) doses for the vaccine item + earliest expiry, within an optional location.
func (q *Queries) SumAvailableStockForItem(ctx context.Context, arg SumAvailableStockForItemParams) (SumAvailableStockForItemRow, error) {
	row := q.db.QueryRow(ctx, sumAvailableStockForItem, arg.TenantID, arg.ItemID, arg.LocationID)
	var i SumAvailableStockForItemRow
	err := row.Scan(&i.Available, &i.EarliestExpiry)
	return i, err
}
