// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package vaccinationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatchupGoats = `-- name: CountCatchupGoats :one
SELECT count(DISTINCT g.goat_id)::bigint AS total
FROM goats g
JOIN vaccination_completions vc
  ON vc.tenant_id = g.tenant_id AND vc.goat_id = g.goat_id AND vc.status = 'accepted'
WHERE g.tenant_id = $1
  AND g.lifecycle_status = 'alive'
  AND ($2::text = '' OR g.management_stage = $2::text)
  AND ($3::text = '' OR g.sex = $3::text)
  AND ($4::text = '' OR g.breed = $4::text)
  AND ($5::text = '' OR COALESCE(g.health_status, '') = $5::text)
  AND ($6::uuid IS NULL OR g.park_id = $6::uuid)
`

type CountCatchupGoatsParams struct {
	TenantID pgtype.UUID
	Stage    string
	Sex      string
	Breed    string
	Health   string
	ParkID   pgtype.UUID
}

// Eligible goats that already have an accepted completion (next-due from last accepted, not DOB).
func (q *Queries) CountCatchupGoats(ctx context.Context, arg CountCatchupGoatsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatchupGoats,
		arg.TenantID,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countEligibleGoats = `-- name: CountEligibleGoats :one
SELECT count(*)::bigint AS total
FROM goats
WHERE tenant_id = $1
  AND lifecycle_status = 'alive'
  AND ($2::text = '' OR management_stage = $2::text)
  AND ($3::text = '' OR sex = $3::text)
  AND ($4::text = '' OR breed = $4::text)
  AND ($5::text = '' OR COALESCE(health_status, '') = $5::text)
  AND ($6::uuid IS NULL OR park_id = $6::uuid)
`

type CountEligibleGoatsParams struct {
	TenantID pgtype.UUID
	Stage    string
	Sex      string
	Breed    string
	Health   string
	ParkID   pgtype.UUID
}

// Live impact: alive goats matching a rule's eligibility dims within an optional park scope.
// Optional text dims use the (” OR col = @x) idiom; park scope via a nullable narg uuid.
func (q *Queries) CountEligibleGoats(ctx context.Context, arg CountEligibleGoatsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleGoats,
		arg.TenantID,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countEligibleShedScopes = `-- name: CountEligibleShedScopes :one
SELECT count(DISTINCT shed_id)::bigint AS total
FROM goats
WHERE tenant_id = $1
  AND lifecycle_status = 'alive'
  AND shed_id IS NOT NULL
  AND ($2::text = '' OR management_stage = $2::text)
  AND ($3::text = '' OR sex = $3::text)
  AND ($4::text = '' OR breed = $4::text)
  AND ($5::text = '' OR COALESCE(health_status, '') = $5::text)
  AND ($6::uuid IS NULL OR park_id = $6::uuid)
`

type CountEligibleShedScopesParams struct {
	TenantID pgtype.UUID
	Stage    string
	Sex      string
	Breed    string
	Health   string
	ParkID   pgtype.UUID
}

// Estimated drive batches = distinct sheds holding eligible goats (one shed drive per shed).
func (q *Queries) CountEligibleShedScopes(ctx context.Context, arg CountEligibleShedScopesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleShedScopes,
		arg.TenantID,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.Health,
		arg.ParkID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getGoatForGeneration = `-- name: GetGoatForGeneration :one
SELECT goat_id::text AS goat_id, dob, entry_date, lifecycle_status,
       COALESCE(shed_id::text, '')::text AS shed_id,
       COALESCE(park_id::text, '')::text AS park_id,
       COALESCE(sex, '')::text AS sex,
       COALESCE(breed, '')::text AS breed,
       COALESCE(management_stage, '')::text AS management_stage
FROM goats
WHERE tenant_id = $1 AND goat_id = $2::uuid
`

type GetGoatForGenerationParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetGoatForGenerationRow struct {
	GoatID          string
	Dob             pgtype.Date
	EntryDate       pgtype.Date
	LifecycleStatus string
	ShedID          string
	ParkID          string
	Sex             string
	Breed           string
	ManagementStage string
}

// Single-goat generation fields (incl sex/breed/stage for Go-side eligibility match on goat.created).
func (q *Queries) GetGoatForGeneration(ctx context.Context, arg GetGoatForGenerationParams) (GetGoatForGenerationRow, error) {
	row := q.db.QueryRow(ctx, getGoatForGeneration, arg.TenantID, arg.GoatID)
	var i GetGoatForGenerationRow
	err := row.Scan(
		&i.GoatID,
		&i.Dob,
		&i.EntryDate,
		&i.LifecycleStatus,
		&i.ShedID,
		&i.ParkID,
		&i.Sex,
		&i.Breed,
		&i.ManagementStage,
	)
	return i, err
}

const getLastAcceptedCompletionForGoat = `-- name: GetLastAcceptedCompletionForGoat :one
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id, administered_at
FROM vaccination_completions
WHERE tenant_id = $1 AND goat_id = $2 AND status = 'accepted'
ORDER BY administered_at DESC
LIMIT 1
`

type GetLastAcceptedCompletionForGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
}

type GetLastAcceptedCompletionForGoatRow struct {
	CompletionID   string
	ObligationID   string
	AdministeredAt pgtype.Timestamptz
}

// Next-due / SM-7 basis: most recent accepted administration for a goat.
func (q *Queries) GetLastAcceptedCompletionForGoat(ctx context.Context, arg GetLastAcceptedCompletionForGoatParams) (GetLastAcceptedCompletionForGoatRow, error) {
	row := q.db.QueryRow(ctx, getLastAcceptedCompletionForGoat, arg.TenantID, arg.GoatID)
	var i GetLastAcceptedCompletionForGoatRow
	err := row.Scan(&i.CompletionID, &i.ObligationID, &i.AdministeredAt)
	return i, err
}

const listEligibleGoatsForGeneration = `-- name: ListEligibleGoatsForGeneration :many
SELECT goat_id::text AS goat_id, dob, entry_date, lifecycle_status,
       COALESCE(shed_id::text, '')::text AS shed_id,
       COALESCE(park_id::text, '')::text AS park_id
FROM goats
WHERE tenant_id = $1
  AND lifecycle_status IN ('alive', 'sick', 'under_treatment', 'quarantine', 'icu')
  AND ($2::text = '' OR management_stage = $2::text)
  AND ($3::text = '' OR sex = $3::text)
  AND ($4::text = '' OR breed = $4::text)
  AND ($5::uuid IS NULL OR park_id = $5::uuid)
  AND goat_id > $6::uuid
ORDER BY goat_id
LIMIT $7
`

type ListEligibleGoatsForGenerationParams struct {
	TenantID    pgtype.UUID
	Stage       string
	Sex         string
	Breed       string
	ParkID      pgtype.UUID
	AfterGoatID pgtype.UUID
	RowLimit    int32
}

type ListEligibleGoatsForGenerationRow struct {
	GoatID          string
	Dob             pgtype.Date
	EntryDate       pgtype.Date
	LifecycleStatus string
	ShedID          string
	ParkID          string
}

// Chunked (keyset) listing of the in-care cohort for SM-1 generation. Cursor by goat_id over the
// (tenant_id, goat_id) unique index. Includes defer-state goats (icu/quarantine/sick) so the
// handler can emit a visible deferred obligation rather than silently skipping them.
func (q *Queries) ListEligibleGoatsForGeneration(ctx context.Context, arg ListEligibleGoatsForGenerationParams) ([]ListEligibleGoatsForGenerationRow, error) {
	rows, err := q.db.Query(ctx, listEligibleGoatsForGeneration,
		arg.TenantID,
		arg.Stage,
		arg.Sex,
		arg.Breed,
		arg.ParkID,
		arg.AfterGoatID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleGoatsForGenerationRow
	for rows.Next() {
		var i ListEligibleGoatsForGenerationRow
		if err := rows.Scan(
			&i.GoatID,
			&i.Dob,
			&i.EntryDate,
			&i.LifecycleStatus,
			&i.ShedID,
			&i.ParkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaccinationCompletionsByGoat = `-- name: ListVaccinationCompletionsByGoat :many
SELECT completion_id::text AS completion_id, obligation_id::text AS obligation_id,
       COALESCE(batch_id::text, '')::text AS batch_id, administered_at, status,
       COALESCE(doses, 0)::int AS doses, COALESCE(route_site, '')::text AS route_site,
       adverse_reaction, withdrawal_until_date
FROM vaccination_completions
WHERE tenant_id = $1 AND goat_id = $2
ORDER BY administered_at DESC
LIMIT $3
`

type ListVaccinationCompletionsByGoatParams struct {
	TenantID pgtype.UUID
	GoatID   pgtype.UUID
	RowLimit int32
}

type ListVaccinationCompletionsByGoatRow struct {
	CompletionID        string
	ObligationID        string
	BatchID             string
	AdministeredAt      pgtype.Timestamptz
	Status              string
	Doses               int32
	RouteSite           string
	AdverseReaction     bool
	WithdrawalUntilDate pgtype.Date
}

// Goat Passport history. Uses vaccination_completions_goat_history_idx (tenant_id, goat_id, administered_at DESC).
func (q *Queries) ListVaccinationCompletionsByGoat(ctx context.Context, arg ListVaccinationCompletionsByGoatParams) ([]ListVaccinationCompletionsByGoatRow, error) {
	rows, err := q.db.Query(ctx, listVaccinationCompletionsByGoat, arg.TenantID, arg.GoatID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaccinationCompletionsByGoatRow
	for rows.Next() {
		var i ListVaccinationCompletionsByGoatRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.ObligationID,
			&i.BatchID,
			&i.AdministeredAt,
			&i.Status,
			&i.Doses,
			&i.RouteSite,
			&i.AdverseReaction,
			&i.WithdrawalUntilDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAvailableStockForItem = `-- name: SumAvailableStockForItem :one
SELECT COALESCE(SUM(quantity_in_stock - quantity_reserved), 0)::numeric AS available,
       MIN(expiry_date)::date AS earliest_expiry
FROM inventory_stock
WHERE tenant_id = $1
  AND item_id = $2
  AND quantity_in_stock > quantity_reserved
  AND ($3::uuid IS NULL OR location_id = $3::uuid)
`

type SumAvailableStockForItemParams struct {
	TenantID   pgtype.UUID
	ItemID     pgtype.UUID
	LocationID pgtype.UUID
}

type SumAvailableStockForItemRow struct {
	Available      pgtype.Numeric
	EarliestExpiry pgtype.Date
}

// Available (unreserved) doses for the vaccine item + earliest expiry, within an optional location.
func (q *Queries) SumAvailableStockForItem(ctx context.Context, arg SumAvailableStockForItemParams) (SumAvailableStockForItemRow, error) {
	row := q.db.QueryRow(ctx, sumAvailableStockForItem, arg.TenantID, arg.ItemID, arg.LocationID)
	var i SumAvailableStockForItemRow
	err := row.Scan(&i.Available, &i.EarliestExpiry)
	return i, err
}
