steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - tools/deploy/slack-stg-deploy-bot/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/goatos-stg/goatos/slack-stg-deploy-bot:manual
