#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
container_name="goatos-sqlc-schema-$$"
image="${GOATOS_SQLC_POSTGRES_IMAGE:-${GOATOS_POSTGRES_IMAGE:-postgres:16.9-alpine}}"
db_name="goatos"
db_user="postgres"
out_files=(
  "$repo_root/backend/internal/identity/adapters/postgres/sqlc/schema.sql"
  "$repo_root/backend/internal/legacy_import/adapters/postgres/sqlc/schema.sql"
  "$repo_root/backend/internal/reporting/adapters/postgres/sqlc/schema.sql"
)

cleanup() {
  docker rm -f "$container_name" >/dev/null 2>&1 || true
}
trap cleanup EXIT

run_psql() {
  docker exec -i "$container_name" psql -v ON_ERROR_STOP=1 -U "$db_user" -d "$db_name" "$@"
}

apply_goose_up() {
  local migration="$1"
  awk '
    /^-- \+goose Up/ { in_up = 1; next }
    /^-- \+goose Down/ { in_up = 0 }
    in_up { print }
  ' "$migration" | run_psql
}

docker run --rm --name "$container_name" \
  -e POSTGRES_PASSWORD=goatos \
  -e POSTGRES_DB="$db_name" \
  -d "$image" >/dev/null

for _ in $(seq 1 60); do
  if docker exec "$container_name" pg_isready -U "$db_user" -d "$db_name" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

docker exec "$container_name" pg_isready -U "$db_user" -d "$db_name" >/dev/null

while IFS= read -r migration; do
  apply_goose_up "$migration"
done < <(find "$repo_root/backend/migrations/postgres" -maxdepth 1 -type f -name '*.sql' | sort)

schema_dump="$(
  {
    printf '%s\n' '-- Code generated by tools/sqlc/dump-schema.sh; DO NOT EDIT.'
    printf '%s\n' "-- Source: backend/migrations/postgres/*.sql applied to $image"
    docker exec "$container_name" pg_dump \
      --schema-only \
      --no-owner \
      --no-privileges \
      --no-comments \
      -U "$db_user" \
      -d "$db_name" |
      sed -E \
        -e '/^-- Dumped from database version /d' \
        -e '/^-- Dumped by pg_dump version /d' \
        -e '/^-- Started on /d' \
        -e '/^-- Completed on /d'
  } | awk '
    NF { last = NR }
    { lines[NR] = $0 }
    END {
      for (i = 1; i <= last; i++) {
        print lines[i]
      }
    }
  '
)"

for out_file in "${out_files[@]}"; do
  mkdir -p "$(dirname "$out_file")"
  printf '%s\n' "$schema_dump" > "$out_file"
done
