#!/usr/bin/env bash
# ===========================================================================
# fetch-ceo-ai-secrets.sh
#
# LOCAL DEV convenience: pull the Mesha leadership assistant ("CEO AI") config
# from Google Secret Manager (project goatos-stg, org vgoats.com) and write a
# gitignored .env.ceo-ai.local at the repo root that the local scripts
# (run-cube-local.sh, run-mcp-toolbox-local.sh, backend) source.
#
# This NEVER commits a value; .env.ceo-ai.local is gitignored. It only fetches
# what your account is allowed to read. For a purely-local stack that needs no
# staging access, use tools/dev/setup-ceo-ai-local-role.sh instead, which mints
# throwaway local roles without touching Secret Manager.
#
# NOTE: the staging read-only DB roles are a PENDING deploy step, so the
# *-db-url secrets currently hold a clearly-marked PLACEHOLDER. When fetched,
# this script keeps any working local DSNs already in your env file rather than
# clobbering them with the placeholder (unless --force-remote).
#
# Usage:
#   tools/dev/fetch-ceo-ai-secrets.sh            # merge remote secrets -> env file
#   tools/dev/fetch-ceo-ai-secrets.sh --force-remote  # remote wins even over local DSNs
#   tools/dev/fetch-ceo-ai-secrets.sh --print-names   # list secret names, fetch nothing
# ===========================================================================
set -euo pipefail

PROJECT="${MESHA_SECRETS_PROJECT:-goatos-stg}"
EXPECT_ACCOUNT="${MESHA_SECRETS_ACCOUNT:-ravi@mesha.sg}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${MESHA_CEO_AI_ENV_FILE:-${REPO_ROOT}/.env.ceo-ai.local}"

FORCE_REMOTE=0
PRINT_NAMES=0
for arg in "$@"; do
  case "$arg" in
    --force-remote) FORCE_REMOTE=1 ;;
    --print-names) PRINT_NAMES=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

# Non-secret config defaults (documented, NOT stored as secrets).
: "${MESHA_AI_PROVIDER:=vertex}"
: "${MESHA_VERTEX_PROJECT:=goatos-stg}"
: "${MESHA_VERTEX_LOCATION:=asia-south1}"
: "${MESHA_VERTEX_MODEL:=gemini-2.5-flash}"
: "${MESHA_CUBE_URL:=http://127.0.0.1:4000}"
: "${MESHA_MCP_TOOLBOX_URL:=http://127.0.0.1:5001}"

# Secret Manager entry names (values pulled at fetch time).
CEO_DB_SECRET="mesha-ceo-readonly-db-url"
CUBE_DB_SECRET="mesha-cube-readonly-db-url"
CUBE_API_SECRET="mesha-cube-api-secret"
TOOLSET_SECRET="mesha-mcp-toolset"

if [[ "$PRINT_NAMES" == "1" ]]; then
  printf '%s\n' "$CEO_DB_SECRET" "$CUBE_DB_SECRET" "$CUBE_API_SECRET" "$TOOLSET_SECRET"
  exit 0
fi

# --- context guard ---------------------------------------------------------
acct="$(gcloud config get-value account 2>/dev/null || true)"
if [[ "$acct" != "$EXPECT_ACCOUNT" ]]; then
  echo "WARNING: active gcloud account '$acct' != '$EXPECT_ACCOUNT'." >&2
  echo "  If a fetch fails, run: gcloud auth login ${EXPECT_ACCOUNT}" >&2
fi

access() {
  local name="$1"
  gcloud secrets versions access latest --secret="$name" --project="$PROJECT" 2>/dev/null || true
}

echo "==> fetching CEO AI secrets from Secret Manager (${PROJECT})"
CEO_DB_URL="$(access "$CEO_DB_SECRET")"
CUBE_DB_URL="$(access "$CUBE_DB_SECRET")"
CUBE_API="$(access "$CUBE_API_SECRET")"
TOOLSET="$(access "$TOOLSET_SECRET")"
[[ -z "$TOOLSET" ]] && TOOLSET="mesha_ceo_toolset"

is_placeholder() { [[ "$1" == PLACEHOLDER-* ]]; }

# Preserve an existing working local DSN over a remote placeholder.
existing_val() { [[ -f "$ENV_FILE" ]] && grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2- || true; }

resolve_db_url() {
  local remote="$1" local_key="$2"
  local prior; prior="$(existing_val "$local_key")"
  if [[ "$FORCE_REMOTE" == "1" ]]; then
    printf '%s' "$remote"; return
  fi
  if is_placeholder "$remote" && [[ -n "$prior" ]] && ! is_placeholder "$prior"; then
    printf '%s' "$prior"   # keep the good local DSN
  else
    printf '%s' "$remote"
  fi
}

CEO_DB_FINAL="$(resolve_db_url "$CEO_DB_URL" MESHA_MCP_DB_DSN)"
CUBE_DB_FINAL="$(resolve_db_url "$CUBE_DB_URL" MESHA_CUBE_DB_DSN)"

umask 077
cat > "$ENV_FILE" <<EOF
# GENERATED by tools/dev/fetch-ceo-ai-secrets.sh — DO NOT COMMIT (gitignored).
# Credential VALUES come from Google Secret Manager (${PROJECT}); config is plain.
# Regenerate: tools/dev/fetch-ceo-ai-secrets.sh

# --- provider / Vertex (config, not secret) ---
MESHA_AI_PROVIDER=${MESHA_AI_PROVIDER}
MESHA_VERTEX_PROJECT=${MESHA_VERTEX_PROJECT}
MESHA_VERTEX_LOCATION=${MESHA_VERTEX_LOCATION}
MESHA_VERTEX_MODEL=${MESHA_VERTEX_MODEL}

# --- Cube Core governed metric layer ---
MESHA_CUBE_URL=${MESHA_CUBE_URL}
MESHA_CUBE_API_SECRET=${CUBE_API}
MESHA_CUBE_DB_DSN=${CUBE_DB_FINAL}

# --- MCP Toolbox curated tools ---
MESHA_MCP_TOOLBOX_URL=${MESHA_MCP_TOOLBOX_URL}
MESHA_MCP_TOOLSET=${TOOLSET}
MESHA_MCP_DB_DSN=${CEO_DB_FINAL}
MESHA_CEO_READONLY_DATABASE_URL=${CEO_DB_FINAL}
EOF

echo "==> wrote ${ENV_FILE} (chmod 600, gitignored)"
if is_placeholder "$CEO_DB_FINAL" || is_placeholder "$CUBE_DB_FINAL"; then
  echo "NOTE: a DB url is still a PLACEHOLDER (staging read-only role pending)." >&2
  echo "  For a working LOCAL stack run: tools/dev/setup-ceo-ai-local-role.sh" >&2
fi
