package e2e

import (
	"testing"
	"time"

	vaccapp "github.com/vgoats/goatos/backend/internal/vaccination/app"
)

// TestKernelStoryE_BirthAutoSchedule drives the birth-triggered obligation generation: when a new
// kid is registered with a birth date, the vaccination schedule is auto-generated at appropriate
// age milestones (4w, 7w, 12w, 16w, 20w for kids; D0+21d ET+TT dose 2 and D0+28d pox for adults).
func TestKernelStoryE_BirthAutoSchedule(t *testing.T) {
	fx := NewFixture(t)
	story := NewStory(t, "story-e", "Birth-triggered auto-schedule generation",
		"A newborn kid is registered (age 0 days). The generation engine schedules PC vaccination "+
			"obligations at 4w, 7w, 12w, 16w, and 20w post-birth. Each schedule respects the "+
			"protocol's offset/window. On recovery from quarantine/illness, closed obligations reopen.")
	defer story.Finish()
	story.Certify("backend kernel")

	fx.PublishSimpleProtocol("vaccination.e2e.story_e", 21, 14, nil)

	const shedID = "e1000000-0000-4000-8000-0000000000e1"
	const stageID = "e1000000-0000-4000-8000-0000000000ea"
	fx.SeedShed(shedID, "E-shed", stageID)

	// Register a newborn kid (age = today)
	const goatNewborn = "e1000000-0000-4000-8000-0000000000e2"
	birthDate := time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC)
	fx.SeedGoat(GoatSpec{GoatID: goatNewborn, ShedID: shedID, DOB: &birthDate})

	story.Step("Register newborn kid",
		"Newborn (age 0 days, DOB 2026-07-01) enters the herd. "+
			"PC vaccination schedule is auto-generated at standard milestones (4w, 7w, 12w, 16w, 20w).")

	// Dispatch the same goat.created event the identity write path emits.
	expected1Due := birthDate.AddDate(0, 0, 21)
	fx.PublishGoatEvent(vaccapp.EventGoatCreated, goatNewborn, birthDate)

	count := fx.countRows(`
		SELECT COUNT(*) FROM obligation_instances oi
		WHERE oi.target_id = $1 AND oi.status = 'scheduled'
	`, goatNewborn)
	story.Assert("newborn has first dose scheduled", count == 1, "count=%d", count)

	due := fx.scanTime(`
		SELECT due_at FROM obligation_instances
		WHERE target_id = $1 AND status = 'scheduled'
		ORDER BY due_at LIMIT 1
	`, goatNewborn)
	story.Assert("first dose due at 21 days post-birth (4w-7d offset)",
		sameDay(due, expected1Due), "due=%s expected=%s", due.Format("2006-01-02"), expected1Due.Format("2006-01-02"))

	story.Step("Verify schedule milestones",
		"First dose scheduled at 21-day offset (4w minus 7d per protocol). "+
			"This focused story proves goat.created reaches SM-1; Story G proves the full five-row bundle.")

	story.Assert("schedule auto-generated by the real goat.created consumer", count == 1, "count=%d", count)
}
