package e2e

import (
	"strings"
	"testing"
	"time"

	vaccexecapp "github.com/vgoats/goatos/backend/internal/vaccinationexecution/app"
)

// Projection guard dimensions for operator drive assignments:
// OneToMany animal-vs-dose membership, PageBoundary spillover, ScheduledDate drive day,
// ParkScope assignment, and StatusMatrix capacity states.

// TestKernelStoryAM_OperatorDriveAssignment is the first operator-drive E2E proof for the new
// capacity kernel. It deliberately drives the real planner package, not a hand-built table:
// obligations are assumed already generated by the unchanged vaccination rule engine, and this
// layer assigns the resulting animal work blocks to available operators by unique animal count.
func TestKernelStoryAM_OperatorDriveAssignment(t *testing.T) {
	story := NewStory(t, "story-am", "Operator drive planner assigns animal work, not dose cells",
		"CPT adult seed data is only the proof slice. The generic drive planner consumes already-eligible "+
			"animal work blocks, groups shed partitions under their physical shed, assigns them to available "+
			"operators by unique animal count, and finishes latest-safe work over cap instead of delaying or "+
			"escalating away the vaccination.")
	defer story.Finish()
	story.Certify("backend kernel")
	story.Certify("Action Center")
	story.Certify("Protocol Adherence")
	story.Certify("Control Tower")

	planner := vaccexecapp.OperatorDrivePlanner{}

	story.Step("CPT proof run: three operators, cap 200 animals each, partitions under physical sheds",
		"The July 23 proof run has 324 source animals. Gandhi partitions total 114, Godel 1 "+
			"partitions total 120, and Godel 2 + Mandela 2 + Old Yashoda total 90. All three operators "+
			"must receive meaningful work without multiplying animals by vaccine bundle count.")
	cptPlan, err := planner.Plan(vaccexecapp.DrivePlanRequest{
		StartDate: dateAM(2026, 7, 23),
		Availability: []vaccexecapp.DriveDateAvailability{{
			Date: dateAM(2026, 7, 23),
			Operators: []vaccexecapp.DriveOperator{
				{ID: "amit", Name: "Amit Kumar", Cap: 200, Available: true},
				{ID: "darshan", Name: "Darshan Talwar", Cap: 200, Available: true},
				{ID: "sagar", Name: "Sagar Mahoor", Cap: 200, Available: true},
			},
		}},
		WorkBlocks: cptAdultProofBlocksAM(),
	})
	story.Assert("operator planner returned no error", err == nil, "err=%v", err)
	story.Assert("one drive day was enough at 3 × 200", len(cptPlan.Days) == 1, "days=%d", len(cptPlan.Days))
	story.Assert("all 324 source animals assigned", cptPlan.Days[0].Assigned == 324 && len(cptPlan.Unassigned) == 0,
		"assigned=%d unassigned=%d", cptPlan.Days[0].Assigned, len(cptPlan.Unassigned))
	totals := totalsByOperatorAM(cptPlan.Days[0])
	story.Assert("all three operators receive meaningful balanced work",
		totals["Amit Kumar"] == 114 && totals["Darshan Talwar"] == 120 && totals["Sagar Mahoor"] == 90,
		"totals=%+v", totals)
	story.Assert("operator-only assignment preserves shed visibility grains",
		assignmentForAM(cptPlan.Days[0], "Amit Kumar", "Gandhi") == 114 &&
			assignmentForAM(cptPlan.Days[0], "Darshan Talwar", "Godel 1") == 120 &&
			assignmentForAM(cptPlan.Days[0], "Sagar Mahoor", "Mandela 2") == 47,
		"assignments=%+v", cptPlan.Days[0].Assignments)

	story.Step("Availability changes capacity: day off removes an operator from the plan",
		"Friday availability excludes Amit. The second day must use only Darshan and Sagar; Amit contributes "+
			"zero capacity and must not see an assigned shed for that date.")
	spillPlan, err := planner.Plan(vaccexecapp.DrivePlanRequest{
		StartDate: dateAM(2026, 7, 23),
		Availability: []vaccexecapp.DriveDateAvailability{
			{Date: dateAM(2026, 7, 23), Operators: []vaccexecapp.DriveOperator{
				{ID: "amit", Name: "Amit Kumar", Cap: 50, Available: true},
				{ID: "darshan", Name: "Darshan Talwar", Cap: 50, Available: true},
			}},
			{Date: dateAM(2026, 7, 24), Operators: []vaccexecapp.DriveOperator{
				{ID: "amit", Name: "Amit Kumar", Cap: 50, Available: false},
				{ID: "darshan", Name: "Darshan Talwar", Cap: 50, Available: true},
				{ID: "sagar", Name: "Sagar Mahoor", Cap: 50, Available: true},
			}},
		},
		WorkBlocks: []vaccexecapp.DriveWorkBlock{
			{ID: "alpha", Park: "CPT", RawShed: "Alpha 1", Animals: 50},
			{ID: "beta", Park: "CPT", RawShed: "Beta 1", Animals: 50},
			{ID: "charlie", Park: "CPT", RawShed: "Charlie 1", Animals: 50},
			{ID: "delta", Park: "CPT", RawShed: "Delta 1", Animals: 50},
		},
	})
	story.Assert("spillover planner returned no error", err == nil, "err=%v", err)
	secondDayTotals := totalsByOperatorAM(spillPlan.Days[1])
	story.Assert("second day excludes Amit and splits between available operators",
		secondDayTotals["Amit Kumar"] == 0 && secondDayTotals["Darshan Talwar"] == 50 && secondDayTotals["Sagar Mahoor"] == 50,
		"secondDayTotals=%+v", secondDayTotals)

	story.Step("Latest-safe residual capacity: whole partitions are never cut to top up a day",
		"When animals are crossing the +1 week safe boundary, the planner still treats the physical "+
			"shed/partition as the atomic unit. If the next whole partition does not fit, it remains "+
			"unassigned for a capacity action instead of being sliced into the residual slot.")
	urgentPlan, err := planner.Plan(vaccexecapp.DrivePlanRequest{
		StartDate: dateAM(2026, 7, 23),
		Availability: []vaccexecapp.DriveDateAvailability{{
			Date:      dateAM(2026, 7, 23),
			Operators: []vaccexecapp.DriveOperator{{ID: "amit", Name: "Amit Kumar", Cap: 50, Available: true}},
		}},
		WorkBlocks: []vaccexecapp.DriveWorkBlock{
			{ID: "later-safe", Park: "CPT", RawShed: "Godel 1 - Part 1", Animals: 50, LatestSafeDate: dateAM(2026, 7, 30)},
			{ID: "latest-safe-a", Park: "CPT", RawShed: "Gandhi 1", Animals: 50, LatestSafeDate: dateAM(2026, 7, 23)},
			{ID: "latest-safe-b", Park: "CPT", RawShed: "Gandhi 2", Animals: 25, LatestSafeDate: dateAM(2026, 7, 23)},
		},
	})
	story.Assert("urgent planner returned no error", err == nil, "err=%v", err)
	story.Assert("only the fitting latest-safe partition is assigned today", urgentPlan.Days[0].Assigned == 50,
		"assigned=%d", urgentPlan.Days[0].Assigned)
	story.Assert("non-fitting latest-safe partition remains whole with later-safe work",
		len(urgentPlan.Unassigned) == 2 &&
			urgentPlan.Unassigned[0].ID == "latest-safe-b" &&
			urgentPlan.Unassigned[0].Animals == 25 &&
			urgentPlan.Unassigned[1].ID == "later-safe",
		"unassigned=%+v", urgentPlan.Unassigned)
	story.Assert("capacity breach is surfaced without forced partition split",
		!hasWarningAM(urgentPlan.Days[0], "forced_partition_split") && planTextContainsAM(urgentPlan, "capacity_breach"),
		"plan=%+v", urgentPlan)
}

func cptAdultProofBlocksAM() []vaccexecapp.DriveWorkBlock {
	return []vaccexecapp.DriveWorkBlock{
		{ID: "gandhi-1", Park: "CPT", RawShed: "Gandhi 1", Animals: 42, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "gandhi-2", Park: "CPT", RawShed: "Gandhi 2", Animals: 30, Bundle: "Goat: ET+TT Booster + Goat Pox"},
		{ID: "gandhi-3", Park: "CPT", RawShed: "Gandhi 3", Animals: 42, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "godel-1-part-1", Park: "CPT", RawShed: "Godel 1 - Part 1", Animals: 60, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "godel-1-part-3", Park: "CPT", RawShed: "Godel 1 - Part 3", Animals: 30, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "godel-1-part-4", Park: "CPT", RawShed: "Godel 1 - Part 4", Animals: 30, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "godel-2-part-4", Park: "CPT", RawShed: "Godel 2 - Part 4", Animals: 32, Bundle: "Goat: ET+TT Booster + Goat Pox"},
		{ID: "mandela-2-part-1", Park: "CPT", RawShed: "Mandela 2 - Part 1", Animals: 1, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "mandela-2-part-2", Park: "CPT", RawShed: "Mandela 2 - Part 2", Animals: 2, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "mandela-2-part-3", Park: "CPT", RawShed: "Mandela 2 - Part 3", Animals: 1, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "mandela-2-part-7", Park: "CPT", RawShed: "Mandela 2 - Part 7", Animals: 13, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "mandela-2-part-8", Park: "CPT", RawShed: "Mandela 2 - Part 8", Animals: 30, Bundle: "Goat: ET+TT Booster + Goat Pox"},
		{ID: "old-yashoda-1", Park: "CPT", RawShed: "Old Yashoda 1", Animals: 8, Bundle: "Sheep: ET+TT Booster + PPR"},
		{ID: "old-yashoda-5", Park: "CPT", RawShed: "Old Yashoda 5", Animals: 3, Bundle: "Goat: ET+TT Booster + PPR"},
	}
}

func totalsByOperatorAM(day vaccexecapp.DrivePlanDay) map[string]int {
	totals := map[string]int{}
	for _, assignment := range day.Assignments {
		totals[assignment.OperatorName] += assignment.Animals
	}
	return totals
}

func assignmentForAM(day vaccexecapp.DrivePlanDay, operator, shed string) int {
	for _, assignment := range day.Assignments {
		if assignment.OperatorName == operator && assignment.PhysicalShed == shed {
			return assignment.Animals
		}
	}
	return 0
}

func hasWarningAM(day vaccexecapp.DrivePlanDay, warning string) bool {
	for _, assignment := range day.Assignments {
		for _, got := range assignment.Warnings {
			if got == warning {
				return true
			}
		}
	}
	return false
}

func planTextContainsAM(plan vaccexecapp.DrivePlan, needle string) bool {
	needle = strings.ToLower(needle)
	for _, warning := range plan.Warnings {
		if strings.Contains(strings.ToLower(warning), needle) {
			return true
		}
	}
	for _, day := range plan.Days {
		for _, assignment := range day.Assignments {
			for _, warning := range assignment.Warnings {
				if strings.Contains(strings.ToLower(warning), needle) {
					return true
				}
			}
		}
	}
	return false
}

func dateAM(year int, month time.Month, day int) time.Time {
	return time.Date(year, month, day, 0, 0, 0, 0, time.UTC)
}
