// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package reportingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIdentityCountersByGrain = `-- name: DeleteIdentityCountersByGrain :execrows
DELETE FROM goat_identity_counters
WHERE tenant_id = $1
  AND counter_grain = $2
`

type DeleteIdentityCountersByGrainParams struct {
	TenantID     pgtype.UUID
	CounterGrain string
}

func (q *Queries) DeleteIdentityCountersByGrain(ctx context.Context, arg DeleteIdentityCountersByGrainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityCountersByGrain, arg.TenantID, arg.CounterGrain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBreedSexLifecycleCounters = `-- name: InsertBreedSexLifecycleCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  breed_id,
  sex,
  lifecycle_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'breed_sex_lifecycle',
  g.tenant_id,
  g.breed_id,
  g.sex,
  g.lifecycle_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.breed_id, g.sex, g.lifecycle_status
`

type InsertBreedSexLifecycleCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertBreedSexLifecycleCounters(ctx context.Context, arg InsertBreedSexLifecycleCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBreedSexLifecycleCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCustodianIdentityCounters = `-- name: InsertCustodianIdentityCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  custodian_party_id,
  identity_state,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'custodian_identity',
  g.tenant_id,
  g.custodian_party_id,
  g.identity_state,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.lifecycle_status = 'alive'
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.custodian_party_id, g.identity_state
`

type InsertCustodianIdentityCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertCustodianIdentityCounters(ctx context.Context, arg InsertCustodianIdentityCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCustodianIdentityCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCustodianLifecycleCounters = `-- name: InsertCustodianLifecycleCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  custodian_party_id,
  lifecycle_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'custodian_lifecycle',
  g.tenant_id,
  g.custodian_party_id,
  g.lifecycle_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.custodian_party_id, g.lifecycle_status
`

type InsertCustodianLifecycleCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertCustodianLifecycleCounters(ctx context.Context, arg InsertCustodianLifecycleCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCustodianLifecycleCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGrowthCohortCounters = `-- name: InsertGrowthCohortCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  growth_cohort_tag,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'growth_cohort',
  g.tenant_id,
  g.growth_cohort_tag,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.lifecycle_status = 'alive'
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.growth_cohort_tag
`

type InsertGrowthCohortCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertGrowthCohortCounters(ctx context.Context, arg InsertGrowthCohortCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGrowthCohortCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertHealthStatusCounters = `-- name: InsertHealthStatusCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  health_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'health_status',
  g.tenant_id,
  g.health_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.lifecycle_status = 'alive'
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.health_status
`

type InsertHealthStatusCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertHealthStatusCounters(ctx context.Context, arg InsertHealthStatusCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertHealthStatusCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertManagementStageCounters = `-- name: InsertManagementStageCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  management_stage,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'management_stage',
  g.tenant_id,
  g.management_stage,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.lifecycle_status = 'alive'
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.management_stage
`

type InsertManagementStageCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertManagementStageCounters(ctx context.Context, arg InsertManagementStageCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertManagementStageCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertParkLifecycleCounters = `-- name: InsertParkLifecycleCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  park_id,
  lifecycle_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'park_lifecycle',
  g.tenant_id,
  g.park_id,
  g.lifecycle_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.park_id, g.lifecycle_status
`

type InsertParkLifecycleCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertParkLifecycleCounters(ctx context.Context, arg InsertParkLifecycleCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertParkLifecycleCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertReproductiveStatusCounters = `-- name: InsertReproductiveStatusCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  reproductive_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'reproductive_status',
  g.tenant_id,
  g.reproductive_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.lifecycle_status = 'alive'
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.reproductive_status
`

type InsertReproductiveStatusCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertReproductiveStatusCounters(ctx context.Context, arg InsertReproductiveStatusCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReproductiveStatusCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertShedLifecycleCounters = `-- name: InsertShedLifecycleCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  park_id,
  shed_id,
  lifecycle_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'shed_lifecycle',
  g.tenant_id,
  g.park_id,
  g.shed_id,
  g.lifecycle_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.park_id, g.shed_id, g.lifecycle_status
`

type InsertShedLifecycleCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertShedLifecycleCounters(ctx context.Context, arg InsertShedLifecycleCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertShedLifecycleCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTenantLifecycleCounters = `-- name: InsertTenantLifecycleCounters :execrows
INSERT INTO goat_identity_counters (
  counter_grain,
  tenant_id,
  lifecycle_status,
  count_value,
  as_of_recorded_at,
  source_import_run_id,
  is_rebuilding,
  updated_at
)
SELECT
  'tenant_lifecycle',
  g.tenant_id,
  g.lifecycle_status,
  count(*)::bigint,
  $1,
  $2::uuid,
  false,
  now()
FROM goats g
WHERE g.tenant_id = $3
  AND g.identity_state NOT IN ('merged', 'inactive')
GROUP BY g.tenant_id, g.lifecycle_status
`

type InsertTenantLifecycleCountersParams struct {
	AsOfRecordedAt    pgtype.Timestamptz
	SourceImportRunID pgtype.UUID
	TenantID          pgtype.UUID
}

func (q *Queries) InsertTenantLifecycleCounters(ctx context.Context, arg InsertTenantLifecycleCountersParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTenantLifecycleCounters, arg.AsOfRecordedAt, arg.SourceImportRunID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const maxGoatIdentityEventRecordedAtForTenant = `-- name: MaxGoatIdentityEventRecordedAtForTenant :one
SELECT max(recorded_at)::timestamptz AS as_of_recorded_at
FROM goat_identity_events
WHERE tenant_id = $1
`

func (q *Queries) MaxGoatIdentityEventRecordedAtForTenant(ctx context.Context, tenantID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, maxGoatIdentityEventRecordedAtForTenant, tenantID)
	var as_of_recorded_at pgtype.Timestamptz
	err := row.Scan(&as_of_recorded_at)
	return as_of_recorded_at, err
}

const sourceImportRunBelongsToTenant = `-- name: SourceImportRunBelongsToTenant :one
SELECT EXISTS (
  SELECT 1
  FROM legacy_import_runs
  WHERE tenant_id = $1
    AND import_run_id = $2
)::bool
`

type SourceImportRunBelongsToTenantParams struct {
	TenantID    pgtype.UUID
	ImportRunID pgtype.UUID
}

func (q *Queries) SourceImportRunBelongsToTenant(ctx context.Context, arg SourceImportRunBelongsToTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, sourceImportRunBelongsToTenant, arg.TenantID, arg.ImportRunID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const tenantExists = `-- name: TenantExists :one
SELECT EXISTS (
  SELECT 1
  FROM tenants
  WHERE tenant_id = $1
)::bool
`

func (q *Queries) TenantExists(ctx context.Context, tenantID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExists, tenantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
