// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package reportingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentityCounterProjectionState = `-- name: GetIdentityCounterProjectionState :one
SELECT
  tenant_id::text AS tenant_id,
  last_processed_recorded_at,
  COALESCE(last_processed_event_id::text, '')::text AS last_processed_event_id,
  rebuild_required,
  rebuild_reason,
  updated_at
FROM goat_identity_counter_projection_state
WHERE tenant_id = $1
`

type GetIdentityCounterProjectionStateRow struct {
	TenantID                string
	LastProcessedRecordedAt pgtype.Timestamptz
	LastProcessedEventID    string
	RebuildRequired         bool
	RebuildReason           pgtype.Text
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) GetIdentityCounterProjectionState(ctx context.Context, tenantID pgtype.UUID) (GetIdentityCounterProjectionStateRow, error) {
	row := q.db.QueryRow(ctx, getIdentityCounterProjectionState, tenantID)
	var i GetIdentityCounterProjectionStateRow
	err := row.Scan(
		&i.TenantID,
		&i.LastProcessedRecordedAt,
		&i.LastProcessedEventID,
		&i.RebuildRequired,
		&i.RebuildReason,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityCounts = `-- name: ListIdentityCounts :many
SELECT
  c.counter_id::text AS counter_id,
  c.counter_grain,
  c.tenant_id::text AS tenant_id,
  COALESCE(c.custodian_party_id::text, '')::text AS custodian_party_id,
  COALESCE(c.farm_id::text, '')::text AS farm_id,
  farm.name AS farm_name,
  COALESCE(c.park_id::text, '')::text AS park_id,
  park.name AS park_name,
  COALESCE(c.shed_id::text, '')::text AS shed_id,
  shed.name AS shed_name,
  COALESCE(c.cohort_id::text, '')::text AS cohort_id,
  cohort.name AS cohort_name,
  c.lifecycle_status,
  c.reproductive_status,
  c.growth_cohort_tag,
  c.management_stage,
  c.health_status,
  c.identity_state,
  COALESCE(c.breed_id::text, '')::text AS breed_id,
  breed.canonical_name AS breed_name,
  c.sex,
  c.count_value,
  c.as_of_recorded_at,
  COALESCE(c.source_import_run_id::text, '')::text AS source_import_run_id,
  c.is_rebuilding,
  c.updated_at
FROM goat_identity_counters c
LEFT JOIN locations farm ON farm.tenant_id = c.tenant_id AND farm.location_id = c.farm_id
LEFT JOIN locations park ON park.tenant_id = c.tenant_id AND park.location_id = c.park_id
LEFT JOIN locations shed ON shed.tenant_id = c.tenant_id AND shed.location_id = c.shed_id
LEFT JOIN locations cohort ON cohort.tenant_id = c.tenant_id AND cohort.location_id = c.cohort_id
LEFT JOIN breeds breed ON breed.breed_id = c.breed_id
WHERE c.counter_grain = $1
  AND c.tenant_id = $2
  AND ($3::uuid IS NULL OR c.custodian_party_id = $3::uuid)
  AND ($4::uuid IS NULL OR c.farm_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.park_id = $5::uuid)
  AND ($6::uuid IS NULL OR c.shed_id = $6::uuid)
  AND ($7::uuid IS NULL OR c.cohort_id = $7::uuid)
  AND ($8::text IS NULL OR c.lifecycle_status = $8::text)
  AND ($9::text IS NULL OR c.reproductive_status = $9::text)
  AND ($10::text IS NULL OR c.growth_cohort_tag = $10::text)
  AND ($11::text IS NULL OR c.management_stage = $11::text)
  AND ($12::text IS NULL OR c.health_status = $12::text)
  AND ($13::text IS NULL OR c.identity_state = $13::text)
  AND ($14::uuid IS NULL OR c.breed_id = $14::uuid)
  AND ($15::text IS NULL OR c.sex = $15::text)
  AND (
    $16::bigint IS NULL
    OR c.count_value < $16::bigint
    OR (
      c.count_value = $16::bigint
      AND c.counter_id > $17::uuid
    )
  )
ORDER BY c.count_value DESC, c.counter_id ASC
LIMIT $18
`

type ListIdentityCountsParams struct {
	CounterGrain       string
	TenantID           pgtype.UUID
	CustodianPartyID   pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            pgtype.UUID
	Sex                pgtype.Text
	CursorCountValue   pgtype.Int8
	CursorCounterID    pgtype.UUID
	LimitCount         int32
}

type ListIdentityCountsRow struct {
	CounterID          string
	CounterGrain       string
	TenantID           string
	CustodianPartyID   string
	FarmID             string
	FarmName           pgtype.Text
	ParkID             string
	ParkName           pgtype.Text
	ShedID             string
	ShedName           pgtype.Text
	CohortID           string
	CohortName         pgtype.Text
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            string
	BreedName          pgtype.Text
	Sex                pgtype.Text
	CountValue         int64
	AsOfRecordedAt     pgtype.Timestamptz
	SourceImportRunID  string
	IsRebuilding       bool
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) ListIdentityCounts(ctx context.Context, arg ListIdentityCountsParams) ([]ListIdentityCountsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityCounts,
		arg.CounterGrain,
		arg.TenantID,
		arg.CustodianPartyID,
		arg.FarmID,
		arg.ParkID,
		arg.ShedID,
		arg.CohortID,
		arg.LifecycleStatus,
		arg.ReproductiveStatus,
		arg.GrowthCohortTag,
		arg.ManagementStage,
		arg.HealthStatus,
		arg.IdentityState,
		arg.BreedID,
		arg.Sex,
		arg.CursorCountValue,
		arg.CursorCounterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityCountsRow
	for rows.Next() {
		var i ListIdentityCountsRow
		if err := rows.Scan(
			&i.CounterID,
			&i.CounterGrain,
			&i.TenantID,
			&i.CustodianPartyID,
			&i.FarmID,
			&i.FarmName,
			&i.ParkID,
			&i.ParkName,
			&i.ShedID,
			&i.ShedName,
			&i.CohortID,
			&i.CohortName,
			&i.LifecycleStatus,
			&i.ReproductiveStatus,
			&i.GrowthCohortTag,
			&i.ManagementStage,
			&i.HealthStatus,
			&i.IdentityState,
			&i.BreedID,
			&i.BreedName,
			&i.Sex,
			&i.CountValue,
			&i.AsOfRecordedAt,
			&i.SourceImportRunID,
			&i.IsRebuilding,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEventsAfterCheckpoint = `-- name: ListIdentityEventsAfterCheckpoint :many
SELECT
  identity_event_id::text AS event_id,
  tenant_id::text AS tenant_id,
  goat_id::text AS goat_id,
  event_type,
  recorded_at
FROM goat_identity_events
WHERE tenant_id = $1
  AND (
    $2::timestamptz IS NULL
    OR recorded_at > $2::timestamptz
    OR (
      recorded_at = $2::timestamptz
      AND $3::uuid IS NOT NULL
      AND identity_event_id > $3::uuid
    )
  )
ORDER BY recorded_at ASC, identity_event_id ASC
LIMIT $4
`

type ListIdentityEventsAfterCheckpointParams struct {
	TenantID                pgtype.UUID
	LastProcessedRecordedAt pgtype.Timestamptz
	LastProcessedEventID    pgtype.UUID
	LimitCount              int32
}

type ListIdentityEventsAfterCheckpointRow struct {
	EventID    string
	TenantID   string
	GoatID     string
	EventType  string
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) ListIdentityEventsAfterCheckpoint(ctx context.Context, arg ListIdentityEventsAfterCheckpointParams) ([]ListIdentityEventsAfterCheckpointRow, error) {
	rows, err := q.db.Query(ctx, listIdentityEventsAfterCheckpoint,
		arg.TenantID,
		arg.LastProcessedRecordedAt,
		arg.LastProcessedEventID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityEventsAfterCheckpointRow
	for rows.Next() {
		var i ListIdentityEventsAfterCheckpointRow
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.GoatID,
			&i.EventType,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
