// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package reportingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentityCounterProjectionState = `-- name: GetIdentityCounterProjectionState :one
SELECT
  tenant_id::text AS tenant_id,
  last_processed_recorded_at,
  COALESCE(last_processed_event_id::text, '')::text AS last_processed_event_id,
  rebuild_required,
  rebuild_reason,
  updated_at
FROM goat_identity_counter_projection_state
WHERE tenant_id = $1
`

type GetIdentityCounterProjectionStateRow struct {
	TenantID                string
	LastProcessedRecordedAt pgtype.Timestamptz
	LastProcessedEventID    string
	RebuildRequired         bool
	RebuildReason           pgtype.Text
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) GetIdentityCounterProjectionState(ctx context.Context, tenantID pgtype.UUID) (GetIdentityCounterProjectionStateRow, error) {
	row := q.db.QueryRow(ctx, getIdentityCounterProjectionState, tenantID)
	var i GetIdentityCounterProjectionStateRow
	err := row.Scan(
		&i.TenantID,
		&i.LastProcessedRecordedAt,
		&i.LastProcessedEventID,
		&i.RebuildRequired,
		&i.RebuildReason,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityCounts = `-- name: ListIdentityCounts :many
SELECT
  counter_id::text AS counter_id,
  counter_grain,
  tenant_id::text AS tenant_id,
  COALESCE(custodian_party_id::text, '')::text AS custodian_party_id,
  COALESCE(farm_id::text, '')::text AS farm_id,
  COALESCE(park_id::text, '')::text AS park_id,
  COALESCE(shed_id::text, '')::text AS shed_id,
  COALESCE(cohort_id::text, '')::text AS cohort_id,
  lifecycle_status,
  reproductive_status,
  growth_cohort_tag,
  management_stage,
  health_status,
  identity_state,
  COALESCE(breed_id::text, '')::text AS breed_id,
  sex,
  count_value,
  as_of_recorded_at,
  COALESCE(source_import_run_id::text, '')::text AS source_import_run_id,
  is_rebuilding,
  updated_at
FROM goat_identity_counters
WHERE counter_grain = $1
  AND tenant_id = $2
  AND ($3::uuid IS NULL OR custodian_party_id = $3::uuid)
  AND ($4::uuid IS NULL OR farm_id = $4::uuid)
  AND ($5::uuid IS NULL OR park_id = $5::uuid)
  AND ($6::uuid IS NULL OR shed_id = $6::uuid)
  AND ($7::uuid IS NULL OR cohort_id = $7::uuid)
  AND ($8::text IS NULL OR lifecycle_status = $8::text)
  AND ($9::text IS NULL OR reproductive_status = $9::text)
  AND ($10::text IS NULL OR growth_cohort_tag = $10::text)
  AND ($11::text IS NULL OR management_stage = $11::text)
  AND ($12::text IS NULL OR health_status = $12::text)
  AND ($13::text IS NULL OR identity_state = $13::text)
  AND ($14::uuid IS NULL OR breed_id = $14::uuid)
  AND ($15::text IS NULL OR sex = $15::text)
  AND (
    $16::bigint IS NULL
    OR count_value < $16::bigint
    OR (
      count_value = $16::bigint
      AND counter_id > $17::uuid
    )
  )
ORDER BY count_value DESC, counter_id ASC
LIMIT $18
`

type ListIdentityCountsParams struct {
	CounterGrain       string
	TenantID           pgtype.UUID
	CustodianPartyID   pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            pgtype.UUID
	Sex                pgtype.Text
	CursorCountValue   pgtype.Int8
	CursorCounterID    pgtype.UUID
	LimitCount         int32
}

type ListIdentityCountsRow struct {
	CounterID          string
	CounterGrain       string
	TenantID           string
	CustodianPartyID   string
	FarmID             string
	ParkID             string
	ShedID             string
	CohortID           string
	LifecycleStatus    pgtype.Text
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	IdentityState      pgtype.Text
	BreedID            string
	Sex                pgtype.Text
	CountValue         int64
	AsOfRecordedAt     pgtype.Timestamptz
	SourceImportRunID  string
	IsRebuilding       bool
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) ListIdentityCounts(ctx context.Context, arg ListIdentityCountsParams) ([]ListIdentityCountsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityCounts,
		arg.CounterGrain,
		arg.TenantID,
		arg.CustodianPartyID,
		arg.FarmID,
		arg.ParkID,
		arg.ShedID,
		arg.CohortID,
		arg.LifecycleStatus,
		arg.ReproductiveStatus,
		arg.GrowthCohortTag,
		arg.ManagementStage,
		arg.HealthStatus,
		arg.IdentityState,
		arg.BreedID,
		arg.Sex,
		arg.CursorCountValue,
		arg.CursorCounterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityCountsRow
	for rows.Next() {
		var i ListIdentityCountsRow
		if err := rows.Scan(
			&i.CounterID,
			&i.CounterGrain,
			&i.TenantID,
			&i.CustodianPartyID,
			&i.FarmID,
			&i.ParkID,
			&i.ShedID,
			&i.CohortID,
			&i.LifecycleStatus,
			&i.ReproductiveStatus,
			&i.GrowthCohortTag,
			&i.ManagementStage,
			&i.HealthStatus,
			&i.IdentityState,
			&i.BreedID,
			&i.Sex,
			&i.CountValue,
			&i.AsOfRecordedAt,
			&i.SourceImportRunID,
			&i.IsRebuilding,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEventsAfterCheckpoint = `-- name: ListIdentityEventsAfterCheckpoint :many
SELECT
  identity_event_id::text AS event_id,
  tenant_id::text AS tenant_id,
  goat_id::text AS goat_id,
  event_type,
  recorded_at
FROM goat_identity_events
WHERE tenant_id = $1
  AND (
    $2::timestamptz IS NULL
    OR recorded_at > $2::timestamptz
    OR (
      recorded_at = $2::timestamptz
      AND $3::uuid IS NOT NULL
      AND identity_event_id > $3::uuid
    )
  )
ORDER BY recorded_at ASC, identity_event_id ASC
LIMIT $4
`

type ListIdentityEventsAfterCheckpointParams struct {
	TenantID                pgtype.UUID
	LastProcessedRecordedAt pgtype.Timestamptz
	LastProcessedEventID    pgtype.UUID
	LimitCount              int32
}

type ListIdentityEventsAfterCheckpointRow struct {
	EventID    string
	TenantID   string
	GoatID     string
	EventType  string
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) ListIdentityEventsAfterCheckpoint(ctx context.Context, arg ListIdentityEventsAfterCheckpointParams) ([]ListIdentityEventsAfterCheckpointRow, error) {
	rows, err := q.db.Query(ctx, listIdentityEventsAfterCheckpoint,
		arg.TenantID,
		arg.LastProcessedRecordedAt,
		arg.LastProcessedEventID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityEventsAfterCheckpointRow
	for rows.Next() {
		var i ListIdentityEventsAfterCheckpointRow
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.GoatID,
			&i.EventType,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
