// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package legacyimportdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLegacyImportRun = `-- name: CompleteLegacyImportRun :exec
UPDATE legacy_import_runs
SET
  completed_at = now(),
  status = 'completed',
  row_count = $1,
  created_goat_count = 0,
  updated_goat_count = 0,
  conflict_count = 0,
  error_count = $2
WHERE tenant_id = $3
  AND import_run_id = $4
`

type CompleteLegacyImportRunParams struct {
	RowCount    int32
	ErrorCount  int32
	TenantID    pgtype.UUID
	ImportRunID pgtype.UUID
}

func (q *Queries) CompleteLegacyImportRun(ctx context.Context, arg CompleteLegacyImportRunParams) error {
	_, err := q.db.Exec(ctx, completeLegacyImportRun,
		arg.RowCount,
		arg.ErrorCount,
		arg.TenantID,
		arg.ImportRunID,
	)
	return err
}

const createLegacyImportRun = `-- name: CreateLegacyImportRun :one
INSERT INTO legacy_import_runs (
  tenant_id,
  source_name,
  source_system,
  source_dataset,
  source_file_ref,
  source_file_hash,
  policy_version,
  dry_run,
  completed_at,
  status,
  row_count,
  created_goat_count,
  updated_goat_count,
  conflict_count,
  error_count,
  started_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::text,
  $6,
  $7,
  $8,
  CASE WHEN $9::text = 'completed' THEN now() ELSE NULL END,
  $9,
  $10,
  0,
  0,
  0,
  $11,
  $12::uuid
)
RETURNING import_run_id::text AS import_run_id
`

type CreateLegacyImportRunParams struct {
	TenantID       pgtype.UUID
	SourceName     string
	SourceSystem   string
	SourceDataset  string
	SourceFileRef  pgtype.Text
	SourceFileHash pgtype.Text
	PolicyVersion  string
	DryRun         bool
	Status         string
	RowCount       int32
	ErrorCount     int32
	StartedBy      pgtype.UUID
}

func (q *Queries) CreateLegacyImportRun(ctx context.Context, arg CreateLegacyImportRunParams) (string, error) {
	row := q.db.QueryRow(ctx, createLegacyImportRun,
		arg.TenantID,
		arg.SourceName,
		arg.SourceSystem,
		arg.SourceDataset,
		arg.SourceFileRef,
		arg.SourceFileHash,
		arg.PolicyVersion,
		arg.DryRun,
		arg.Status,
		arg.RowCount,
		arg.ErrorCount,
		arg.StartedBy,
	)
	var import_run_id string
	err := row.Scan(&import_run_id)
	return import_run_id, err
}

const failLegacyImportRun = `-- name: FailLegacyImportRun :exec
UPDATE legacy_import_runs
SET
  completed_at = now(),
  status = 'failed',
  row_count = $1,
  created_goat_count = 0,
  updated_goat_count = 0,
  conflict_count = 0,
  error_count = $2
WHERE tenant_id = $3
  AND import_run_id = $4
`

type FailLegacyImportRunParams struct {
	RowCount    int32
	ErrorCount  int32
	TenantID    pgtype.UUID
	ImportRunID pgtype.UUID
}

func (q *Queries) FailLegacyImportRun(ctx context.Context, arg FailLegacyImportRunParams) error {
	_, err := q.db.Exec(ctx, failLegacyImportRun,
		arg.RowCount,
		arg.ErrorCount,
		arg.TenantID,
		arg.ImportRunID,
	)
	return err
}

const insertLegacyImportRow = `-- name: InsertLegacyImportRow :one
INSERT INTO legacy_import_rows (
  import_run_id,
  tenant_id,
  source_system,
  source_dataset,
  source_record_id,
  source_row_key,
  source_key_recipe_version,
  source_row_version_hash,
  hash_recipe_version,
  row_number,
  raw_payload,
  normalized_payload,
  processing_state,
  error_reason,
  matched_goat_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::text,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14::text,
  NULL
)
ON CONFLICT (tenant_id, source_system, source_dataset, source_row_key, source_row_version_hash) DO NOTHING
RETURNING legacy_row_id::text AS legacy_row_id
`

type InsertLegacyImportRowParams struct {
	ImportRunID            pgtype.UUID
	TenantID               pgtype.UUID
	SourceSystem           string
	SourceDataset          string
	SourceRecordID         pgtype.Text
	SourceRowKey           string
	SourceKeyRecipeVersion string
	SourceRowVersionHash   string
	HashRecipeVersion      string
	RowNumber              int32
	RawPayload             []byte
	NormalizedPayload      []byte
	ProcessingState        string
	ErrorReason            pgtype.Text
}

func (q *Queries) InsertLegacyImportRow(ctx context.Context, arg InsertLegacyImportRowParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLegacyImportRow,
		arg.ImportRunID,
		arg.TenantID,
		arg.SourceSystem,
		arg.SourceDataset,
		arg.SourceRecordID,
		arg.SourceRowKey,
		arg.SourceKeyRecipeVersion,
		arg.SourceRowVersionHash,
		arg.HashRecipeVersion,
		arg.RowNumber,
		arg.RawPayload,
		arg.NormalizedPayload,
		arg.ProcessingState,
		arg.ErrorReason,
	)
	var legacy_row_id string
	err := row.Scan(&legacy_row_id)
	return legacy_row_id, err
}
