// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package legacyimportdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApprovedLegacyImportPolicy = `-- name: GetApprovedLegacyImportPolicy :one
SELECT
  policy_version,
  source_system,
  source_dataset,
  identifier_policy_version,
  source_key_recipe,
  source_key_recipe_version,
  hash_recipe,
  hash_recipe_version,
  normalizer_version
FROM legacy_import_policies
WHERE policy_version = $1
  AND status = 'approved'
`

type GetApprovedLegacyImportPolicyRow struct {
	PolicyVersion           string
	SourceSystem            string
	SourceDataset           string
	IdentifierPolicyVersion string
	SourceKeyRecipe         []byte
	SourceKeyRecipeVersion  string
	HashRecipe              []byte
	HashRecipeVersion       string
	NormalizerVersion       string
}

func (q *Queries) GetApprovedLegacyImportPolicy(ctx context.Context, policyVersion string) (GetApprovedLegacyImportPolicyRow, error) {
	row := q.db.QueryRow(ctx, getApprovedLegacyImportPolicy, policyVersion)
	var i GetApprovedLegacyImportPolicyRow
	err := row.Scan(
		&i.PolicyVersion,
		&i.SourceSystem,
		&i.SourceDataset,
		&i.IdentifierPolicyVersion,
		&i.SourceKeyRecipe,
		&i.SourceKeyRecipeVersion,
		&i.HashRecipe,
		&i.HashRecipeVersion,
		&i.NormalizerVersion,
	)
	return i, err
}

const getLegacyImportRunForApply = `-- name: GetLegacyImportRunForApply :one
SELECT
  import_run_id::text AS import_run_id,
  tenant_id::text AS tenant_id,
  source_system,
  source_dataset,
  policy_version,
  dry_run,
  status,
  row_count,
  created_goat_count,
  updated_goat_count,
  conflict_count,
  error_count
FROM legacy_import_runs
WHERE tenant_id = $1
  AND import_run_id = $2
`

type GetLegacyImportRunForApplyParams struct {
	TenantID    pgtype.UUID
	ImportRunID pgtype.UUID
}

type GetLegacyImportRunForApplyRow struct {
	ImportRunID      string
	TenantID         string
	SourceSystem     string
	SourceDataset    string
	PolicyVersion    string
	DryRun           bool
	Status           string
	RowCount         int32
	CreatedGoatCount int32
	UpdatedGoatCount int32
	ConflictCount    int32
	ErrorCount       int32
}

func (q *Queries) GetLegacyImportRunForApply(ctx context.Context, arg GetLegacyImportRunForApplyParams) (GetLegacyImportRunForApplyRow, error) {
	row := q.db.QueryRow(ctx, getLegacyImportRunForApply, arg.TenantID, arg.ImportRunID)
	var i GetLegacyImportRunForApplyRow
	err := row.Scan(
		&i.ImportRunID,
		&i.TenantID,
		&i.SourceSystem,
		&i.SourceDataset,
		&i.PolicyVersion,
		&i.DryRun,
		&i.Status,
		&i.RowCount,
		&i.CreatedGoatCount,
		&i.UpdatedGoatCount,
		&i.ConflictCount,
		&i.ErrorCount,
	)
	return i, err
}

const hasLegacyImportRowWithDifferentHash = `-- name: HasLegacyImportRowWithDifferentHash :one
SELECT EXISTS (
  SELECT 1
  FROM legacy_import_rows
  WHERE tenant_id = $1
    AND source_system = $2
    AND source_dataset = $3
    AND source_row_key = $4
    AND source_row_version_hash <> $5
)::bool
`

type HasLegacyImportRowWithDifferentHashParams struct {
	TenantID             pgtype.UUID
	SourceSystem         string
	SourceDataset        string
	SourceRowKey         string
	SourceRowVersionHash string
}

func (q *Queries) HasLegacyImportRowWithDifferentHash(ctx context.Context, arg HasLegacyImportRowWithDifferentHashParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLegacyImportRowWithDifferentHash,
		arg.TenantID,
		arg.SourceSystem,
		arg.SourceDataset,
		arg.SourceRowKey,
		arg.SourceRowVersionHash,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listPendingLegacyImportRowsForApply = `-- name: ListPendingLegacyImportRowsForApply :many
SELECT
  legacy_row_id::text AS legacy_row_id,
  row_number,
  source_system,
  source_dataset,
  source_record_id,
  source_row_key,
  source_key_recipe_version,
  source_row_version_hash,
  hash_recipe_version,
  raw_payload,
  normalized_payload,
  processing_state,
  error_reason
FROM legacy_import_rows
WHERE tenant_id = $1
  AND import_run_id = $2
  AND processing_state = 'pending'
  AND (
    $3::int IS NULL
    OR (row_number, legacy_row_id) > ($3::int, $4::uuid)
  )
ORDER BY row_number, legacy_import_rows.legacy_row_id
LIMIT $5
`

type ListPendingLegacyImportRowsForApplyParams struct {
	TenantID          pgtype.UUID
	ImportRunID       pgtype.UUID
	CursorRowNumber   pgtype.Int4
	CursorLegacyRowID pgtype.UUID
	LimitCount        int32
}

type ListPendingLegacyImportRowsForApplyRow struct {
	LegacyRowID            string
	RowNumber              int32
	SourceSystem           string
	SourceDataset          string
	SourceRecordID         pgtype.Text
	SourceRowKey           string
	SourceKeyRecipeVersion string
	SourceRowVersionHash   string
	HashRecipeVersion      string
	RawPayload             []byte
	NormalizedPayload      []byte
	ProcessingState        string
	ErrorReason            pgtype.Text
}

func (q *Queries) ListPendingLegacyImportRowsForApply(ctx context.Context, arg ListPendingLegacyImportRowsForApplyParams) ([]ListPendingLegacyImportRowsForApplyRow, error) {
	rows, err := q.db.Query(ctx, listPendingLegacyImportRowsForApply,
		arg.TenantID,
		arg.ImportRunID,
		arg.CursorRowNumber,
		arg.CursorLegacyRowID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingLegacyImportRowsForApplyRow
	for rows.Next() {
		var i ListPendingLegacyImportRowsForApplyRow
		if err := rows.Scan(
			&i.LegacyRowID,
			&i.RowNumber,
			&i.SourceSystem,
			&i.SourceDataset,
			&i.SourceRecordID,
			&i.SourceRowKey,
			&i.SourceKeyRecipeVersion,
			&i.SourceRowVersionHash,
			&i.HashRecipeVersion,
			&i.RawPayload,
			&i.NormalizedPayload,
			&i.ProcessingState,
			&i.ErrorReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRFIDApplyCandidateRowsForBlankSuffixPolicy = `-- name: ListRFIDApplyCandidateRowsForBlankSuffixPolicy :many
SELECT
  legacy_row_id::text AS legacy_row_id,
  row_number,
  source_system,
  source_dataset,
  source_record_id,
  source_row_key,
  source_key_recipe_version,
  source_row_version_hash,
  hash_recipe_version,
  raw_payload,
  normalized_payload,
  processing_state,
  error_reason
FROM legacy_import_rows
WHERE tenant_id = $1
  AND import_run_id = $2
  AND (
    processing_state = 'pending'
    OR (
      processing_state = 'needs_review'
      AND normalized_payload @> '{"processing_reasons":["blank_old_tag_suffix"]}'::jsonb
    )
  )
  AND (
    $3::int IS NULL
    OR (row_number, legacy_row_id) > ($3::int, $4::uuid)
  )
ORDER BY row_number, legacy_import_rows.legacy_row_id
LIMIT $5
`

type ListRFIDApplyCandidateRowsForBlankSuffixPolicyParams struct {
	TenantID          pgtype.UUID
	ImportRunID       pgtype.UUID
	CursorRowNumber   pgtype.Int4
	CursorLegacyRowID pgtype.UUID
	LimitCount        int32
}

type ListRFIDApplyCandidateRowsForBlankSuffixPolicyRow struct {
	LegacyRowID            string
	RowNumber              int32
	SourceSystem           string
	SourceDataset          string
	SourceRecordID         pgtype.Text
	SourceRowKey           string
	SourceKeyRecipeVersion string
	SourceRowVersionHash   string
	HashRecipeVersion      string
	RawPayload             []byte
	NormalizedPayload      []byte
	ProcessingState        string
	ErrorReason            pgtype.Text
}

func (q *Queries) ListRFIDApplyCandidateRowsForBlankSuffixPolicy(ctx context.Context, arg ListRFIDApplyCandidateRowsForBlankSuffixPolicyParams) ([]ListRFIDApplyCandidateRowsForBlankSuffixPolicyRow, error) {
	rows, err := q.db.Query(ctx, listRFIDApplyCandidateRowsForBlankSuffixPolicy,
		arg.TenantID,
		arg.ImportRunID,
		arg.CursorRowNumber,
		arg.CursorLegacyRowID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRFIDApplyCandidateRowsForBlankSuffixPolicyRow
	for rows.Next() {
		var i ListRFIDApplyCandidateRowsForBlankSuffixPolicyRow
		if err := rows.Scan(
			&i.LegacyRowID,
			&i.RowNumber,
			&i.SourceSystem,
			&i.SourceDataset,
			&i.SourceRecordID,
			&i.SourceRowKey,
			&i.SourceKeyRecipeVersion,
			&i.SourceRowVersionHash,
			&i.HashRecipeVersion,
			&i.RawPayload,
			&i.NormalizedPayload,
			&i.ProcessingState,
			&i.ErrorReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
