// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package legacyimportdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApprovedLegacyImportPolicy = `-- name: GetApprovedLegacyImportPolicy :one
SELECT
  policy_version,
  source_system,
  source_dataset,
  identifier_policy_version,
  source_key_recipe,
  source_key_recipe_version,
  hash_recipe,
  hash_recipe_version,
  normalizer_version
FROM legacy_import_policies
WHERE policy_version = $1
  AND status = 'approved'
`

type GetApprovedLegacyImportPolicyRow struct {
	PolicyVersion           string
	SourceSystem            string
	SourceDataset           string
	IdentifierPolicyVersion string
	SourceKeyRecipe         []byte
	SourceKeyRecipeVersion  string
	HashRecipe              []byte
	HashRecipeVersion       string
	NormalizerVersion       string
}

func (q *Queries) GetApprovedLegacyImportPolicy(ctx context.Context, policyVersion string) (GetApprovedLegacyImportPolicyRow, error) {
	row := q.db.QueryRow(ctx, getApprovedLegacyImportPolicy, policyVersion)
	var i GetApprovedLegacyImportPolicyRow
	err := row.Scan(
		&i.PolicyVersion,
		&i.SourceSystem,
		&i.SourceDataset,
		&i.IdentifierPolicyVersion,
		&i.SourceKeyRecipe,
		&i.SourceKeyRecipeVersion,
		&i.HashRecipe,
		&i.HashRecipeVersion,
		&i.NormalizerVersion,
	)
	return i, err
}

const hasLegacyImportRowWithDifferentHash = `-- name: HasLegacyImportRowWithDifferentHash :one
SELECT EXISTS (
  SELECT 1
  FROM legacy_import_rows
  WHERE tenant_id = $1
    AND source_system = $2
    AND source_dataset = $3
    AND source_row_key = $4
    AND source_row_version_hash <> $5
)::bool
`

type HasLegacyImportRowWithDifferentHashParams struct {
	TenantID             pgtype.UUID
	SourceSystem         string
	SourceDataset        string
	SourceRowKey         string
	SourceRowVersionHash string
}

func (q *Queries) HasLegacyImportRowWithDifferentHash(ctx context.Context, arg HasLegacyImportRowWithDifferentHashParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLegacyImportRowWithDifferentHash,
		arg.TenantID,
		arg.SourceSystem,
		arg.SourceDataset,
		arg.SourceRowKey,
		arg.SourceRowVersionHash,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
