// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package obligationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachObligationsToBatch = `-- name: AttachObligationsToBatch :execrows
UPDATE obligation_instances
SET batch_id = $1, updated_at = now()
WHERE tenant_id = $2
  AND obligation_id = ANY($3::uuid[])
  AND batch_id IS NULL
  AND status IN ('scheduled', 'due', 'in_progress', 'missed')
`

type AttachObligationsToBatchParams struct {
	BatchID       pgtype.UUID
	TenantID      pgtype.UUID
	ObligationIds []pgtype.UUID
}

// Attach a set of still-open, still-unbatched obligations to a batch (idempotent: already-batched
// and newly blocked/closed obligations are skipped).
func (q *Queries) AttachObligationsToBatch(ctx context.Context, arg AttachObligationsToBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachObligationsToBatch, arg.BatchID, arg.TenantID, arg.ObligationIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelOpenObligationsForGoat = `-- name: CancelOpenObligationsForGoat :many
UPDATE obligation_instances
SET status = 'canceled', row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $1
  AND target_type = 'goat'
  AND target_id = $2
  AND status IN ('scheduled', 'due', 'in_progress', 'deferred')
RETURNING obligation_id::text AS obligation_id
`

type CancelOpenObligationsForGoatParams struct {
	TenantID pgtype.UUID
	TargetID pgtype.UUID
}

// SM-3: cancel a goat's still-open obligations on death/sale/exit. 'deferred' (held sick/ICU/
// quarantine) work is included so a goat that exits while on hold does not strand open obligations.
// Idempotent — completed/accepted/missed/already-canceled rows are not matched. Uses
// obligation_instances_target_idx.
func (q *Queries) CancelOpenObligationsForGoat(ctx context.Context, arg CancelOpenObligationsForGoatParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cancelOpenObligationsForGoat, arg.TenantID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var obligation_id string
		if err := rows.Scan(&obligation_id); err != nil {
			return nil, err
		}
		items = append(items, obligation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'completed', result_type = $1, result_id = $2, completed_at = now()
WHERE idempotency_key = $3
`

type CompleteIdempotencyKeyParams struct {
	ResultType     pgtype.Text
	ResultID       pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey, arg.ResultType, arg.ResultID, arg.IdempotencyKey)
	return err
}

const createObligationBatch = `-- name: CreateObligationBatch :one
INSERT INTO obligation_batches (
  tenant_id, protocol_version_id, scope_type, scope_id, session, planned_date,
  window_start, window_end, status, estimated_targets, planned_quantity, quantity_unit,
  primary_inventory_lot_id, sop_task_id, conducted_by
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15
)
RETURNING batch_id::text AS batch_id
`

type CreateObligationBatchParams struct {
	TenantID              pgtype.UUID
	ProtocolVersionID     pgtype.UUID
	ScopeType             string
	ScopeID               pgtype.UUID
	Session               pgtype.Text
	PlannedDate           pgtype.Date
	WindowStart           pgtype.Timestamptz
	WindowEnd             pgtype.Timestamptz
	Status                string
	EstimatedTargets      int32
	PlannedQuantity       pgtype.Numeric
	QuantityUnit          pgtype.Text
	PrimaryInventoryLotID pgtype.UUID
	SopTaskID             pgtype.UUID
	ConductedBy           pgtype.UUID
}

func (q *Queries) CreateObligationBatch(ctx context.Context, arg CreateObligationBatchParams) (string, error) {
	row := q.db.QueryRow(ctx, createObligationBatch,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Session,
		arg.PlannedDate,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Status,
		arg.EstimatedTargets,
		arg.PlannedQuantity,
		arg.QuantityUnit,
		arg.PrimaryInventoryLotID,
		arg.SopTaskID,
		arg.ConductedBy,
	)
	var batch_id string
	err := row.Scan(&batch_id)
	return batch_id, err
}

const insertObligationInstance = `-- name: InsertObligationInstance :one
INSERT INTO obligation_instances (
  tenant_id, protocol_version_id, rule_id, batch_id, target_type, target_id,
  scope_type, scope_id, due_at, window_start, window_end, status,
  idempotency_key, rule_identity_key, generated_by_trigger_id, "sequence",
  repeat_cycle_source, repeat_cycle_source_ref, repeat_cycle_anchor_obligation_id,
  repeat_cycle_anchor_at, repeat_cycle_due_at
) SELECT
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16,
  $17, $18,
  $19, $20,
  $21
WHERE NOT EXISTS (
  SELECT 1
  FROM obligation_instances existing
  WHERE existing.tenant_id = $1
    AND existing.protocol_version_id = $2
    AND existing.rule_id = $3
    AND existing.target_type = $5
    AND existing.target_id = $6
    AND (
      -- NON-REPEAT: missed is closed history. A fresh generation pass must be able to create
      -- new work instead of letting a terminal missed row suppress the insert.
      (
        $18::text IS NULL
        AND existing."sequence" = $16
        AND existing.due_at = $9
        AND existing.status IN ('scheduled', 'due', 'in_progress', 'deferred')
      )
      OR
      -- REPEAT: deduped by the administration that CAUSED it, never by its due date. A
      -- repeat's due date moves with the previous dose, which is exactly how the same
      -- cycle came to be minted twice a day apart.
      --
      -- 'missed' is absent on purpose: a missed successor is closed history, so it must
      -- free its source for the next pass to mint new work rather than block it forever.
      (
        $18::text IS NOT NULL
        AND existing.status IN ('scheduled', 'due', 'in_progress', 'deferred')
        AND (
          existing.repeat_cycle_source = $17::text
            AND existing.repeat_cycle_source_ref = $18::text
          OR
          -- A row written before repeat-cycle metadata existed carries no cause, so it cannot
          -- be matched by one. It is still the same open cycle: for a repeat rule, one open
          -- obligation per dose slot IS the invariant. Without this an anchored insert would
          -- land beside every unrepaired legacy row on the day of deploy -- including rows
          -- whose cause the repair could not reconstruct, which are reported and left alone
          -- rather than guessed at. Scoped to the repeat branch, so no other writer is
          -- affected.
          existing.repeat_cycle_source_ref IS NULL
            AND existing."sequence" = $16
        )
      )
    )
)
ON CONFLICT (tenant_id, idempotency_key) DO UPDATE
SET scope_type = EXCLUDED.scope_type,
    scope_id = EXCLUDED.scope_id,
    due_at = EXCLUDED.due_at,
    window_start = EXCLUDED.window_start,
    window_end = EXCLUDED.window_end,
    status = EXCLUDED.status,
    row_version = obligation_instances.row_version + 1,
    updated_at = now()
WHERE obligation_instances.batch_id IS NULL
  AND obligation_instances.status IN ('scheduled', 'due', 'deferred')
  AND (
    obligation_instances.scope_type IS DISTINCT FROM EXCLUDED.scope_type
    OR obligation_instances.scope_id IS DISTINCT FROM EXCLUDED.scope_id
    OR obligation_instances.due_at IS DISTINCT FROM EXCLUDED.due_at
    OR obligation_instances.window_start IS DISTINCT FROM EXCLUDED.window_start
    OR obligation_instances.window_end IS DISTINCT FROM EXCLUDED.window_end
    OR obligation_instances.status IS DISTINCT FROM EXCLUDED.status
  )
RETURNING obligation_id::text AS obligation_id
`

type InsertObligationInstanceParams struct {
	TenantID                      pgtype.UUID
	ProtocolVersionID             pgtype.UUID
	RuleID                        pgtype.UUID
	BatchID                       pgtype.UUID
	TargetType                    string
	TargetID                      pgtype.UUID
	ScopeType                     string
	ScopeID                       pgtype.UUID
	DueAt                         pgtype.Timestamptz
	WindowStart                   pgtype.Timestamptz
	WindowEnd                     pgtype.Timestamptz
	Status                        string
	IdempotencyKey                string
	RuleIdentityKey               pgtype.Text
	GeneratedByTriggerID          pgtype.UUID
	Sequence                      int32
	RepeatCycleSource             pgtype.Text
	RepeatCycleSourceRef          pgtype.Text
	RepeatCycleAnchorObligationID pgtype.UUID
	RepeatCycleAnchorAt           pgtype.Timestamptz
	RepeatCycleDueAt              pgtype.Timestamptz
}

// Deterministic idempotency_key makes generation a no-op on replay (returns no row on conflict).
// The logical duplicate guard also prevents pre-canonical-key rows (for example old next_cycle keys)
// from being duplicated by a later replay with a corrected idempotency key. Bare ON CONFLICT is
// intentional: concurrent generators can both pass NOT EXISTS, so either unique guard must converge.
func (q *Queries) InsertObligationInstance(ctx context.Context, arg InsertObligationInstanceParams) (string, error) {
	row := q.db.QueryRow(ctx, insertObligationInstance,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.RuleID,
		arg.BatchID,
		arg.TargetType,
		arg.TargetID,
		arg.ScopeType,
		arg.ScopeID,
		arg.DueAt,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Status,
		arg.IdempotencyKey,
		arg.RuleIdentityKey,
		arg.GeneratedByTriggerID,
		arg.Sequence,
		arg.RepeatCycleSource,
		arg.RepeatCycleSourceRef,
		arg.RepeatCycleAnchorObligationID,
		arg.RepeatCycleAnchorAt,
		arg.RepeatCycleDueAt,
	)
	var obligation_id string
	err := row.Scan(&obligation_id)
	return obligation_id, err
}

const insertObligationStatusEvent = `-- name: InsertObligationStatusEvent :one
INSERT INTO obligation_status_events (
  tenant_id, obligation_id, event_type, occurred_at, actor_id, payload, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING obligation_event_id::text AS obligation_event_id
`

type InsertObligationStatusEventParams struct {
	TenantID       pgtype.UUID
	ObligationID   pgtype.UUID
	EventType      string
	OccurredAt     pgtype.Timestamptz
	ActorID        pgtype.UUID
	Payload        []byte
	IdempotencyKey string
}

func (q *Queries) InsertObligationStatusEvent(ctx context.Context, arg InsertObligationStatusEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertObligationStatusEvent,
		arg.TenantID,
		arg.ObligationID,
		arg.EventType,
		arg.OccurredAt,
		arg.ActorID,
		arg.Payload,
		arg.IdempotencyKey,
	)
	var obligation_event_id string
	err := row.Scan(&obligation_event_id)
	return obligation_event_id, err
}

const markObligationCompleted = `-- name: MarkObligationCompleted :execrows
UPDATE obligation_instances
SET status = 'completed', completed_at = now(), row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $1
  AND obligation_id = $2
  AND status IN ('scheduled', 'due', 'in_progress', 'missed')
`

type MarkObligationCompletedParams struct {
	TenantID     pgtype.UUID
	ObligationID pgtype.UUID
}

// SM-5: mark an obligation completed on accepted verification. Late real-world work may complete
// a previously-missed obligation; the missed event remains in the ledger for audit/as-of views.
// Idempotent: rows already completed/waived/canceled/superseded are not matched.
func (q *Queries) MarkObligationCompleted(ctx context.Context, arg MarkObligationCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markObligationCompleted, arg.TenantID, arg.ObligationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reScopeOpenObligationsForGoat = `-- name: ReScopeOpenObligationsForGoat :many
UPDATE obligation_instances
SET scope_type = $1, scope_id = $2, row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $3
  AND target_type = 'goat'
  AND target_id = $4
  AND status IN ('scheduled', 'due', 'deferred')
  AND batch_id IS NULL
  AND (scope_type IS DISTINCT FROM $1 OR scope_id IS DISTINCT FROM $2)
RETURNING obligation_id::text AS obligation_id
`

type ReScopeOpenObligationsForGoatParams struct {
	ScopeType string
	ScopeID   pgtype.UUID
	TenantID  pgtype.UUID
	TargetID  pgtype.UUID
}

// SM-2: on a goat shift, move the goat's still-open, unbatched obligations to the new scope. 'deferred'
// (held sick/ICU/quarantine) work is re-scoped too — symmetric with SM-3 CancelOpenObligationsForGoat —
// so when the goat later recovers, ReopenDeferredObligationForKey surfaces the obligation at the goat's
// CURRENT shed and the SM-4 sweeper batches it under the right drive ("one shed = one drive"); without
// this a deferred row would reopen at the stale pre-move shed. The IS DISTINCT FROM guard makes a
// same-scope replay match nothing (no row_version churn → idempotent). Completed/in-progress/missed/
// canceled and already-batched obligations are never touched (a batched deferred row is mid-drive and
// must stay with its batch). Uses obligation_instances_target_idx.
func (q *Queries) ReScopeOpenObligationsForGoat(ctx context.Context, arg ReScopeOpenObligationsForGoatParams) ([]string, error) {
	rows, err := q.db.Query(ctx, reScopeOpenObligationsForGoat,
		arg.ScopeType,
		arg.ScopeID,
		arg.TenantID,
		arg.TargetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var obligation_id string
		if err := rows.Scan(&obligation_id); err != nil {
			return nil, err
		}
		items = append(items, obligation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenDeferredObligationForKey = `-- name: ReopenDeferredObligationForKey :one
WITH target AS MATERIALIZED (
  SELECT oi.obligation_id, oi.status, oi.due_at, oi.row_version,
         oi.target_type, oi.target_id, oi.protocol_version_id
  FROM obligation_instances oi
  WHERE oi.tenant_id = $1
    AND oi.idempotency_key = $2
  FOR UPDATE
), updated AS (
  UPDATE obligation_instances oi
  SET status = 'scheduled', batch_id = NULL, row_version = oi.row_version + 1, updated_at = now()
  FROM target t
  WHERE oi.tenant_id = $1
    AND oi.obligation_id = t.obligation_id
    AND t.status = 'deferred'
    AND NOT EXISTS (
    SELECT 1
    FROM goats g
    JOIN protocol_versions pv
      ON pv.tenant_id = $1
     AND pv.protocol_version_id = t.protocol_version_id
    JOIN protocol_definitions pd
      ON pd.tenant_id = pv.tenant_id
     AND pd.protocol_id = pv.protocol_id
    WHERE t.target_type = 'goat'
      AND g.tenant_id = $1
      AND g.goat_id = t.target_id
      AND pd.category = 'vaccination'
      AND (
        g.lifecycle_status IN ('dead', 'sold', 'lost', 'culled', 'transferred', 'merged', 'inactive')
        OR g.merged_into_goat_id IS NOT NULL
        OR EXISTS (
          SELECT 1
          FROM vw_procurement_vaccination_excluded_goats ex
          WHERE ex.tenant_id = g.tenant_id
            AND ex.goat_id = g.goat_id
        )
      )
    )
  RETURNING oi.obligation_id::text AS obligation_id, oi.status, oi.due_at, oi.row_version
)
SELECT obligation_id, status, due_at, row_version, true AS changed FROM updated
UNION ALL
SELECT t.obligation_id::text, t.status, t.due_at, t.row_version, false AS changed
FROM target t
WHERE NOT EXISTS (SELECT 1 FROM updated)
LIMIT 1
`

type ReopenDeferredObligationForKeyParams struct {
	TenantID       pgtype.UUID
	IdempotencyKey string
}

type ReopenDeferredObligationForKeyRow struct {
	ObligationID string
	Status       string
	DueAt        pgtype.Timestamptz
	RowVersion   int32
	Changed      bool
}

// Recovery recheck: a previously-deferred (held) obligation becomes schedulable again once the goat
// is no longer in a defer state (recovered from sick/ICU/quarantine). Clear batch_id defensively so
// recovery always returns the obligation to the unbatched sweeper path, even if a future execution
// path deferred a row after it had been attached to a non-planned batch. Idempotent: only rows still
// 'deferred' match, so a replay after the goat is already schedulable is a no-op.
func (q *Queries) ReopenDeferredObligationForKey(ctx context.Context, arg ReopenDeferredObligationForKeyParams) (ReopenDeferredObligationForKeyRow, error) {
	row := q.db.QueryRow(ctx, reopenDeferredObligationForKey, arg.TenantID, arg.IdempotencyKey)
	var i ReopenDeferredObligationForKeyRow
	err := row.Scan(
		&i.ObligationID,
		&i.Status,
		&i.DueAt,
		&i.RowVersion,
		&i.Changed,
	)
	return i, err
}

const reopenDeferredObligationForKeyWithDue = `-- name: ReopenDeferredObligationForKeyWithDue :one
WITH target AS MATERIALIZED (
  SELECT oi.obligation_id, oi.status, oi.due_at, oi.row_version,
         oi.target_type, oi.target_id, oi.protocol_version_id
  FROM obligation_instances oi
  WHERE oi.tenant_id = $1
    AND oi.idempotency_key = $2
  FOR UPDATE
), updated AS (
  UPDATE obligation_instances oi
  SET status = 'scheduled',
      batch_id = NULL,
      due_at = $3,
      window_start = $4,
      window_end = $5,
      row_version = oi.row_version + 1,
      updated_at = now()
  FROM target t
  WHERE oi.tenant_id = $1
    AND oi.obligation_id = t.obligation_id
    AND t.status = 'deferred'
    AND NOT EXISTS (
    SELECT 1
    FROM goats g
    JOIN protocol_versions pv
      ON pv.tenant_id = $1
     AND pv.protocol_version_id = t.protocol_version_id
    JOIN protocol_definitions pd
      ON pd.tenant_id = pv.tenant_id
     AND pd.protocol_id = pv.protocol_id
    WHERE t.target_type = 'goat'
      AND g.tenant_id = $1
      AND g.goat_id = t.target_id
      AND pd.category = 'vaccination'
      AND (
        g.lifecycle_status IN ('dead', 'sold', 'lost', 'culled', 'transferred', 'merged', 'inactive')
        OR g.merged_into_goat_id IS NOT NULL
        OR EXISTS (
          SELECT 1
          FROM vw_procurement_vaccination_excluded_goats ex
          WHERE ex.tenant_id = g.tenant_id
            AND ex.goat_id = g.goat_id
        )
      )
    )
  RETURNING oi.obligation_id::text AS obligation_id, oi.status, oi.due_at, oi.row_version
)
SELECT obligation_id, status, due_at, row_version, true AS changed FROM updated
UNION ALL
SELECT t.obligation_id::text, t.status, t.due_at, t.row_version, false AS changed
FROM target t
WHERE NOT EXISTS (SELECT 1 FROM updated)
LIMIT 1
`

type ReopenDeferredObligationForKeyWithDueParams struct {
	TenantID               pgtype.UUID
	IdempotencyKey         string
	RescheduledDueAt       pgtype.Timestamptz
	RescheduledWindowStart pgtype.Timestamptz
	RescheduledWindowEnd   pgtype.Timestamptz
}

type ReopenDeferredObligationForKeyWithDueRow struct {
	ObligationID string
	Status       string
	DueAt        pgtype.Timestamptz
	RowVersion   int32
	Changed      bool
}

// Health recovery replan: reopen a held obligation and slide due_at to a nearby planned drive date
// or to recovery time for an immediate micro-drive. Clears batch_id so the sweeper re-attaches.
func (q *Queries) ReopenDeferredObligationForKeyWithDue(ctx context.Context, arg ReopenDeferredObligationForKeyWithDueParams) (ReopenDeferredObligationForKeyWithDueRow, error) {
	row := q.db.QueryRow(ctx, reopenDeferredObligationForKeyWithDue,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.RescheduledDueAt,
		arg.RescheduledWindowStart,
		arg.RescheduledWindowEnd,
	)
	var i ReopenDeferredObligationForKeyWithDueRow
	err := row.Scan(
		&i.ObligationID,
		&i.Status,
		&i.DueAt,
		&i.RowVersion,
		&i.Changed,
	)
	return i, err
}

const reopenObligation = `-- name: ReopenObligation :execrows
UPDATE obligation_instances
SET status = 'due', completed_at = NULL, row_version = row_version + 1, updated_at = now()
WHERE tenant_id = $1
  AND obligation_id = $2
  AND status = 'completed'
`

type ReopenObligationParams struct {
	TenantID     pgtype.UUID
	ObligationID pgtype.UUID
}

// Verification rejection reopens a completion's obligation back to outstanding work (maintainer
// state-model: the obligation axis reopens on rejection, mirroring MarkObligationCompleted's close
// on record). Only a genuinely-completed row is reopened -- an obligation waived/canceled/superseded
// by an unrelated process is never resurrected by a stale reject replay. completed_at is cleared so
// IsCompleted/read models agree the obligation is open again.
func (q *Queries) ReopenObligation(ctx context.Context, arg ReopenObligationParams) (int64, error) {
	result, err := q.db.Exec(ctx, reopenObligation, arg.TenantID, arg.ObligationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleOpenObligationByID = `-- name: RescheduleOpenObligationByID :one
UPDATE obligation_instances oi
SET due_at = $1,
    window_start = $2,
    window_end = $3,
    status = 'scheduled',
    row_version = row_version + 1,
    updated_at = now()
WHERE oi.tenant_id = $4
  AND oi.obligation_id = $5
  AND oi.status IN ('scheduled', 'due')
RETURNING oi.obligation_id::text AS obligation_id
`

type RescheduleOpenObligationByIDParams struct {
	DueAt        pgtype.Timestamptz
	WindowStart  pgtype.Timestamptz
	WindowEnd    pgtype.Timestamptz
	TenantID     pgtype.UUID
	ObligationID pgtype.UUID
}

// Mobile "reschedule this obligation" write path: moves a still-OPEN, not-yet-closed obligation
// (scheduled/due) to a new due date, scoped by obligation_id rather than by idempotency_key like the
// health-recovery reopen queries above. 'deferred' (health hold) is deliberately excluded — that status
// stays exclusively owned by ReopenDeferredObligationForKey(WithDue); this path can never reach a
// health-held row. 'missed' is deliberately excluded too (state-machines.md §"Conventions": missed is
// immutable closed history, alongside completed/waived/canceled/superseded — a later policy correction
// must create new work, never rewrite the closed row): Repository.RescheduleObligationByID branches a
// 'missed' target to insertReworkObligationForMissed (a fresh INSERT via InsertObligationInstance)
// instead of calling this UPDATE. Terminal/in-flight statuses (completed, in_progress, proof_pending,
// verification_pending, rejected, blocked, canceled) are excluded too — none of those are
// reschedulable from the mobile app. The caller separately locks the row first and detaches batch_id
// when the obligation is still attached to a 'planned' batch, mirroring
// DeferOpenObligationByIdempotencyKey's detachPlannedBatch pattern, since a moved due date may no longer
// belong to that drive.
func (q *Queries) RescheduleOpenObligationByID(ctx context.Context, arg RescheduleOpenObligationByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, rescheduleOpenObligationByID,
		arg.DueAt,
		arg.WindowStart,
		arg.WindowEnd,
		arg.TenantID,
		arg.ObligationID,
	)
	var obligation_id string
	err := row.Scan(&obligation_id)
	return obligation_id, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO idempotency_keys (idempotency_key, tenant_id, scope, request_hash, status)
VALUES ($1, $2, $3, $4, 'started')
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING idempotency_key
`

type ReserveIdempotencyKeyParams struct {
	IdempotencyKey string
	TenantID       pgtype.UUID
	Scope          string
	RequestHash    string
}

// Reserve-before-insert guard for status events (cross-partition dedup). Returns the key on
// first claim; returns no row if already reserved (retry).
func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey,
		arg.IdempotencyKey,
		arg.TenantID,
		arg.Scope,
		arg.RequestHash,
	)
	var idempotency_key string
	err := row.Scan(&idempotency_key)
	return idempotency_key, err
}
