// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package obligationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countObligationsByScope = `-- name: CountObligationsByScope :one
SELECT COUNT(*)::bigint AS total
FROM obligation_instances
WHERE tenant_id = $1 AND scope_type = $2
  AND scope_id = $3 AND status = $4
`

type CountObligationsByScopeParams struct {
	TenantID  pgtype.UUID
	ScopeType string
	ScopeID   pgtype.UUID
	Status    string
}

// Per-scope rollup. Uses obligation_instances_scope_idx (tenant_id, scope_type, scope_id, status, due_at).
func (q *Queries) CountObligationsByScope(ctx context.Context, arg CountObligationsByScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countObligationsByScope,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Status,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findNearestPlannedBatchDate = `-- name: FindNearestPlannedBatchDate :one
SELECT b.planned_date
FROM obligation_batches b
WHERE b.tenant_id = $1
  AND b.protocol_version_id = $2
  AND b.session = $3
  AND b.status = 'planned'
  AND b.planned_date >= $4::date
  AND b.planned_date <= $5::date
  AND (
    ($6::uuid IS NOT NULL AND b.scope_type = 'shed' AND b.scope_id = $6)
    OR ($7::uuid IS NOT NULL AND b.scope_type = 'park' AND b.scope_id = $7)
  )
ORDER BY b.planned_date ASC
LIMIT 1
`

type FindNearestPlannedBatchDateParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
	Session           pgtype.Text
	FromDate          pgtype.Date
	ToDate            pgtype.Date
	ShedID            pgtype.UUID
	ParkID            pgtype.UUID
}

// Sick-recovery align: earliest planned drive for this rule in shed or park within the align window.
func (q *Queries) FindNearestPlannedBatchDate(ctx context.Context, arg FindNearestPlannedBatchDateParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, findNearestPlannedBatchDate,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.Session,
		arg.FromDate,
		arg.ToDate,
		arg.ShedID,
		arg.ParkID,
	)
	var planned_date pgtype.Date
	err := row.Scan(&planned_date)
	return planned_date, err
}

const getObligationBoosterContext = `-- name: GetObligationBoosterContext :one
SELECT protocol_version_id::text AS protocol_version_id,
       scope_type, COALESCE(scope_id::text, '')::text AS scope_id, "sequence"
FROM obligation_instances
WHERE tenant_id = $1 AND obligation_id = $2
`

type GetObligationBoosterContextParams struct {
	TenantID     pgtype.UUID
	ObligationID pgtype.UUID
}

type GetObligationBoosterContextRow struct {
	ProtocolVersionID string
	ScopeType         string
	ScopeID           string
	Sequence          int32
}

// SM-7 basis on the verify path: the obligation's version + scope + sequence, looked up by PK
// (obligation_instances_tenant_id_unique) so the booster can schedule the next dose without the
// caller threading protocol context through the verification event.
func (q *Queries) GetObligationBoosterContext(ctx context.Context, arg GetObligationBoosterContextParams) (GetObligationBoosterContextRow, error) {
	row := q.db.QueryRow(ctx, getObligationBoosterContext, arg.TenantID, arg.ObligationID)
	var i GetObligationBoosterContextRow
	err := row.Scan(
		&i.ProtocolVersionID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Sequence,
	)
	return i, err
}

const getObligationByIdempotencyKey = `-- name: GetObligationByIdempotencyKey :one
SELECT obligation_id::text AS obligation_id, status, due_at, row_version
FROM obligation_instances
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetObligationByIdempotencyKeyParams struct {
	TenantID       pgtype.UUID
	IdempotencyKey string
}

type GetObligationByIdempotencyKeyRow struct {
	ObligationID string
	Status       string
	DueAt        pgtype.Timestamptz
	RowVersion   int32
}

func (q *Queries) GetObligationByIdempotencyKey(ctx context.Context, arg GetObligationByIdempotencyKeyParams) (GetObligationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getObligationByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i GetObligationByIdempotencyKeyRow
	err := row.Scan(
		&i.ObligationID,
		&i.Status,
		&i.DueAt,
		&i.RowVersion,
	)
	return i, err
}

const idempotencyKeyStatus = `-- name: IdempotencyKeyStatus :one
SELECT status, COALESCE(result_type, '')::text AS result_type, COALESCE(result_id::text, '')::text AS result_id
FROM idempotency_keys
WHERE idempotency_key = $1
`

type IdempotencyKeyStatusRow struct {
	Status     string
	ResultType string
	ResultID   string
}

func (q *Queries) IdempotencyKeyStatus(ctx context.Context, idempotencyKey string) (IdempotencyKeyStatusRow, error) {
	row := q.db.QueryRow(ctx, idempotencyKeyStatus, idempotencyKey)
	var i IdempotencyKeyStatusRow
	err := row.Scan(&i.Status, &i.ResultType, &i.ResultID)
	return i, err
}

const listDueObligations = `-- name: ListDueObligations :many
SELECT obligation_id::text AS obligation_id, protocol_version_id::text AS protocol_version_id,
       rule_id::text AS rule_id, target_type, target_id::text AS target_id,
       scope_type, COALESCE(scope_id::text, '')::text AS scope_id, due_at, status
FROM obligation_instances
WHERE tenant_id = $1 AND status = $2 AND due_at <= $3
ORDER BY due_at ASC, obligation_id ASC
LIMIT $4
`

type ListDueObligationsParams struct {
	TenantID  pgtype.UUID
	Status    string
	DueBefore pgtype.Timestamptz
	RowLimit  int32
}

type ListDueObligationsRow struct {
	ObligationID      string
	ProtocolVersionID string
	RuleID            string
	TargetType        string
	TargetID          string
	ScopeType         string
	ScopeID           string
	DueAt             pgtype.Timestamptz
	Status            string
}

// Due-window scan. Uses obligation_instances_due_window_idx (tenant_id, status, due_at, obligation_id).
func (q *Queries) ListDueObligations(ctx context.Context, arg ListDueObligationsParams) ([]ListDueObligationsRow, error) {
	rows, err := q.db.Query(ctx, listDueObligations,
		arg.TenantID,
		arg.Status,
		arg.DueBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueObligationsRow
	for rows.Next() {
		var i ListDueObligationsRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.ProtocolVersionID,
			&i.RuleID,
			&i.TargetType,
			&i.TargetID,
			&i.ScopeType,
			&i.ScopeID,
			&i.DueAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenObligationsByGoat = `-- name: ListOpenObligationsByGoat :many
SELECT obligation_id::text AS obligation_id, protocol_version_id::text AS protocol_version_id,
       rule_id::text AS rule_id, scope_type, COALESCE(scope_id::text, '')::text AS scope_id,
       COALESCE(batch_id::text, '')::text AS batch_id, due_at, status, "sequence"
FROM obligation_instances
WHERE tenant_id = $1 AND target_type = 'goat' AND target_id = $2
  AND status IN ('scheduled', 'due', 'in_progress', 'deferred', 'missed')
ORDER BY due_at ASC, obligation_id ASC
LIMIT $3
`

type ListOpenObligationsByGoatParams struct {
	TenantID pgtype.UUID
	TargetID pgtype.UUID
	RowLimit int32
}

type ListOpenObligationsByGoatRow struct {
	ObligationID      string
	ProtocolVersionID string
	RuleID            string
	ScopeType         string
	ScopeID           string
	BatchID           string
	DueAt             pgtype.Timestamptz
	Status            string
	Sequence          int32
}

// Goat Passport next-due: a goat's still-actionable obligations, earliest due first. Uses
// obligation_instances_target_idx (tenant_id, target_type, target_id, status).
func (q *Queries) ListOpenObligationsByGoat(ctx context.Context, arg ListOpenObligationsByGoatParams) ([]ListOpenObligationsByGoatRow, error) {
	rows, err := q.db.Query(ctx, listOpenObligationsByGoat, arg.TenantID, arg.TargetID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenObligationsByGoatRow
	for rows.Next() {
		var i ListOpenObligationsByGoatRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.ProtocolVersionID,
			&i.RuleID,
			&i.ScopeType,
			&i.ScopeID,
			&i.BatchID,
			&i.DueAt,
			&i.Status,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnbatchedDueForVersion = `-- name: ListUnbatchedDueForVersion :many
SELECT oi.obligation_id::text AS obligation_id,
       oi.rule_id::text AS rule_id,
       oi.scope_type,
       COALESCE(oi.scope_id::text, '')::text AS scope_id,
       COALESCE(oi.target_id::text, '')::text AS target_id,
       CASE
         WHEN oi.target_type = 'goat' THEN COALESCE(g.species, 'goat')::text
         ELSE ''
       END AS target_species,
       CASE
         WHEN oi.target_type = 'goat' THEN COALESCE(asl.stage_code, g.management_stage, '')::text
         ELSE ''
       END AS target_animal_stage,
       CASE
         WHEN oi.target_type = 'goat' THEN COALESCE(g.reproductive_status, '')::text
         ELSE ''
       END AS target_reproductive_status,
       oi.due_at,
       oi.window_start,
       oi.window_end,
       COALESCE(oi.batching_hold_count, 0)::int AS batching_hold_count,
       oi.first_batching_hold_until
FROM obligation_instances oi
LEFT JOIN goats g
  ON g.tenant_id = oi.tenant_id
 AND g.goat_id = oi.target_id
 AND oi.target_type = 'goat'
LEFT JOIN location_operational_attributes loa
  ON loa.tenant_id = g.tenant_id
 AND loa.location_id = g.current_location_id
LEFT JOIN shed_profiles sp
  ON sp.tenant_id = g.tenant_id
 AND sp.location_id = COALESCE(g.shed_id, CASE WHEN oi.scope_type = 'shed' THEN oi.scope_id END)
LEFT JOIN animal_stage_lookup asl
  ON asl.tenant_id = sp.tenant_id
 AND asl.animal_stage_id = sp.animal_stage_id
 AND asl.status = 'active'
WHERE oi.tenant_id = $1
  AND oi.protocol_version_id = $2
  AND oi.status IN ('scheduled', 'due', 'missed')
  AND oi.batch_id IS NULL
  AND oi.due_at <= $3
  AND (
    oi.target_type <> 'goat'
    OR (
      g.goat_id IS NOT NULL
      AND g.lifecycle_status = 'alive'
      AND COALESCE(g.health_status, '') NOT IN ('sick', 'under_treatment', 'quarantine', 'icu')
      AND COALESCE(loa.usable_for_vaccination, true)
      AND NOT COALESCE(loa.is_quarantine, false)
      AND NOT COALESCE(loa.is_icu, false)
    )
  )
ORDER BY oi.scope_type, oi.scope_id, oi.rule_id, target_species, target_animal_stage, oi.due_at, oi.obligation_id
LIMIT $4
`

type ListUnbatchedDueForVersionParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
	DueBefore         pgtype.Timestamptz
	RowLimit          int32
}

type ListUnbatchedDueForVersionRow struct {
	ObligationID             string
	RuleID                   string
	ScopeType                string
	ScopeID                  string
	TargetID                 string
	TargetSpecies            string
	TargetAnimalStage        string
	TargetReproductiveStatus string
	DueAt                    pgtype.Timestamptz
	WindowStart              pgtype.Timestamptz
	WindowEnd                pgtype.Timestamptz
	BatchingHoldCount        int32
	FirstBatchingHoldUntil   pgtype.Timestamptz
}

// SM-4 sweeper: unbatched scheduled/due obligations for a version within the window, grouped by
// scope + rule + due/window downstream. batch_id IS NULL makes re-sweeps idempotent.
// Uses obligation_instances_unbatched_due_version_idx.
func (q *Queries) ListUnbatchedDueForVersion(ctx context.Context, arg ListUnbatchedDueForVersionParams) ([]ListUnbatchedDueForVersionRow, error) {
	rows, err := q.db.Query(ctx, listUnbatchedDueForVersion,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.DueBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnbatchedDueForVersionRow
	for rows.Next() {
		var i ListUnbatchedDueForVersionRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.RuleID,
			&i.ScopeType,
			&i.ScopeID,
			&i.TargetID,
			&i.TargetSpecies,
			&i.TargetAnimalStage,
			&i.TargetReproductiveStatus,
			&i.DueAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.BatchingHoldCount,
			&i.FirstBatchingHoldUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
