package postgres

import (
	"strings"
	"testing"
	"time"

	"github.com/vgoats/goatos/backend/internal/herdsignals/domain"
)

func TestLiveSortCursorIsOpaqueAndRoundTrips(t *testing.T) {
	temp := 27.5
	tag := domain.TagLatest{
		TagID:           strings.Repeat("x", 128),
		TagTemperatureC: &temp,
		LastSeenAt:      time.Date(2026, 9, 12, 8, 0, 0, 0, time.UTC),
	}
	spec := normalizeLiveSort([]domain.LiveSort{{Key: "tag_temp", Dir: "desc"}})

	cursor := liveCursorFromTag(tag, spec)
	if len(cursor) <= 200 {
		t.Fatalf("cursor length = %d, want a backend-shaped cursor that proves the frontend must allow >200 chars", len(cursor))
	}

	decoded, ok := decodeLiveCursor(cursor, spec)
	if !ok {
		t.Fatal("decodeLiveCursor rejected a cursor generated by liveCursorFromTag")
	}
	if decoded.Key != "tag_temp" || decoded.Dir != "desc" || decoded.TagID != tag.TagID || decoded.Value != "27.5" || decoded.Null {
		t.Fatalf("decoded cursor = %+v", decoded)
	}
}

func TestDefaultLiveSortKeepsLegacyCursorShape(t *testing.T) {
	spec := normalizeLiveSort(nil)
	if !spec.defaultKey {
		t.Fatal("default/no-sort callers must keep the legacy last_seen/tag_id pagination path")
	}
	if _, ok := decodeLiveCursor("legacy-tag-id", spec); ok {
		t.Fatal("legacy tag-id cursors must not be treated as opaque v1 cursors")
	}
}
