org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
goatosDevBearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb2F0b3MtYXBpIiwiZXhwIjoxNzg2MjE0NTIyLCJpc3MiOiJnb2F0b3MtbG9jYWwiLCJuYmYiOjE3ODYxMjgwNjIsInN1YiI6IjkwMDAwMDAwLTAwMDAtNDAwMC04MDAwLTAwMDAwMDAwMDEwMSIsInRlbmFudF9pZCI6IjAwMDAwMDAwLTAwMDAtNDAwMC04MDAwLTAwMDAwMDAwMDAwMSJ9._ZfOJJcs3AtLLGbtUexXJI2ACOunYxgNlMiFOkDUJJs
