// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package protocoldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProtocolDefinition = `-- name: CreateProtocolDefinition :one
INSERT INTO protocol_definitions (tenant_id, code, name, category, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING protocol_id::text AS protocol_id
`

type CreateProtocolDefinitionParams struct {
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Category  string
	Status    string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateProtocolDefinition(ctx context.Context, arg CreateProtocolDefinitionParams) (string, error) {
	row := q.db.QueryRow(ctx, createProtocolDefinition,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.CreatedBy,
	)
	var protocol_id string
	err := row.Scan(&protocol_id)
	return protocol_id, err
}

const createProtocolRule = `-- name: CreateProtocolRule :one
INSERT INTO protocol_rules (
  tenant_id, protocol_version_id, dose_code, "sequence", trigger_type, offset_days,
  due_window_days, min_gap_days, "repeat", repeat_until_after_age, catch_up,
  eligibility_json, sop_version_id, proof_policy, withdrawal_days, sort_order
) SELECT
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11,
  $12, $13, $14, $15, $16
FROM protocol_versions pv
WHERE pv.tenant_id = $1
  AND pv.protocol_version_id = $2
  AND pv.status = 'draft'
RETURNING rule_id::text AS rule_id
`

type CreateProtocolRuleParams struct {
	TenantID            pgtype.UUID
	ProtocolVersionID   pgtype.UUID
	DoseCode            string
	Sequence            int32
	TriggerType         string
	OffsetDays          int32
	DueWindowDays       int32
	MinGapDays          int32
	Repeat              string
	RepeatUntilAfterAge pgtype.Text
	CatchUp             string
	EligibilityJson     []byte
	SopVersionID        pgtype.UUID
	ProofPolicy         []byte
	WithdrawalDays      pgtype.Int4
	SortOrder           int32
}

func (q *Queries) CreateProtocolRule(ctx context.Context, arg CreateProtocolRuleParams) (string, error) {
	row := q.db.QueryRow(ctx, createProtocolRule,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.DoseCode,
		arg.Sequence,
		arg.TriggerType,
		arg.OffsetDays,
		arg.DueWindowDays,
		arg.MinGapDays,
		arg.Repeat,
		arg.RepeatUntilAfterAge,
		arg.CatchUp,
		arg.EligibilityJson,
		arg.SopVersionID,
		arg.ProofPolicy,
		arg.WithdrawalDays,
		arg.SortOrder,
	)
	var rule_id string
	err := row.Scan(&rule_id)
	return rule_id, err
}

const createProtocolTrigger = `-- name: CreateProtocolTrigger :one
INSERT INTO protocol_triggers (tenant_id, protocol_version_id, trigger_type, trigger_config, is_active)
SELECT $1, $2, $3, $4, $5
FROM protocol_versions pv
WHERE pv.tenant_id = $1
  AND pv.protocol_version_id = $2
  AND pv.status = 'draft'
RETURNING trigger_id::text AS trigger_id
`

type CreateProtocolTriggerParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
	TriggerType       string
	TriggerConfig     []byte
	IsActive          bool
}

func (q *Queries) CreateProtocolTrigger(ctx context.Context, arg CreateProtocolTriggerParams) (string, error) {
	row := q.db.QueryRow(ctx, createProtocolTrigger,
		arg.TenantID,
		arg.ProtocolVersionID,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.IsActive,
	)
	var trigger_id string
	err := row.Scan(&trigger_id)
	return trigger_id, err
}

const createProtocolVersion = `-- name: CreateProtocolVersion :one
INSERT INTO protocol_versions (
  tenant_id, protocol_id, scope_type, scope_id, version, version_label, status,
  effective_from, effective_to, rule_dsl, proof_policy, sop_version_id, drafted_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13
)
RETURNING protocol_version_id::text AS protocol_version_id
`

type CreateProtocolVersionParams struct {
	TenantID      pgtype.UUID
	ProtocolID    pgtype.UUID
	ScopeType     string
	ScopeID       pgtype.UUID
	Version       int32
	VersionLabel  string
	Status        string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	RuleDsl       []byte
	ProofPolicy   []byte
	SopVersionID  pgtype.UUID
	DraftedBy     pgtype.UUID
}

func (q *Queries) CreateProtocolVersion(ctx context.Context, arg CreateProtocolVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, createProtocolVersion,
		arg.TenantID,
		arg.ProtocolID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Version,
		arg.VersionLabel,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.RuleDsl,
		arg.ProofPolicy,
		arg.SopVersionID,
		arg.DraftedBy,
	)
	var protocol_version_id string
	err := row.Scan(&protocol_version_id)
	return protocol_version_id, err
}

const discardProtocolVersion = `-- name: DiscardProtocolVersion :execrows
DELETE FROM protocol_versions
WHERE tenant_id = $1
  AND protocol_version_id = $2
  AND status = 'draft'
`

type DiscardProtocolVersionParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
}

// Deletes a DRAFT version and, by cascade, its rules. The status predicate is the
// safety property: a published or retired version can never be removed by this
// statement, so history stays complete no matter what id is supplied. A draft has
// never reached the field -- no obligation references it -- so deleting it destroys
// only unpublished authoring work.
func (q *Queries) DiscardProtocolVersion(ctx context.Context, arg DiscardProtocolVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardProtocolVersion, arg.TenantID, arg.ProtocolVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishProtocolVersion = `-- name: PublishProtocolVersion :execrows
UPDATE protocol_versions
SET status = 'published',
    published_by = $1,
    published_at = now(),
    row_version = row_version + 1,
    updated_at = now()
WHERE tenant_id = $2
  AND protocol_version_id = $3
  AND status = 'draft'
`

type PublishProtocolVersionParams struct {
	PublishedBy       pgtype.UUID
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
}

// Status flip only; executable-contract checks are enforced in the app layer.
func (q *Queries) PublishProtocolVersion(ctx context.Context, arg PublishProtocolVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishProtocolVersion, arg.PublishedBy, arg.TenantID, arg.ProtocolVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
