// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package protocoldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProtocolDefinitionByCode = `-- name: GetProtocolDefinitionByCode :one
SELECT protocol_id::text AS protocol_id, code, name, category, status, row_version
FROM protocol_definitions
WHERE tenant_id = $1 AND code = $2
`

type GetProtocolDefinitionByCodeParams struct {
	TenantID pgtype.UUID
	Code     string
}

type GetProtocolDefinitionByCodeRow struct {
	ProtocolID string
	Code       string
	Name       string
	Category   string
	Status     string
	RowVersion int32
}

func (q *Queries) GetProtocolDefinitionByCode(ctx context.Context, arg GetProtocolDefinitionByCodeParams) (GetProtocolDefinitionByCodeRow, error) {
	row := q.db.QueryRow(ctx, getProtocolDefinitionByCode, arg.TenantID, arg.Code)
	var i GetProtocolDefinitionByCodeRow
	err := row.Scan(
		&i.ProtocolID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.RowVersion,
	)
	return i, err
}

const getProtocolVersion = `-- name: GetProtocolVersion :one
SELECT protocol_version_id::text AS protocol_version_id, protocol_id::text AS protocol_id,
       scope_type, COALESCE(scope_id::text, '')::text AS scope_id, version, status,
       effective_from, effective_to, rule_dsl, proof_policy, row_version
FROM protocol_versions
WHERE tenant_id = $1 AND protocol_version_id = $2
`

type GetProtocolVersionParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
}

type GetProtocolVersionRow struct {
	ProtocolVersionID string
	ProtocolID        string
	ScopeType         string
	ScopeID           string
	Version           int32
	Status            string
	EffectiveFrom     pgtype.Date
	EffectiveTo       pgtype.Date
	RuleDsl           []byte
	ProofPolicy       []byte
	RowVersion        int32
}

func (q *Queries) GetProtocolVersion(ctx context.Context, arg GetProtocolVersionParams) (GetProtocolVersionRow, error) {
	row := q.db.QueryRow(ctx, getProtocolVersion, arg.TenantID, arg.ProtocolVersionID)
	var i GetProtocolVersionRow
	err := row.Scan(
		&i.ProtocolVersionID,
		&i.ProtocolID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Version,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.RuleDsl,
		&i.ProofPolicy,
		&i.RowVersion,
	)
	return i, err
}

const listPublishedVersionsForProtocol = `-- name: ListPublishedVersionsForProtocol :many
SELECT protocol_version_id::text AS protocol_version_id, scope_type,
       COALESCE(scope_id::text, '')::text AS scope_id, version, effective_from, effective_to
FROM protocol_versions
WHERE tenant_id = $1 AND protocol_id = $2 AND status = 'published'
ORDER BY effective_from DESC, protocol_version_id DESC
`

type ListPublishedVersionsForProtocolParams struct {
	TenantID   pgtype.UUID
	ProtocolID pgtype.UUID
}

type ListPublishedVersionsForProtocolRow struct {
	ProtocolVersionID string
	ScopeType         string
	ScopeID           string
	Version           int32
	EffectiveFrom     pgtype.Date
	EffectiveTo       pgtype.Date
}

func (q *Queries) ListPublishedVersionsForProtocol(ctx context.Context, arg ListPublishedVersionsForProtocolParams) ([]ListPublishedVersionsForProtocolRow, error) {
	rows, err := q.db.Query(ctx, listPublishedVersionsForProtocol, arg.TenantID, arg.ProtocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedVersionsForProtocolRow
	for rows.Next() {
		var i ListPublishedVersionsForProtocolRow
		if err := rows.Scan(
			&i.ProtocolVersionID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Version,
			&i.EffectiveFrom,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForVersion = `-- name: ListRulesForVersion :many
SELECT rule_id::text AS rule_id, dose_code, "sequence", trigger_type, offset_days,
       due_window_days, min_gap_days, "repeat", COALESCE(repeat_until_after_age, '')::text AS repeat_until_after_age,
       catch_up, sort_order
FROM protocol_rules
WHERE tenant_id = $1 AND protocol_version_id = $2
ORDER BY sort_order ASC, "sequence" ASC
`

type ListRulesForVersionParams struct {
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
}

type ListRulesForVersionRow struct {
	RuleID              string
	DoseCode            string
	Sequence            int32
	TriggerType         string
	OffsetDays          int32
	DueWindowDays       int32
	MinGapDays          int32
	Repeat              string
	RepeatUntilAfterAge string
	CatchUp             string
	SortOrder           int32
}

func (q *Queries) ListRulesForVersion(ctx context.Context, arg ListRulesForVersionParams) ([]ListRulesForVersionRow, error) {
	rows, err := q.db.Query(ctx, listRulesForVersion, arg.TenantID, arg.ProtocolVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesForVersionRow
	for rows.Next() {
		var i ListRulesForVersionRow
		if err := rows.Scan(
			&i.RuleID,
			&i.DoseCode,
			&i.Sequence,
			&i.TriggerType,
			&i.OffsetDays,
			&i.DueWindowDays,
			&i.MinGapDays,
			&i.Repeat,
			&i.RepeatUntilAfterAge,
			&i.CatchUp,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
