// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commands.sql

package inventorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustStockBalances = `-- name: AdjustStockBalances :exec
UPDATE inventory_stock
SET quantity_in_stock = quantity_in_stock + $1,
    quantity_reserved = quantity_reserved + $2,
    row_version = row_version + 1,
    updated_at = now()
WHERE tenant_id = $3 AND stock_id = $4
`

type AdjustStockBalancesParams struct {
	InDelta       pgtype.Numeric
	ReservedDelta pgtype.Numeric
	TenantID      pgtype.UUID
	StockID       pgtype.UUID
}

func (q *Queries) AdjustStockBalances(ctx context.Context, arg AdjustStockBalancesParams) error {
	_, err := q.db.Exec(ctx, adjustStockBalances,
		arg.InDelta,
		arg.ReservedDelta,
		arg.TenantID,
		arg.StockID,
	)
	return err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (tenant_id, item_code, name, category, base_unit, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING item_id::text AS item_id
`

type CreateInventoryItemParams struct {
	TenantID pgtype.UUID
	ItemCode string
	Name     string
	Category string
	BaseUnit string
	Status   string
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (string, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.TenantID,
		arg.ItemCode,
		arg.Name,
		arg.Category,
		arg.BaseUnit,
		arg.Status,
	)
	var item_id string
	err := row.Scan(&item_id)
	return item_id, err
}

const createInventoryStockLot = `-- name: CreateInventoryStockLot :one
INSERT INTO inventory_stock (
  tenant_id, item_id, location_id, lot_code, expiry_date,
  quantity_in_stock, quantity_reserved, quantity_unit, status
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING stock_id::text AS stock_id
`

type CreateInventoryStockLotParams struct {
	TenantID         pgtype.UUID
	ItemID           pgtype.UUID
	LocationID       pgtype.UUID
	LotCode          pgtype.Text
	ExpiryDate       pgtype.Date
	QuantityInStock  pgtype.Numeric
	QuantityReserved pgtype.Numeric
	QuantityUnit     string
	Status           string
}

func (q *Queries) CreateInventoryStockLot(ctx context.Context, arg CreateInventoryStockLotParams) (string, error) {
	row := q.db.QueryRow(ctx, createInventoryStockLot,
		arg.TenantID,
		arg.ItemID,
		arg.LocationID,
		arg.LotCode,
		arg.ExpiryDate,
		arg.QuantityInStock,
		arg.QuantityReserved,
		arg.QuantityUnit,
		arg.Status,
	)
	var stock_id string
	err := row.Scan(&stock_id)
	return stock_id, err
}

const insertStockMovement = `-- name: InsertStockMovement :one
INSERT INTO inventory_stock_movements (
  tenant_id, lot_id, item_id, location_id, movement_type,
  quantity, quantity_unit, batch_id, actor_id, reason, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10, $11
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING movement_id::text AS movement_id
`

type InsertStockMovementParams struct {
	TenantID       pgtype.UUID
	LotID          pgtype.UUID
	ItemID         pgtype.UUID
	LocationID     pgtype.UUID
	MovementType   string
	Quantity       pgtype.Numeric
	QuantityUnit   string
	BatchID        pgtype.UUID
	ActorID        pgtype.UUID
	Reason         pgtype.Text
	IdempotencyKey string
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStockMovement,
		arg.TenantID,
		arg.LotID,
		arg.ItemID,
		arg.LocationID,
		arg.MovementType,
		arg.Quantity,
		arg.QuantityUnit,
		arg.BatchID,
		arg.ActorID,
		arg.Reason,
		arg.IdempotencyKey,
	)
	var movement_id string
	err := row.Scan(&movement_id)
	return movement_id, err
}
