// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package inventorydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUiConfigEntry struct {
	TenantID    pgtype.UUID
	Locale      string
	RouteID     string
	ConfigKey   string
	ConfigValue string
	ValueKind   string
	Status      string
	Metadata    []byte
	RowVersion  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AdminUiConfigFamilyChangeQueue struct {
	TransactionID int64
	TenantID      pgtype.UUID
	FamilyKey     string
	ChangedBy     pgtype.UUID
	Source        string
	Metadata      []byte
	ChangeCount   int32
	QueuedAt      pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AdminUiConfigFamilyRevision struct {
	TenantID    pgtype.UUID
	FamilyKey   string
	Revision    int64
	ContentHash string
	ChangedAt   pgtype.Timestamptz
	ChangedBy   pgtype.UUID
	Source      string
	Metadata    []byte
}

type AnimalStageLookup struct {
	AnimalStageID pgtype.UUID
	TenantID      pgtype.UUID
	StageCode     string
	Name          string
	MinAgeDays    pgtype.Int4
	MaxAgeDays    pgtype.Int4
	SortOrder     int32
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ArrivalIntakeReview struct {
	ReviewID       pgtype.UUID
	TenantID       pgtype.UUID
	LoadID         pgtype.UUID
	ParkLocationID pgtype.UUID
	ExpectedCount  int32
	LoadedCount    int32
	ArrivedCount   int32
	MatchedCount   int32
	MissingCount   int32
	ExtraCount     int32
	RejectedCount  int32
	HealthFlags    []byte
	WeightFlags    []byte
	MediaProofID   pgtype.UUID
	Status         string
	ReviewedBy     pgtype.UUID
	ReviewedAt     pgtype.Timestamptz
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RowVersion     int32
}

type ArrivalIntakeReviewGoat struct {
	ReviewGoatID      pgtype.UUID
	TenantID          pgtype.UUID
	ReviewID          pgtype.UUID
	LoadID            pgtype.UUID
	GoatID            pgtype.UUID
	AnimalIdentifier2 pgtype.Text
	AnimalIdentifier1 pgtype.Text
	ItemKey           string
	ArrivalState      string
	HealthFlag        pgtype.Text
	WeightFlag        pgtype.Text
	ProofRefID        pgtype.UUID
	Notes             string
	CreatedAt         pgtype.Timestamptz
}

type AuditLog struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202606 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202607 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202608 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLog202609 struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuditLogDefault struct {
	AuditID      pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	ScopeType    pgtype.Text
	ScopeID      pgtype.UUID
	DecisionID   pgtype.UUID
	BeforeState  []byte
	AfterState   []byte
	Metadata     []byte
	TraceID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
}

type AuthPendingEmailGrant struct {
	PendingGrantID             pgtype.UUID
	TenantID                   pgtype.UUID
	Email                      string
	NormalizedEmail            string
	Role                       string
	ScopeType                  string
	ScopeID                    pgtype.UUID
	Status                     string
	ValidFrom                  pgtype.Timestamptz
	ValidTo                    pgtype.Timestamptz
	Source                     string
	CreatedBy                  pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	LastClaimedUserID          pgtype.UUID
	LastClaimedExternalSubject pgtype.Text
	LastClaimedAt              pgtype.Timestamptz
	ClaimCount                 int64
	Metadata                   []byte
}

type Breed struct {
	BreedID       pgtype.UUID
	Species       string
	CanonicalName string
	Status        string
	ReviewNotes   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type BreedAlias struct {
	AliasID         pgtype.UUID
	BreedID         pgtype.UUID
	Alias           string
	NormalizedAlias string
	SourceSystem    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type CalendarEventIdentity struct {
	TenantID         pgtype.UUID
	EventID          string
	SliceKey         string
	SourceTargetType pgtype.Text
	SourceTargetID   pgtype.UUID
	FirstSeenAt      pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
}

type CalendarEventProjection struct {
	TenantID                   pgtype.UUID
	EventID                    string
	SliceKey                   string
	EventType                  string
	OwnerKey                   string
	Title                      string
	Subtitle                   string
	Status                     string
	Severity                   string
	DueAt                      pgtype.Timestamptz
	WindowStart                pgtype.Timestamptz
	WindowEnd                  pgtype.Timestamptz
	Timezone                   string
	TimezoneSource             string
	ParkID                     pgtype.UUID
	ParkCode                   pgtype.Text
	ShedID                     pgtype.UUID
	ShedName                   pgtype.Text
	CohortID                   pgtype.UUID
	CohortName                 pgtype.Text
	TargetType                 string
	TargetCount                int32
	ProtocolID                 pgtype.UUID
	ProtocolVersionID          pgtype.UUID
	RuleID                     pgtype.UUID
	VaccineName                pgtype.Text
	DoseCode                   pgtype.Text
	SourceBacked               bool
	SourceLabel                string
	SourceTargetType           string
	SourceTargetID             pgtype.UUID
	AssigneeLabel              pgtype.Text
	ExecutorRole               pgtype.Text
	VerifierLabel              pgtype.Text
	ReminderState              string
	PrimaryNotificationChannel string
	EscalationState            string
	System                     bool
	CrossCutting               bool
	Links                      []byte
	Detail                     []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type CalendarSnooze struct {
	SnoozeID           pgtype.UUID
	TenantID           pgtype.UUID
	CalendarEventID    string
	TargetType         string
	TargetID           pgtype.UUID
	SnoozeUntil        pgtype.Timestamptz
	Reason             string
	Status             string
	CreatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	ReplacedBySnoozeID pgtype.UUID
	IdempotencyKey     string
	RequestFingerprint string
	Context            []byte
	TraceID            pgtype.Text
}

type CountBaseAnchor struct {
	BaseCountAnchorID  pgtype.UUID
	TenantID           pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	BreedID            pgtype.UUID
	BreedKey           string
	BreedLabel         string
	CountedAt          pgtype.Timestamptz
	HeadCount          int32
	SourceSystem       string
	SourceRef          string
	SourceHash         string
	AnchorState        string
	DiscrepancyState   string
	IdempotencyKey     string
	RequestFingerprint string
	RecordedBy         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	RowVersion         int32
}

type CountDimensionAlias struct {
	AliasID         pgtype.UUID
	TenantID        pgtype.UUID
	Dimension       string
	SourceSystem    string
	SourceValue     string
	SourceValueNorm string
	CanonicalValue  string
	CanonicalLabel  pgtype.Text
	ReviewStatus    string
	SourceRef       string
	SourceHash      string
	ApprovedBy      pgtype.UUID
	ApprovedAt      pgtype.Timestamptz
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	RowVersion      int32
}

type CountMismatchScanRun struct {
	CountMismatchScanRunID   pgtype.UUID
	TenantID                 pgtype.UUID
	ParkID                   pgtype.UUID
	ShedID                   pgtype.UUID
	CountedAfter             pgtype.Timestamptz
	CountedBefore            pgtype.Timestamptz
	CursorCountedAt          pgtype.Timestamptz
	CursorAnchorID           pgtype.UUID
	Status                   string
	StartedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	ScannedAnchorCount       int32
	ExceptionWriteCount      int32
	InvestigatingAnchorCount int32
	NextCursorCountedAt      pgtype.Timestamptz
	NextCursorAnchorID       pgtype.UUID
	LastError                pgtype.Text
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	RowVersion               int32
}

type CountProjectionException struct {
	CountProjectionExceptionID pgtype.UUID
	TenantID                   pgtype.UUID
	CountProjectionSnapshotID  pgtype.UUID
	ExceptionType              string
	SourceKey                  string
	GrainKey                   string
	ParkID                     pgtype.UUID
	ShedID                     pgtype.UUID
	BreedKey                   pgtype.Text
	StageTag                   pgtype.Text
	Severity                   string
	Status                     string
	OwnerRef                   pgtype.Text
	BlockerReason              string
	EvidenceJson               []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	ResolvedAt                 pgtype.Timestamptz
	WorkType                   string
	WorkState                  string
	DueAt                      pgtype.Timestamptz
	NextAction                 string
	EvidenceLink               string
	ResolutionID               pgtype.UUID
	ResolvedByRef              pgtype.Text
	ResolutionReason           pgtype.Text
	ResolutionRef              pgtype.Text
}

type CountProjectionExceptionResolution struct {
	CountProjectionExceptionResolutionID pgtype.UUID
	TenantID                             pgtype.UUID
	CountProjectionExceptionID           pgtype.UUID
	Action                               string
	ResolvedByRef                        string
	ResolutionReason                     string
	ResolutionRef                        pgtype.Text
	IdempotencyKey                       string
	RequestFingerprint                   string
	CreatedAt                            pgtype.Timestamptz
}

type CountProjectionRecomputeRun struct {
	CountProjectionRecomputeRunID pgtype.UUID
	TenantID                      pgtype.UUID
	ParkID                        pgtype.UUID
	Horizon                       string
	TargetDate                    pgtype.Date
	AsOf                          pgtype.Timestamptz
	Status                        string
	ProjectionStatus              pgtype.Text
	SnapshotID                    pgtype.UUID
	RowCount                      int32
	ExceptionCount                int32
	SourceContractVersion         string
	GeneratedBy                   string
	TraceID                       pgtype.Text
	LastError                     pgtype.Text
	StartedAt                     pgtype.Timestamptz
	CompletedAt                   pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
}

type CountProjectionSnapshot struct {
	CountProjectionSnapshotID pgtype.UUID
	TenantID                  pgtype.UUID
	Horizon                   string
	ParkID                    pgtype.UUID
	TargetDate                pgtype.Date
	AsOf                      pgtype.Timestamptz
	ProjectionStatus          string
	SourceContractVersion     string
	SourceHash                string
	BaseAnchorIdsHash         string
	ShiftingEventIdsHash      string
	RowCount                  int32
	ExceptionCount            int32
	GeneratedBy               string
	TraceID                   pgtype.Text
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	RowVersion                int32
}

type CountProjectionSnapshotRow struct {
	CountProjectionSnapshotRowID pgtype.UUID
	TenantID                     pgtype.UUID
	CountProjectionSnapshotID    pgtype.UUID
	ParkID                       pgtype.UUID
	ShedID                       pgtype.UUID
	TargetDate                   pgtype.Date
	GrainKey                     string
	BreedID                      pgtype.UUID
	BreedKey                     string
	BreedLabel                   string
	StageTag                     pgtype.Text
	AgeClass                     pgtype.Text
	Sex                          pgtype.Text
	HeadCount                    int32
	PregnantCount                int32
	LactatingCount               int32
	WarmupCount                  int32
	RationContextResolutionState string
	RationContextRef             pgtype.Text
	BlockerReason                pgtype.Text
	SourceRowHash                string
	CreatedAt                    pgtype.Timestamptz
	BaseCountAnchorID            pgtype.UUID
	IncludedShiftingEventIdsHash string
}

type CountSourceImportRun struct {
	CountSourceImportRunID pgtype.UUID
	TenantID               pgtype.UUID
	SourceSystem           string
	Mode                   string
	Status                 string
	SourceRef              pgtype.Text
	SourceRowsRead         int32
	BaseAnchorRows         int32
	ShiftingEventRows      int32
	ReplayCount            int32
	FailedRowCount         int32
	TraceID                pgtype.Text
	LastError              pgtype.Text
	StartedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type CountsShiftingReadinessEvidence struct {
	CountsShiftingReadinessEvidenceID pgtype.UUID
	TenantID                          pgtype.UUID
	SubgateID                         string
	Status                            string
	EvidenceRef                       string
	BlockerReason                     string
	ImplementationRef                 pgtype.Text
	RecordedAt                        pgtype.Timestamptz
}

type CountsShiftingReadinessSubgate struct {
	TenantID          pgtype.UUID
	SubgateID         string
	Status            string
	Owner             string
	EvidenceRef       string
	BlockerReason     string
	ImplementationRef pgtype.Text
	LastCheckedAt     pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DomainEventProcessedEvent struct {
	TenantID        pgtype.UUID
	SubscriptionID  string
	EventID         string
	EventType       string
	MessageID       string
	DeliveryAttempt int32
	Status          string
	AttemptCount    int32
	StartedAt       pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	LastError       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FarmProfile struct {
	LocationID pgtype.UUID
	TenantID   pgtype.UUID
	FarmKind   pgtype.Text
	Capacity   pgtype.Int4
	Notes      string
	Context    []byte
	RowVersion int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type FeedDirectionCompletion struct {
	CompletionID            pgtype.UUID
	TenantID                pgtype.UUID
	ObligationID            pgtype.UUID
	BatchID                 pgtype.UUID
	ShedID                  pgtype.UUID
	RationProtocolVersionID pgtype.UUID
	SopSubmissionItemID     pgtype.UUID
	FeedInventoryLotID      pgtype.UUID
	QuantityFed             pgtype.Numeric
	QuantityUnit            pgtype.Text
	HeadCount               pgtype.Int4
	FedAt                   pgtype.Timestamptz
	Status                  string
	VerifiedBy              pgtype.UUID
	VerifiedAt              pgtype.Timestamptz
	RejectionReason         pgtype.Text
	RecordedBy              pgtype.UUID
	IdempotencyKey          string
	RowVersion              int32
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type Goat struct {
	GoatID             pgtype.UUID
	TenantID           pgtype.UUID
	DisplayID          string
	Species            string
	Breed              pgtype.Text
	BreedID            pgtype.UUID
	Sex                string
	ApproxDob          pgtype.Date
	AgeBand            pgtype.Text
	LifecycleStatus    string
	ReproductiveStatus pgtype.Text
	GrowthCohortTag    pgtype.Text
	ManagementStage    pgtype.Text
	HealthStatus       pgtype.Text
	CustodianPartyID   pgtype.UUID
	CurrentLocationID  pgtype.UUID
	FarmID             pgtype.UUID
	ParkID             pgtype.UUID
	ShedID             pgtype.UUID
	CohortID           pgtype.UUID
	MergedIntoGoatID   pgtype.UUID
	RowVersion         int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	Dob                pgtype.Date
	DobEstimated       bool
	OriginType         pgtype.Text
	EntryDate          pgtype.Date
	ExitedAt           pgtype.Timestamptz
	ExitReason         pgtype.Text
}

type GoatCustodyHistory struct {
	CustodyHistoryID pgtype.UUID
	TenantID         pgtype.UUID
	GoatID           pgtype.UUID
	CustodianPartyID pgtype.UUID
	FromLocationID   pgtype.UUID
	ToLocationID     pgtype.UUID
	ValidFrom        pgtype.Timestamptz
	ValidTo          pgtype.Timestamptz
	DecisionID       pgtype.UUID
	Reason           pgtype.Text
	CreatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
}

type GoatIdentifier struct {
	IdentifierID      pgtype.UUID
	TenantID          pgtype.UUID
	GoatID            pgtype.UUID
	IdentifierType    string
	IdentifierValue   string
	NormalizedValue   string
	ScopeKey          string
	IsPrimaryForGoat  bool
	Status            string
	ValidFrom         pgtype.Timestamptz
	ValidTo           pgtype.Timestamptz
	SourceSystem      pgtype.Text
	SourceRecordID    pgtype.Text
	NormalizerVersion string
	Confidence        pgtype.Numeric
	ApprovedBy        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type GoatIdentityEvent struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202606 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202607 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202608 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEvents202609 struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatIdentityEventsDefault struct {
	IdentityEventID pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	EventType       string
	EventVersion    int32
	OccurredAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	SourceSystem    pgtype.Text
	SourceRecordID  pgtype.Text
	Payload         []byte
	DecisionID      pgtype.UUID
	IdempotencyKey  string
}

type GoatLocationHistory struct {
	LocationHistoryID pgtype.UUID
	TenantID          pgtype.UUID
	GoatID            pgtype.UUID
	FromLocationID    pgtype.UUID
	ToLocationID      pgtype.UUID
	Reason            pgtype.Text
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	SourceRecordID    pgtype.Text
}

type GoatMergeLink struct {
	MergeLinkID    pgtype.UUID
	TenantID       pgtype.UUID
	SurvivorGoatID pgtype.UUID
	MergedGoatID   pgtype.UUID
	DecisionID     pgtype.UUID
	Reason         string
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
}

type GoatOwnership struct {
	OwnershipID  pgtype.UUID
	TenantID     pgtype.UUID
	GoatID       pgtype.UUID
	OwnerPartyID pgtype.UUID
	ShareBps     int32
	ValidFrom    pgtype.Timestamptz
	ValidTo      pgtype.Timestamptz
	Status       string
	DecisionID   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
}

type IdempotencyKey struct {
	IdempotencyKey string
	TenantID       pgtype.UUID
	Scope          string
	RequestHash    string
	Status         string
	ResultType     pgtype.Text
	ResultID       pgtype.UUID
	FirstSeenAt    pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type IdentifierPolicy struct {
	PolicyVersion                   string
	IdentifierType                  string
	DefaultScopeType                string
	ScopeRequired                   bool
	ActiveUniqueness                string
	AutoLinkAllowed                 bool
	PrimaryAllowed                  bool
	UnknownScopeAction              string
	MissingOrConflictingScopeAction string
	NormalizerVersion               string
	FormatValidatorVersion          pgtype.Text
	InvalidValueAction              string
	CreatedAt                       pgtype.Timestamptz
	ApprovedBy                      pgtype.UUID
}

type IdentifierPolicyVersion struct {
	PolicyVersion string
	Status        string
	CreatedAt     pgtype.Timestamptz
	ApprovedAt    pgtype.Timestamptz
	ApprovedBy    pgtype.UUID
}

type IdentityConflict struct {
	ConflictID      pgtype.UUID
	TenantID        pgtype.UUID
	ConflictType    string
	Severity        string
	State           string
	IdentifierType  pgtype.Text
	IdentifierValue pgtype.Text
	GoatIds         []pgtype.UUID
	SourceRecordIds []string
	Evidence        []byte
	CreatedAt       pgtype.Timestamptz
	ResolvedAt      pgtype.Timestamptz
	ResolvedBy      pgtype.UUID
	DecisionID      pgtype.UUID
	RowVersion      int32
}

type IdentityConflictGoat struct {
	ConflictID pgtype.UUID
	TenantID   pgtype.UUID
	GoatID     pgtype.UUID
	Role       string
	CreatedAt  pgtype.Timestamptz
}

type IdentityConflictSourceRecord struct {
	ConflictID     pgtype.UUID
	TenantID       pgtype.UUID
	SourceSystem   string
	SourceRecordID string
	CreatedAt      pgtype.Timestamptz
}

type IdentityCorrectionRequest struct {
	CorrectionRequestID pgtype.UUID
	TenantID            pgtype.UUID
	RequestType         string
	State               string
	GoatID              pgtype.UUID
	IdentifierType      pgtype.Text
	IdentifierValue     pgtype.Text
	FarmID              pgtype.UUID
	ParkID              pgtype.UUID
	ShedID              pgtype.UUID
	CohortID            pgtype.UUID
	Description         string
	Evidence            []byte
	RequestedBy         pgtype.UUID
	AssignedReviewerID  pgtype.UUID
	DecisionID          pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	RowVersion          int32
}

type IdentityDecision struct {
	DecisionID          pgtype.UUID
	TenantID            pgtype.UUID
	DecisionType        string
	DecisionResult      string
	DecisionState       string
	DecidedByType       string
	DecidedBy           pgtype.UUID
	PolicyVersion       string
	SourceRecordIds     []string
	SourceIdentifierIds []pgtype.UUID
	SourceGoatIds       []pgtype.UUID
	SourceEventIds      []pgtype.UUID
	SourceMediaIds      []pgtype.UUID
	ModelVersion        pgtype.Text
	Confidence          pgtype.Numeric
	ReviewerID          pgtype.UUID
	Evidence            []byte
	CreatedAt           pgtype.Timestamptz
	ApprovedAt          pgtype.Timestamptz
	DecidedAt           pgtype.Timestamptz
}

type IdentityDecisionEvent struct {
	DecisionID      pgtype.UUID
	TenantID        pgtype.UUID
	EventID         pgtype.UUID
	EventRecordedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type IdentityDecisionGoat struct {
	DecisionID pgtype.UUID
	TenantID   pgtype.UUID
	GoatID     pgtype.UUID
	Role       string
	CreatedAt  pgtype.Timestamptz
}

type IdentityDecisionIdentifier struct {
	DecisionIdentifierID pgtype.UUID
	DecisionID           pgtype.UUID
	TenantID             pgtype.UUID
	IdentifierID         pgtype.UUID
	IdentifierType       pgtype.Text
	IdentifierValue      pgtype.Text
	Action               string
	CreatedAt            pgtype.Timestamptz
}

type IdentityDecisionMedium struct {
	DecisionID pgtype.UUID
	TenantID   pgtype.UUID
	MediaID    pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type InventoryItem struct {
	ItemID     pgtype.UUID
	TenantID   pgtype.UUID
	ItemCode   string
	Name       string
	Category   string
	BaseUnit   string
	Status     string
	Context    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	RowVersion int32
}

type InventoryStock struct {
	StockID          pgtype.UUID
	TenantID         pgtype.UUID
	ItemID           pgtype.UUID
	LocationID       pgtype.UUID
	LotCode          pgtype.Text
	ExpiryDate       pgtype.Date
	QuantityInStock  pgtype.Numeric
	QuantityReserved pgtype.Numeric
	QuantityUnit     string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int32
}

type InventoryStockMovement struct {
	MovementID     pgtype.UUID
	TenantID       pgtype.UUID
	LotID          pgtype.UUID
	ItemID         pgtype.UUID
	LocationID     pgtype.UUID
	MovementType   string
	Quantity       pgtype.Numeric
	QuantityUnit   string
	BatchID        pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
	ActorID        pgtype.UUID
	Reason         pgtype.Text
	IdempotencyKey string
	Context        []byte
}

type Location struct {
	LocationID       pgtype.UUID
	TenantID         pgtype.UUID
	LocationType     string
	LocationCode     pgtype.Text
	Name             string
	ParentLocationID pgtype.UUID
	Country          string
	StateRegion      pgtype.Text
	District         pgtype.Text
	Pincode          pgtype.Text
	Lat              pgtype.Numeric
	Lng              pgtype.Numeric
	Timezone         string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int32
	DisplayOrder     int32
	OperationalNotes pgtype.Text
	RetiredAt        pgtype.Timestamptz
	RetiredBy        pgtype.UUID
}

type LocationAlias struct {
	AliasID             pgtype.UUID
	TenantID            pgtype.UUID
	AliasCode           string
	CanonicalLocationID pgtype.UUID
	SourceContext       string
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	Status              string
	UpdatedAt           pgtype.Timestamptz
	RowVersion          int32
	RetiredAt           pgtype.Timestamptz
}

type LocationCapacityRecord struct {
	CapacityRecordID pgtype.UUID
	TenantID         pgtype.UUID
	LocationID       pgtype.UUID
	CapacityKind     string
	CapacityValue    int32
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	Source           string
	SourceRef        pgtype.Text
	Notes            pgtype.Text
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int32
}

type LocationOperationalAttribute struct {
	TenantID             pgtype.UUID
	LocationID           pgtype.UUID
	UsableForCounts      bool
	UsableForFeed        bool
	UsableForVaccination bool
	UsableForSop         bool
	IsHolding            bool
	IsQuarantine         bool
	IsIcu                bool
	DisplayOrder         int32
	Notes                pgtype.Text
	UpdatedAt            pgtype.Timestamptz
}

type LocationProjectionInvalidation struct {
	InvalidationID     pgtype.UUID
	TenantID           pgtype.UUID
	SourceModule       string
	ProjectionModule   string
	Reason             string
	AffectedLocationID pgtype.UUID
	SourceRef          pgtype.Text
	Status             string
	CreatedAt          pgtype.Timestamptz
	AcknowledgedAt     pgtype.Timestamptz
}

type LocationReviewItem struct {
	ReviewID              pgtype.UUID
	TenantID              pgtype.UUID
	ReviewType            string
	Status                string
	SourceContext         pgtype.Text
	SourceLabel           pgtype.Text
	NormalizedSourceLabel pgtype.Text
	CanonicalLocationID   pgtype.UUID
	CandidateLocationIds  []byte
	EvidenceJson          []byte
	EvidenceHash          string
	CreatedBy             pgtype.UUID
	ResolvedBy            pgtype.UUID
	ResolutionNotes       pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ResolvedAt            pgtype.Timestamptz
	RowVersion            int32
}

type MovementCommand struct {
	CommandID    pgtype.UUID
	TenantID     pgtype.UUID
	TaskID       pgtype.UUID
	SubmissionID pgtype.UUID
	CommandType  string
	State        string
	Payload      []byte
	CreatedAt    pgtype.Timestamptz
}

type NotificationRequest struct {
	NotificationRequestID pgtype.UUID
	TenantID              pgtype.UUID
	CalendarEventID       string
	TargetType            string
	TargetID              pgtype.UUID
	NotificationType      string
	Channel               string
	RecipientRef          pgtype.Text
	Title                 string
	Body                  string
	Status                string
	RequestedBy           pgtype.UUID
	RequestedAt           pgtype.Timestamptz
	SentAt                pgtype.Timestamptz
	ReadAt                pgtype.Timestamptz
	FailureReason         pgtype.Text
	IdempotencyKey        string
	RequestFingerprint    string
	Context               []byte
	TraceID               pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeliveryAttempts      int32
	NextAttemptAt         pgtype.Timestamptz
	LeasedAt              pgtype.Timestamptz
	LeaseToken            pgtype.UUID
	DeliveredBy           pgtype.Text
}

type ObligationBatch struct {
	BatchID               pgtype.UUID
	TenantID              pgtype.UUID
	ProtocolVersionID     pgtype.UUID
	ScopeType             string
	ScopeID               pgtype.UUID
	Session               pgtype.Text
	PlannedDate           pgtype.Date
	WindowStart           pgtype.Timestamptz
	WindowEnd             pgtype.Timestamptz
	Status                string
	EstimatedTargets      int32
	PlannedQuantity       pgtype.Numeric
	ReservedQuantity      pgtype.Numeric
	UsedQuantity          pgtype.Numeric
	QuantityUnit          pgtype.Text
	PrimaryInventoryLotID pgtype.UUID
	SopTaskID             pgtype.UUID
	ConductedBy           pgtype.UUID
	ProofRef              pgtype.Text
	Context               []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RowVersion            int32
}

type ObligationEscalation struct {
	EscalationID        pgtype.UUID
	TenantID            pgtype.UUID
	ObligationID        pgtype.UUID
	Level               int32
	EscalatedToUserID   pgtype.UUID
	EscalatedToRole     pgtype.Text
	Reason              string
	Status              string
	OpenedAt            pgtype.Timestamptz
	AcknowledgedAt      pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	AcknowledgedBy      pgtype.UUID
	ResolvedBy          pgtype.UUID
	AcknowledgementNote string
	ResolutionNote      string
}

type ObligationGoatShiftWatermark struct {
	TenantID       pgtype.UUID
	GoatID         pgtype.UUID
	LastOccurredAt pgtype.Timestamptz
	LastEventID    string
	LastScopeType  string
	LastScopeID    pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type ObligationInstance struct {
	ObligationID         pgtype.UUID
	TenantID             pgtype.UUID
	ProtocolVersionID    pgtype.UUID
	RuleID               pgtype.UUID
	BatchID              pgtype.UUID
	TargetType           string
	TargetID             pgtype.UUID
	ScopeType            string
	ScopeID              pgtype.UUID
	DueAt                pgtype.Timestamptz
	WindowStart          pgtype.Timestamptz
	WindowEnd            pgtype.Timestamptz
	Status               string
	SopTaskID            pgtype.UUID
	IdempotencyKey       string
	GeneratedByTriggerID pgtype.UUID
	Sequence             int32
	CompletedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RowVersion           int32
}

type ObligationStatusEvent struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202606 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202607 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202608 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202609 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202610 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202611 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEvents202612 struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type ObligationStatusEventsDefault struct {
	ObligationEventID pgtype.UUID
	TenantID          pgtype.UUID
	ObligationID      pgtype.UUID
	EventType         string
	OccurredAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.UUID
	Payload           []byte
	IdempotencyKey    string
}

type Org struct {
	PartyID   pgtype.UUID
	OrgType   string
	LegalName pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OutboxDlqAction struct {
	ActionID       pgtype.UUID
	TenantID       pgtype.UUID
	IdempotencyKey string
	Action         string
	RequestHash    string
	Reason         string
	OutboxIds      []string
	Status         string
	UpdatedCount   int64
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OutboxMessage struct {
	OutboxID       pgtype.UUID
	TenantID       pgtype.UUID
	EventID        pgtype.UUID
	EventType      string
	SchemaVersion  string
	AggregateType  string
	AggregateID    pgtype.UUID
	Topic          string
	Payload        []byte
	Headers        []byte
	IdempotencyKey string
	TraceID        pgtype.Text
	Status         string
	AttemptCount   int32
	NextAttemptAt  pgtype.Timestamptz
	LastError      pgtype.Text
	PublishedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ReplayCount    int32
}

type ParkProfile struct {
	LocationID pgtype.UUID
	TenantID   pgtype.UUID
	ParkCode   pgtype.Text
	Capacity   pgtype.Int4
	Notes      string
	Context    []byte
	RowVersion int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Party struct {
	PartyID     pgtype.UUID
	PartyType   string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProcurementHfVaccinationEvidence struct {
	EvidenceID        pgtype.UUID
	TenantID          pgtype.UUID
	LoadID            pgtype.UUID
	GoatID            pgtype.UUID
	ProtocolVersionID pgtype.UUID
	RuleID            pgtype.UUID
	DoseCode          string
	AdministeredAt    pgtype.Timestamptz
	VaccineName       string
	LotNumber         string
	ProofRefID        pgtype.UUID
	SourceRef         string
	ReviewStatus      string
	ReviewedBy        pgtype.UUID
	ReviewedAt        pgtype.Timestamptz
	ReviewReason      string
	IdempotencyKey    string
	ImportedBy        pgtype.UUID
	ImportedAt        pgtype.Timestamptz
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
}

type ProcurementLoad struct {
	LoadID            pgtype.UUID
	TenantID          pgtype.UUID
	SourcePartyID     pgtype.UUID
	SourceLocationID  pgtype.UUID
	ExpectedCount     int32
	PurchaseDate      pgtype.Date
	PlannedDispatchAt pgtype.Timestamptz
	Status            string
	Notes             string
	Context           []byte
	IdempotencyKey    string
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
}

type ProcurementLoadGoat struct {
	LoadGoatID        pgtype.UUID
	TenantID          pgtype.UUID
	LoadID            pgtype.UUID
	GoatID            pgtype.UUID
	AnimalIdentifier1 pgtype.Text
	AnimalIdentifier2 pgtype.Text
	SelectionState    string
	SelectionReason   string
	CurrentState      string
	SourceEntryState  string
	SourceEntryRef    pgtype.Text
	OwnershipState    string
	HealthState       string
	WarmupStartedAt   pgtype.Timestamptz
	WarmupEndedAt     pgtype.Timestamptz
	WarmupDays        pgtype.Int4
	HoldingLocationID pgtype.UUID
	LoadedAt          pgtype.Timestamptz
	ArrivedAt         pgtype.Timestamptz
	IntakeAcceptedAt  pgtype.Timestamptz
	ExitReason        pgtype.Text
	ProofRefs         []byte
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
	Purpose           string
}

type ProcurementPhcHandoff struct {
	HandoffID                 pgtype.UUID
	TenantID                  pgtype.UUID
	LoadID                    pgtype.UUID
	GoatID                    pgtype.UUID
	AcceptedAt                pgtype.Timestamptz
	ParkLocationID            pgtype.UUID
	ShedLocationID            pgtype.UUID
	EntryDate                 pgtype.Date
	TrustedVaccinationHistory []byte
	IntakeHealthSignal        pgtype.Text
	EventStatus               string
	IdempotencyKey            string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type ProcurementSourceHealthCheck struct {
	HealthCheckID  pgtype.UUID
	TenantID       pgtype.UUID
	GoatID         pgtype.UUID
	LoadID         pgtype.UUID
	HealthState    string
	Reason         string
	CheckedBy      pgtype.UUID
	CheckedAt      pgtype.Timestamptz
	ProofRefID     pgtype.UUID
	SopTaskID      pgtype.UUID
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

type ProofArtifact struct {
	ProofID         pgtype.UUID
	TenantID        pgtype.UUID
	StorageProvider string
	ObjectKey       string
	ContentHash     string
	MimeType        string
	SizeBytes       int64
	DurationMs      pgtype.Int8
	UploadState     string
	ScopeType       string
	ScopeID         pgtype.UUID
	SubjectType     string
	SubjectID       pgtype.UUID
	ProofType       string
	UploadedBy      pgtype.UUID
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UploadedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	RowVersion      int32
}

type ProtocolDefinition struct {
	ProtocolID pgtype.UUID
	TenantID   pgtype.UUID
	Code       string
	Name       string
	Category   string
	Status     string
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	RowVersion int32
}

type ProtocolRule struct {
	RuleID              pgtype.UUID
	TenantID            pgtype.UUID
	ProtocolVersionID   pgtype.UUID
	DoseCode            string
	Sequence            int32
	TriggerType         string
	OffsetDays          int32
	DueWindowDays       int32
	MinGapDays          int32
	Repeat              string
	RepeatUntilAfterAge pgtype.Text
	CatchUp             string
	EligibilityJson     []byte
	SopVersionID        pgtype.UUID
	ProofPolicy         []byte
	WithdrawalDays      pgtype.Int4
	SortOrder           int32
	CreatedAt           pgtype.Timestamptz
}

type ProtocolTrigger struct {
	TriggerID         pgtype.UUID
	TenantID          pgtype.UUID
	ProtocolVersionID pgtype.UUID
	TriggerType       string
	TriggerConfig     []byte
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
}

type ProtocolVersion struct {
	ProtocolVersionID pgtype.UUID
	TenantID          pgtype.UUID
	ProtocolID        pgtype.UUID
	ScopeType         string
	ScopeID           pgtype.UUID
	Version           int32
	VersionLabel      string
	Status            string
	EffectiveFrom     pgtype.Date
	EffectiveTo       pgtype.Date
	RuleDsl           []byte
	ProofPolicy       []byte
	SopVersionID      pgtype.UUID
	DraftedBy         pgtype.UUID
	PublishedBy       pgtype.UUID
	PublishedAt       pgtype.Timestamptz
	RetiredAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
}

type ShedLifecycleStatusLookup struct {
	ShedLifecycleStatusID pgtype.UUID
	TenantID              pgtype.UUID
	StatusCode            string
	Name                  string
	SortOrder             int32
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ShedProfile struct {
	LocationID            pgtype.UUID
	TenantID              pgtype.UUID
	AnimalStageID         pgtype.UUID
	ShedLifecycleStatusID pgtype.UUID
	Sex                   pgtype.Text
	Capacity              pgtype.Int4
	HasIcu                bool
	Notes                 string
	Context               []byte
	RowVersion            int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ShiftingEvent struct {
	ShiftingEventID         pgtype.UUID
	TenantID                pgtype.UUID
	LogicalShiftingEventKey string
	Priority                string
	Category                string
	SourceParkID            pgtype.UUID
	SourceShedID            pgtype.UUID
	DestinationParkID       pgtype.UUID
	DestinationShedID       pgtype.UUID
	RaisedAt                pgtype.Timestamptz
	EffectiveAt             pgtype.Timestamptz
	AuthorizedAt            pgtype.Timestamptz
	AuthorizedBy            pgtype.UUID
	AuthorizationState      string
	VerificationState       string
	EventStatus             string
	SourceSystem            string
	SourceRef               string
	ProofRef                pgtype.Text
	PayloadHash             string
	IdempotencyKey          string
	RequestFingerprint      string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	RowVersion              int32
}

type ShiftingEventImpact struct {
	ShiftingEventImpactID        pgtype.UUID
	TenantID                     pgtype.UUID
	ShiftingEventID              pgtype.UUID
	GrainKey                     string
	BreedID                      pgtype.UUID
	BreedKey                     string
	BreedLabel                   string
	StageTag                     pgtype.Text
	AgeClass                     pgtype.Text
	Sex                          pgtype.Text
	HeadCount                    int32
	PregnantCount                int32
	LactatingCount               int32
	WarmupCount                  int32
	RiskFlags                    []byte
	RationContextResolutionState string
	RationContextRef             pgtype.Text
	BlockerReason                pgtype.Text
	CreatedAt                    pgtype.Timestamptz
}

type SopDefinition struct {
	SopID       pgtype.UUID
	TenantID    pgtype.UUID
	Code        string
	Name        string
	Description string
	Status      string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	RowVersion  int32
}

type SopSubmission struct {
	SubmissionID     pgtype.UUID
	TenantID         pgtype.UUID
	TaskID           pgtype.UUID
	SopVersionID     pgtype.UUID
	SubmittedBy      pgtype.UUID
	IdempotencyKey   string
	Answers          []byte
	ProofRefs        []byte
	State            string
	ValidationReport []byte
	SubmittedAt      pgtype.Timestamptz
	AcceptedAt       pgtype.Timestamptz
	RowVersion       int32
}

type SopSubmissionItem struct {
	ItemID       pgtype.UUID
	TenantID     pgtype.UUID
	SubmissionID pgtype.UUID
	TaskID       pgtype.UUID
	GoatID       pgtype.UUID
	ItemKey      string
	State        string
	Result       []byte
	CreatedAt    pgtype.Timestamptz
}

type SopTask struct {
	TaskID       pgtype.UUID
	TenantID     pgtype.UUID
	SopID        pgtype.UUID
	SopVersionID pgtype.UUID
	TaskType     string
	Title        string
	Description  string
	State        string
	AssignedTo   pgtype.UUID
	ScopeType    string
	ScopeID      pgtype.UUID
	Priority     string
	DueAt        pgtype.Timestamptz
	Context      []byte
	CreatedBy    pgtype.UUID
	VerifiedBy   pgtype.UUID
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	RowVersion   int32
}

type SopTaskReviewFanout struct {
	ReviewFanoutID pgtype.UUID
	TenantID       pgtype.UUID
	TaskID         pgtype.UUID
	TaskRowVersion int32
	Outcome        string
	Status         string
	RequestedBy    pgtype.UUID
	Reason         string
	AttemptCount   int32
	LastError      string
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type SopTaskSubmissionFanout struct {
	SubmissionFanoutID pgtype.UUID
	TenantID           pgtype.UUID
	TaskID             pgtype.UUID
	SubmissionID       pgtype.UUID
	Status             string
	RequestedBy        pgtype.UUID
	AttemptCount       int32
	LastError          string
	CompletedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SopVersion struct {
	SopVersionID     pgtype.UUID
	TenantID         pgtype.UUID
	SopID            pgtype.UUID
	Version          int32
	VersionLabel     string
	Status           string
	FormDsl          []byte
	ProofPolicy      []byte
	Compatibility    []byte
	ValidationReport []byte
	CreatedBy        pgtype.UUID
	PublishedBy      pgtype.UUID
	PublishedAt      pgtype.Timestamptz
	RetiredAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int32
}

type SourceEntryDecision struct {
	DecisionID      pgtype.UUID
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	LoadID          pgtype.UUID
	DecisionStage   string
	DecisionType    string
	Reason          string
	DecidedBy       pgtype.UUID
	DecidedAt       pgtype.Timestamptz
	ProofRefID      pgtype.UUID
	SopTaskID       pgtype.UUID
	OwnerID         pgtype.UUID
	ResumeCondition pgtype.Text
	IdempotencyKey  string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
}

type SourceHoldingStay struct {
	StayID            pgtype.UUID
	TenantID          pgtype.UUID
	GoatID            pgtype.UUID
	LoadID            pgtype.UUID
	HoldingLocationID pgtype.UUID
	StartedAt         pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	WarmupState       string
	WarmupDays        pgtype.Int4
	HealthState       string
	OwnershipState    string
	Status            string
	ProofRefs         []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
	Purpose           string
}

type StatusDefinition struct {
	StatusCode           string
	Axis                 string
	DisplayName          string
	ShortLabel           string
	Description          pgtype.Text
	SortOrder            int32
	Active               bool
	ExpectedDurationDays pgtype.Int4
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Tenant struct {
	TenantID  pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TransitHandoff struct {
	HandoffID        pgtype.UUID
	TenantID         pgtype.UUID
	LoadID           pgtype.UUID
	FromLocationID   pgtype.UUID
	ToLocationID     pgtype.UUID
	LoadedCount      int32
	DispatchedAt     pgtype.Timestamptz
	ArrivedAt        pgtype.Timestamptz
	ProofRefID       pgtype.UUID
	DiscrepancyState string
	Status           string
	IdempotencyKey   string
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int32
}

type UserScopeGrant struct {
	GrantID   pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	ScopeType string
	ScopeID   pgtype.UUID
	Status    string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type VaccinationCompletion struct {
	CompletionID             pgtype.UUID
	TenantID                 pgtype.UUID
	ObligationID             pgtype.UUID
	BatchID                  pgtype.UUID
	GoatID                   pgtype.UUID
	SopSubmissionItemID      pgtype.UUID
	VaccineInventoryLotID    pgtype.UUID
	Doses                    pgtype.Int4
	DoseMlGiven              pgtype.Numeric
	RouteSite                pgtype.Text
	AdverseReaction          bool
	AdverseReactionProblemID pgtype.UUID
	ColdChainVerified        bool
	AdministeredAt           pgtype.Timestamptz
	Status                   string
	VerifiedBy               pgtype.UUID
	VerifiedAt               pgtype.Timestamptz
	RejectionReason          pgtype.Text
	WithdrawalUntilDate      pgtype.Date
	RecordedBy               pgtype.UUID
	IdempotencyKey           string
	RowVersion               int32
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type VaccinationGenerationRun struct {
	RunID                         pgtype.UUID
	TenantID                      pgtype.UUID
	ProtocolVersionID             pgtype.UUID
	TriggerType                   string
	TriggerRef                    pgtype.Text
	Status                        string
	StartedAt                     pgtype.Timestamptz
	CompletedAt                   pgtype.Timestamptz
	GeneratedCount                int32
	DeferredCount                 int32
	SkippedNoDueDateCount         int32
	SuppressedTrustedHistoryCount int32
	CursorGoatID                  pgtype.UUID
	LastError                     pgtype.Text
	IdempotencyKey                string
	Context                       []byte
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	RowVersion                    int32
	ReopenedCount                 int32
}

type Vaccine struct {
	VaccineID      pgtype.UUID
	TenantID       pgtype.UUID
	ItemID         pgtype.UUID
	Disease        pgtype.Text
	Manufacturer   pgtype.Text
	DosesPerVial   pgtype.Int4
	WithdrawalDays pgtype.Int4
	Context        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type VwGoatTagging struct {
	TenantID         pgtype.UUID
	GoatID           pgtype.UUID
	IdentifierID     pgtype.UUID
	IdentifierType   string
	IdentifierValue  string
	NormalizedValue  string
	ScopeKey         string
	IsPrimaryForGoat bool
	Status           string
	ValidFrom        pgtype.Timestamptz
	ValidTo          pgtype.Timestamptz
}

type VwProcurementVaccinationExcludedGoat struct {
	TenantID        pgtype.UUID
	GoatID          pgtype.UUID
	ExclusionReason string
}

type WorkforceAbsence struct {
	AbsenceID           pgtype.UUID
	TenantID            pgtype.UUID
	WorkforceMemberID   pgtype.UUID
	ScopeType           string
	ScopeID             pgtype.UUID
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	ReasonCode          string
	Status              string
	ReplacementMemberID pgtype.UUID
	CreatedBy           pgtype.UUID
	ApprovedBy          pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RowVersion          int32
}

type WorkforceCapability struct {
	CapabilityID   pgtype.UUID
	TenantID       pgtype.UUID
	CapabilityCode string
	Description    string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type WorkforceExternalIdentity struct {
	ExternalIdentityID   pgtype.UUID
	TenantID             pgtype.UUID
	WorkforceMemberID    pgtype.UUID
	SourceSystem         string
	SourceFlow           string
	ExternalRefType      string
	ExternalRefHash      string
	EncryptedExternalRef []byte
	Status               string
	Confidence           pgtype.Numeric
	FirstSeenAt          pgtype.Timestamptz
	LastSeenAt           pgtype.Timestamptz
	ObservationCount     int64
	ReviewedBy           pgtype.UUID
	ReviewedAt           pgtype.Timestamptz
	ReviewReason         pgtype.Text
	Metadata             []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RowVersion           int32
}

type WorkforceMember struct {
	WorkforceMemberID pgtype.UUID
	TenantID          pgtype.UUID
	UserID            pgtype.UUID
	DisplayCode       string
	DisplayName       string
	Status            string
	PrimaryRoleHint   string
	PrimaryLocationID pgtype.UUID
	Metadata          []byte
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RowVersion        int32
}

type WorkforceMemberAppSession struct {
	SessionID         pgtype.UUID
	TenantID          pgtype.UUID
	WorkforceMemberID pgtype.UUID
	DeviceID          pgtype.UUID
	AuthSubject       pgtype.UUID
	StartedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	Status            string
	AppVersion        string
	IpHash            pgtype.Text
	Metadata          []byte
}

type WorkforceMemberCapability struct {
	MemberCapabilityID pgtype.UUID
	TenantID           pgtype.UUID
	WorkforceMemberID  pgtype.UUID
	CapabilityID       pgtype.UUID
	ScopeType          string
	ScopeID            pgtype.UUID
	Status             string
	ValidFrom          pgtype.Timestamptz
	ValidTo            pgtype.Timestamptz
	AssignedBy         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type WorkforceMemberDevice struct {
	DeviceID            pgtype.UUID
	TenantID            pgtype.UUID
	WorkforceMemberID   pgtype.UUID
	Platform            string
	AppInstallID        string
	DevicePublicKeyHash pgtype.Text
	PushTokenHash       pgtype.Text
	AppVersion          string
	OsVersion           string
	Status              string
	LastSeenAt          pgtype.Timestamptz
	RegisteredBy        pgtype.UUID
	RegisteredAt        pgtype.Timestamptz
	RevokedBy           pgtype.UUID
	RevokedAt           pgtype.Timestamptz
	Metadata            []byte
	RowVersion          int32
}

type WorkforceRosterAssignment struct {
	RosterAssignmentID    pgtype.UUID
	TenantID              pgtype.UUID
	WorkforceMemberID     pgtype.UUID
	TeamID                pgtype.UUID
	ScopeType             string
	ScopeID               pgtype.UUID
	ShiftDate             pgtype.Date
	ShiftStartAt          pgtype.Timestamptz
	ShiftEndAt            pgtype.Timestamptz
	TaskType              pgtype.Text
	Status                string
	EscalationOwnerUserID pgtype.UUID
	CreatedBy             pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RowVersion            int32
}
