// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package inventorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT item_id::text AS item_id, item_code, name, category, base_unit, status, row_version
FROM inventory_items
WHERE tenant_id = $1 AND item_id = $2
`

type GetInventoryItemParams struct {
	TenantID pgtype.UUID
	ItemID   pgtype.UUID
}

type GetInventoryItemRow struct {
	ItemID     string
	ItemCode   string
	Name       string
	Category   string
	BaseUnit   string
	Status     string
	RowVersion int32
}

func (q *Queries) GetInventoryItem(ctx context.Context, arg GetInventoryItemParams) (GetInventoryItemRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, arg.TenantID, arg.ItemID)
	var i GetInventoryItemRow
	err := row.Scan(
		&i.ItemID,
		&i.ItemCode,
		&i.Name,
		&i.Category,
		&i.BaseUnit,
		&i.Status,
		&i.RowVersion,
	)
	return i, err
}

const getStockLot = `-- name: GetStockLot :one
SELECT stock_id::text AS stock_id, item_id::text AS item_id, location_id::text AS location_id,
       quantity_in_stock, quantity_reserved, quantity_unit, row_version
FROM inventory_stock
WHERE tenant_id = $1 AND stock_id = $2
`

type GetStockLotParams struct {
	TenantID pgtype.UUID
	StockID  pgtype.UUID
}

type GetStockLotRow struct {
	StockID          string
	ItemID           string
	LocationID       string
	QuantityInStock  pgtype.Numeric
	QuantityReserved pgtype.Numeric
	QuantityUnit     string
	RowVersion       int32
}

func (q *Queries) GetStockLot(ctx context.Context, arg GetStockLotParams) (GetStockLotRow, error) {
	row := q.db.QueryRow(ctx, getStockLot, arg.TenantID, arg.StockID)
	var i GetStockLotRow
	err := row.Scan(
		&i.StockID,
		&i.ItemID,
		&i.LocationID,
		&i.QuantityInStock,
		&i.QuantityReserved,
		&i.QuantityUnit,
		&i.RowVersion,
	)
	return i, err
}

const pickFEFOLot = `-- name: PickFEFOLot :one
SELECT stock_id::text AS stock_id, lot_code, expiry_date,
       quantity_in_stock, quantity_reserved,
       (quantity_in_stock - quantity_reserved)::numeric AS available_quantity,
       quantity_unit
FROM inventory_stock
WHERE tenant_id = $1
  AND location_id = $2
  AND item_id = $3
  AND quantity_in_stock > 0
  AND quantity_in_stock > quantity_reserved
  AND status = 'active'
  AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE)
ORDER BY expiry_date ASC NULLS LAST, stock_id ASC
LIMIT 1
`

type PickFEFOLotParams struct {
	TenantID   pgtype.UUID
	LocationID pgtype.UUID
	ItemID     pgtype.UUID
}

type PickFEFOLotRow struct {
	StockID           string
	LotCode           pgtype.Text
	ExpiryDate        pgtype.Date
	QuantityInStock   pgtype.Numeric
	QuantityReserved  pgtype.Numeric
	AvailableQuantity pgtype.Numeric
	QuantityUnit      string
}

// FEFO: earliest-expiring lot with AVAILABLE (unreserved) stock at a location for an item.
// Keeps an explicit quantity_in_stock > 0 so the partial index inventory_stock_fefo_idx
// (tenant_id, location_id, item_id, expiry_date) WHERE quantity_in_stock > 0 is used; the
// quantity_in_stock > quantity_reserved guard skips fully-reserved lots; returns available qty.
// Expired/quarantined/depleted lots are excluded so vaccination drives cannot silently proceed on
// bad stock.
func (q *Queries) PickFEFOLot(ctx context.Context, arg PickFEFOLotParams) (PickFEFOLotRow, error) {
	row := q.db.QueryRow(ctx, pickFEFOLot, arg.TenantID, arg.LocationID, arg.ItemID)
	var i PickFEFOLotRow
	err := row.Scan(
		&i.StockID,
		&i.LotCode,
		&i.ExpiryDate,
		&i.QuantityInStock,
		&i.QuantityReserved,
		&i.AvailableQuantity,
		&i.QuantityUnit,
	)
	return i, err
}
