package app

// phoneTaskCopy is the "Task with its own phone tab" editor's wording on every module SOP page
// (docs/decisions/simple-task-phone-tabs.md), served through the page contract so the editor
// renders backend copy. Work instructions carry no phone task and get none of it.
var phoneTaskCopy = map[string]string{
	"ptask.action.new":                 "New phone task",
	"ptask.action.edit":                "Edit phone task",
	"ptask.card.park":                  "park",
	"ptask.card.parks":                 "parks",
	"ptask.card.video":                 "video",
	"ptask.card.videos":                "videos",
	"ptask.card.photo":                 "photo",
	"ptask.card.photos":                "photos",
	"ptask.card.question":              "question",
	"ptask.card.questions":             "questions",
	"ptask.card.tag":                   "Phone tab",
	"ptask.title":                      "Task with its own phone tab",
	"ptask.subtitle":                   "A simple task the phone shows in its own tab in this module: which pens, when, who does it at each park, and what they record. Publishing it puts the tab on the phone.",
	"ptask.notice.versions":            "Every publish is a new version. A check already raised keeps the form it was raised with.",
	"ptask.back":                       "Back to SOPs",
	"ptask.section.tab":                "Phone tab",
	"ptask.field.name":                 "Tab name",
	"ptask.hint.name":                  "Also the SOP's name. Shown under the icon in this module's bottom bar, up to 24 letters.",
	"ptask.hint.name_fixed":            "The name is fixed once the SOP exists.",
	"ptask.field.icon":                 "Icon",
	"ptask.field.icon_choose":          "Choose an icon",
	"ptask.field.filters":              "Filters on the list",
	"ptask.hint.filters":               "The filters the phone shows above the list.",
	"ptask.field.instruction":          "What to do",
	"ptask.section.pens":               "Pens",
	"ptask.field.occupied_only":        "Skip empty pens",
	"ptask.hint.park_scope":            "One task for the whole park, not one per pen.",
	"ptask.hint.selected_pens":         "Tick the pens at each park below.",
	"ptask.section.capture":            "What to record",
	"ptask.field.review":               "Review",
	"ptask.section.parks":              "Parks and who does it",
	"ptask.hint.parks":                 "Tick each park the task runs at and choose the one person who does it there.",
	"ptask.field.assignee":             "Who does it",
	"ptask.field.pens":                 "Pens at this park",
	"ptask.assignee.search":            "Type a name",
	"ptask.assignee.none":              "Nobody by that name.",
	"ptask.assignee.placeholder":       "Choose a person",
	"ptask.assignee.unavailable":       "No longer does routines at this park. Choose someone else.",
	"ptask.empty.people":               "Nobody can do routines at this park yet.",
	"ptask.filter.pens_search":         "Find a pen",
	"ptask.action.select_all_pens":     "Select all",
	"ptask.action.clear_pens":          "Clear",
	"ptask.count.pens_chosen":          "{chosen} of {total} chosen",
	"ptask.label.pen_empty":            "No animals",
	"ptask.empty.pens_search":          "No pen matches that name.",
	"ptask.error.catalog":              "This park's pens and people could not be read. Try again.",
	"ptask.error.load":                 "The phone tab choices could not be read. Try again.",
	"ptask.action.save_draft":          "Save draft",
	"ptask.action.publish":             "Publish",
	"ptask.problem.name":               "Give the task a name.",
	"ptask.problem.name_long":          "The tab name fits 24 letters.",
	"ptask.problem.icon":               "Choose an icon.",
	"ptask.problem.park":               "Tick at least one park.",
	"ptask.problem.assignee":           "Choose who does it at {park}.",
	"ptask.problem.pens":               "Tick at least one pen at {park}.",
	"ptask.footer.ready":               "Ready to save.",
	"ptask.saved":                      "Saved as a draft. Publish it to put the tab on the phone.",
	"ptask.failed":                     "The task could not be saved. Try again.",
	"ptask.field.cadence":              "When",
	"ptask.field.weekdays":             "Weekdays",
	"ptask.field.month_days":           "Days of the month",
	"ptask.field.after_work_kinds":     "After which work",
	"ptask.field.due_offset_days":      "Days after",
	"ptask.field.notify_time":          "Push at",
	"ptask.field.interval_days":        "Every how many days",
	"ptask.field.start_date":           "Starting from",
	"ptask.date.previous_month":        "Previous month",
	"ptask.date.next_month":            "Next month",
	"ptask.date.invalid":               "Pick a date on or after {date}.",
	"ptask.field.questions":            "Questions",
	"ptask.field.question_title":       "Question",
	"ptask.field.question_id":          "Key",
	"ptask.field.question_kind":        "Answer type",
	"ptask.field.question_hint":        "Hint",
	"ptask.field.question_required":    "Required",
	"ptask.field.question_unit":        "Unit",
	"ptask.field.question_options":     "Choices",
	"ptask.field.question_proof":       "Proof for this question",
	"ptask.field.question_proof_count": "How many",
	"ptask.field.option_value":         "Value",
	"ptask.field.option_label":         "Label",
	"ptask.field.photo":                "Photos",
	"ptask.field.video":                "Videos",
	"ptask.field.presence":             "Pen check-in",
	"ptask.field.min":                  "At least",
	"ptask.field.max":                  "At most",
	"ptask.action.add_question":        "Add question",
	"ptask.action.remove_question":     "Remove question",
	"ptask.action.add_option":          "Add option",
	"ptask.action.remove_option":       "Remove option",
}

// sopManagedCopy is the /routines note on a routine that comes from a module's phone-task SOP.
var sopManagedCopy = map[string]string{
	"sop_managed.note":               "From {module}. Edit it there.",
	"sop_managed.module.pc_care":     "Preventive Care SOP",
	"sop_managed.module.feed":        "Feed SOP",
	"sop_managed.module.weighing":    "Weighing SOP",
	"sop_managed.module.counts":      "Herd Operations SOP",
	"sop_managed.module.milk":        "Milk SOP",
	"sop_managed.module.procurement": "Procurement SOP",
	"sop_managed.module.sales":       "Sales SOP",
	"sop_managed.module.unknown":     "a module SOP",
}
